<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.1 Leçon | Statistiques avec R</title>
  <meta name="description" content="7.1 Leçon | Statistiques avec R" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="7.1 Leçon | Statistiques avec R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="7.1 Leçon | Statistiques avec R" />
  <meta name="github-repo" content="sci1018/sci1018" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.1 Leçon | Statistiques avec R" />
  
  <meta name="twitter:description" content="7.1 Leçon | Statistiques avec R" />
  

<meta name="author" content="" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lecon7.html"/>
<link rel="next" href="lecon8.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TÉLUQ - SCI 1018</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="part"><span><b>I SCI 1018</b></span></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html"><i class="fa fa-check"></i>À propos du cours</a>
<ul>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#pr%C3%A9sentation"><i class="fa fa-check"></i>Présentation</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#route"><i class="fa fa-check"></i>Feuille de route</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#cr%C3%A9dits"><i class="fa fa-check"></i>Crédits</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html"><i class="fa fa-check"></i>Ressources</a>
<ul>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#travaux-not%C3%A9s"><i class="fa fa-check"></i>Travaux notés</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#donn%C3%A9es"><i class="fa fa-check"></i>Données</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#forum"><i class="fa fa-check"></i>Forum du cours</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#guides-r"><i class="fa fa-check"></i>Guides R</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#ressources-r"><i class="fa fa-check"></i>Ressources R</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#ressources-r-commander"><i class="fa fa-check"></i>Ressources R commander</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#r%C3%A9f%C3%A9rences"><i class="fa fa-check"></i>Références</a></li>
</ul></li>
<li class="part"><span><b>II GUIDE R</b></span></li>
<li class="chapter" data-level="" data-path="InstallationR.html"><a href="InstallationR.html"><i class="fa fa-check"></i>Installation de R</a>
<ul>
<li class="chapter" data-level="" data-path="InstallationR.html"><a href="InstallationR.html#o%C3%B9-se-procurer"><i class="fa fa-check"></i>Où se procurer ?</a></li>
<li class="chapter" data-level="" data-path="pour-débuter-avec-r.html"><a href="pour-débuter-avec-r.html"><i class="fa fa-check"></i>Pour débuter avec R</a></li>
<li class="chapter" data-level="" data-path="choisir-son-éditeur.html"><a href="choisir-son-éditeur.html"><i class="fa fa-check"></i>Choisir son éditeur</a></li>
</ul></li>
<li class="part"><span><b>III APPRENTISSAGE</b></span></li>
<li class="chapter" data-level="" data-path="programmation-avec-r.html"><a href="programmation-avec-r.html"><i class="fa fa-check"></i>Programmation avec R</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistiques avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="leçon-6" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Leçon<a href="leçon-6.html#le%C3%A7on-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="anova-à-deux-critères" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> ANOVA à deux critères<a href="leçon-6.html#anova-%C3%A0-deux-crit%C3%A8res" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On pourrait avoir le réflexe d’effectuer deux analyses, en effectuant une ANOVA à un critère sur chacun des facteurs pris séparément. Toutefois, cette approche n’est pas optimale, puisqu’effectuer deux tests séparément augmentera notre probabilité de commettre une erreur de type I (c.-à-d., un faux positif). En plus de tester l’effet de chacun des facteurs sur la variable réponse, l’ANOVA à deux critères permet de tester si l’effet d’un facteur dépend du niveau de l’autre. C’est ce qu’on entend par l’<strong>interaction</strong> entre les deux facteurs sur la variable réponse. Ainsi, nous dirons qu’il y a interaction entre le traitement hormonal et le sexe lorsque l’effet du traitement sur la concentration en calcium est soit plus grand ou plus petit selon le sexe des individus étudiés, et vice-versa, c’est-à-dire que la différence de la variable réponse entre mâle et femelle dépend du traitement hormonal. L’interaction est souvent d’intérêt puisqu’elle révèle un patron inattendu.</p>
<p>À noter qu’on peut tester le terme d’interaction uniquement lorsqu’on a plus d’une observation pour chaque combinaison des groupes des deux facteurs (p. ex., mâle avec traitement, mâle sans traitement, femelle avec traitement, femelle sans traitement). On dit alors qu’il y a des <strong>répétitions</strong> (<em>replication</em>). Nous illustrerons le concept de l’interaction dans les exemples de cette leçon. L’ANOVA à un critère effectuée séparément sur chaque traitement ne permet pas de tester d’interaction, et c’est pourquoi il est préférable d’utiliser l’ANOVA à deux critères pour analyser les données en une seule étape.</p>
</div>
<div id="suppositions-et-dispositif-expérimental" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Suppositions et dispositif expérimental<a href="leçon-6.html#suppositions-et-dispositif-exp%C3%A9rimental" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>L’ANOVA à deux critères requiert les mêmes suppositions que l’ANOVA à un critère, soit l’indépendance des observations, l’homoscédasticité et la normalité des résidus. Toutefois, le design expérimental de l’ANOVA à deux critères diffère légèrement de celui de l’ANOVA à un critère. À titre de rappel, l’ANOVA à un critère utilise un dispositif expérimental complètement aléatoire. On attribue aléatoirement un traitement (c.-à-d., un des niveaux du facteur testé) à chacune des unités expérimentales. Ici, l’unité expérimentale dépend de l’expérience, mais peut être constituée d’un patient, d’un client sondé au téléphone, d’un quadrat, d’un aquarium, ou d’un site, par exemple. Dans une expérience avec deux facteurs, nous attribuerons aléatoirement une combinaison des deux facteurs à chaque unité expérimentale.</p>
<p>Reprenons notre exemple sur le traitement hormonal en fonction du sexe. Quatre combinaisons de groupes des deux facteurs sont possibles: mâle sans traitement, mâle avec traitement hormonal, femelle sans traitement et femelle avec traitement hormonal. Un <strong>dispositif équilibré</strong> (<em>balanced design</em>), c’est-à-dire, une expérience avec un nombre égal d’observations pour chaque combinaison des traitements, procure une puissance plus élevée qu’un dispositif avec un nombre inégal d’observations par combinaison des traitements. Ainsi, on devrait sélectionner un nombre égal de mâles et de femelles et attribuer le traitement à la moitié des mâles et des femelles.</p>
</div>
<div id="hypothèses-statistiques-1" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Hypothèses statistiques<a href="leçon-6.html#hypoth%C3%A8ses-statistiques-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Les hypothèses statistiques de l’ANOVA à deux critères sont formulées de la même façon qu’avec l’ANOVA à un critère. Poursuivons l’exemple en testant les différences entre les moyennes des groupes définis par le facteur d’intérêt :</p>
<p>Traitement hormonal :<br />
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{\mathrm{horm}} = \mu_{\mathrm{sans.horm}}\)</span> (non-différence)<br />
<span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_{\mathrm{horm}} \neq \mu_{\mathrm{sans.horm}}\)</span></p>
<p>Sexe :<br />
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{\mathrm{m\hat{a}le}} = \mu_{\mathrm{femelle}}\)</span> (non-différence)<br />
<span class="math inline">\(H_a\)</span>: <span class="math inline">\(\mu_{\mathrm{m\hat{a}le}} \neq \mu_{\mathrm{femelle}}\)</span></p>
<p>Puisqu’il y a plusieurs observations par combinaison des deux facteurs (mâle avec traitement, mâle sans traitement, femelle avec traitement, femelle sans traitement), il est possible de tester l’interaction entre le traitement hormonal et le sexe. Le terme d’interaction teste si l’effet du traitement hormonal sur la variable réponse dépend du sexe.</p>
<p>Interaction traitement hormonal <span class="math inline">\(\times\)</span> sexe :<br />
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{\mathrm{m\hat{a}le -- horm}} = \mu_{\mathrm{m\hat{a}le -- sans.horm}} = \mu_{\mathrm{femelle -- horm}} = \mu_{\mathrm{femelle -- sans.horm}}\)</span> (non-différence)<br />
<span class="math inline">\(H_a\)</span>: au moins une moyenne diffère des autres</p>
<p>En mots, si la différence de moyenne entre traitement et sans traitement est égale entre mâle et femelle, il n’y a pas d’interactions et on ne rejette pas <span class="math inline">\(H_0\)</span>. À noter que cette dernière hypothèse ne peut pas être testée en présence d’une seule observation pour chaque combinaison des deux facteurs – il faut plus d’une observation (répétition) pour tester le terme d’interaction. Le seuil de signification (<span class="math inline">\(\alpha\)</span>) pour chacune de ces hypothèses est de 0.05.</p>
</div>
<div id="sommes-des-carrés-1" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Sommes des carrés<a href="leçon-6.html#sommes-des-carr%C3%A9s-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>On construit les sommes des carrés de l’ANOVA à deux critères de classification de façon similaire à l’ANOVA à un critère de classification. Ainsi, la somme des carrés totale (<span class="math inline">\(SST\)</span>) s’obtient avec :</p>
<p><span class="math display">\[SST = \sum_{i=1}^a \sum_{j=1}^b \sum_{k=1}^n (y_{ijk} - \bar{y})^2\]</span></p>
<p>où on compare l’observation <span class="math inline">\(k\)</span> du groupe <span class="math inline">\(i\)</span> du facteur <span class="math inline">\(A\)</span> et du groupe <span class="math inline">\(j\)</span> du facteur <span class="math inline">\(B\)</span> (<span class="math inline">\(y_{ijk}\)</span>) à la moyenne globale (<span class="math inline">\(\bar{y}\)</span>). Les degrés de liberté associés à la somme des carrés totale est obtenue à l’aide de <span class="math inline">\(df = N - 1\)</span>, où <span class="math inline">\(N\)</span> correspond au nombre total d’observations dans l’expérience.</p>
<p>On calcule la somme des carrés de chaque facteur de la même manière que pour une ANOVA à un critère. Nous obtenons ainsi :</p>
<p><span class="math display">\[ SSA = \sum_{i=1}^a \sum_{k=1}^n (\bar{y}_{i} - \bar{y})^2 = n \sum_{i=1}^a (\bar{y}_{i} - \bar{y})^2\]</span>
où on compare la moyenne de chaque groupe <span class="math inline">\(i\)</span> du facteur <span class="math inline">\(A\)</span> (<span class="math inline">\(\bar{y}_{i}\)</span>) à la moyenne globale (<span class="math inline">\(\bar{y}\)</span>) et où ce calcul se répète <span class="math inline">\(n\)</span> fois pour chaque moyenne d’un groupe <span class="math inline">\(i\)</span> donné. Les degrés de liberté correspondant à <span class="math inline">\(SSA\)</span> sont donnés par <span class="math inline">\(df = a - 1\)</span>, où <span class="math inline">\(a\)</span> est le nombre de groupes défini par le facteur A. Le calcul de la somme des carrés du deuxième facteur (<span class="math inline">\(B\)</span>) est identique à celui du facteur <span class="math inline">\(A\)</span> :</p>
<p><span class="math display">\[SSB = \sum_{j=1}^b \sum_{k=1}^n (\bar{y}_{j} - \bar{y})^2 = n \sum_{j=1}^b (\bar{y}_{j} - \bar{y})^2\]</span></p>
<p>Les degrés de liberté s’obtiennent avec <span class="math inline">\(df = b - 1\)</span>, où <span class="math inline">\(b\)</span> correspond au nombre de groupes du facteur <span class="math inline">\(B\)</span>.</p>
<p>La somme des carrés résiduelle (<span class="math inline">\(SSE\)</span>), aussi appelée somme des carrés des erreurs, se calcule de la même façon que pour l’ANOVA à un critère:</p>
<p><span class="math display">\[SSE = \sum_{i=1}^a \sum_{j=1}^b \sum_{k=1}^n (y_{ijk} - \bar{y}_{ij})^2\]</span></p>
<p>où on compare une observation <span class="math inline">\(k\)</span> appartenant à la fois à un groupe donné <span class="math inline">\(i\)</span> du facteur <span class="math inline">\(A\)</span> et d’un groupe <span class="math inline">\(j\)</span> du facteur <span class="math inline">\(B\)</span> à la moyenne de ces groupes combinés (<span class="math inline">\(\bar{y}_{ij}\)</span>). Les degrés de liberté associés à <span class="math inline">\(SSE\)</span> sont <span class="math inline">\(df = ab(n - 1)\)</span>, où <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span> sont le nombre de groupes du facteur <span class="math inline">\(A\)</span> et <span class="math inline">\(B\)</span>, respectivement, et <span class="math inline">\(n\)</span> est le nombre d’observations pour chaque combinaison des facteurs <span class="math inline">\(A\)</span> et <span class="math inline">\(B\)</span>.</p>
<p>L’ANOVA à deux critères qui contient plus d’une observation des combinaisons de groupes des deux facteurs permet de tester l’interaction entre les deux facteurs de l’expérience. La somme des carrés de l’interaction (<span class="math inline">\(SSInter\)</span>) s’obtient avec:</p>
<p><span class="math display">\[SSinter = \sum_{i=1}^a \sum_{j=1}^b \sum_{k=1}^n ( (\bar{y}_{ij} -\bar{y}) - (\bar{y}_i - \bar{y} )  - (\bar{y}_j - \bar{y}) )^2\]</span></p>
<p>où le premier terme, <span class="math inline">\((\bar{y}_{ij} -\bar{y})\)</span>, est la différence observée de la moyenne des groupes combinés <span class="math inline">\(i\)</span> et <span class="math inline">\(j\)</span> avec la moyenne globale, et les deux autres termes représentent la différence que devrait avoir cette moyenne des groupes combinés avec la moyenne globale s’il n’y avait pas d’interaction, c-à-d, la somme des différences entre la moyenne du groupe <span class="math inline">\(i\)</span> et la moyenne globale, <span class="math inline">\((\bar{y}_{i} -\bar{y})\)</span>, et entre la moyenne du groupe <span class="math inline">\(j\)</span> et la moyenne globale, <span class="math inline">\((\bar{y}_{j} -\bar{y})\)</span>. Nous pouvons simplifier l’équation pour <span class="math inline">\(SSinter\)</span>:</p>
<p><span class="math display">\[ SSinter = \sum_{i=1}^a \sum_{j=1}^b \sum_{k=1}^n (\bar{y}_{ij} - \bar{y}_i - \bar{y}_j + \bar{y})^2 = n \sum_{i=1}^a \sum_{j=1}^b  (\bar{y}_{ij} - \bar{y}_i - \bar{y}_j + \bar{y})^2\]</span></p>
<p>L’exemple qui suit illustre le calcul de ces différentes valeurs nécessaires à l’ANOVA à deux critères. Les degrés de liberté associés au terme <span class="math inline">\(SSInter\)</span> sont donnés par <span class="math inline">\(df = (a - 1)(b - 1)\)</span>, où <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span> correspondent aux nombre de groupes du facteur <span class="math inline">\(A\)</span> et <span class="math inline">\(B\)</span>, respectivement.</p>
<div class="exemple" section="7">
<p>On s’intéresse à l’effet d’un traitement hormonal sur la concentration de calcium dans le plasma sanguin chez des oiseaux mâles et femelles. La variable réponse est la concentration du calcium dans le plasma sanguin. Nos deux facteurs sont le traitement hormonal (avec traitement, sans traitement) et le sexe (mâle, femelle). Les données sont contenues dans le fichier <code>calcium.txt</code>.</p>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb619-1"><a href="leçon-6.html#cb619-1" tabindex="-1"></a><span class="do">## On importe le jeu de données</span></span>
<span id="cb619-2"><a href="leçon-6.html#cb619-2" tabindex="-1"></a>calcium <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Module_7/data/calcium.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb619-3"><a href="leçon-6.html#cb619-3" tabindex="-1"></a></span>
<span id="cb619-4"><a href="leçon-6.html#cb619-4" tabindex="-1"></a><span class="do">## On jette un coup d&#39;oeil aux premières observations</span></span>
<span id="cb619-5"><a href="leçon-6.html#cb619-5" tabindex="-1"></a><span class="fu">head</span>(calcium)</span></code></pre></div>
<pre><code>##   Concentration     Trait Sexe
## 1          16.5 sans_horm    f
## 2          18.4 sans_horm    f
## 3          12.7 sans_horm    f
## 4          14.0 sans_horm    f
## 5          12.8 sans_horm    f
## 6          14.5 sans_horm    m</code></pre>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb621-1"><a href="leçon-6.html#cb621-1" tabindex="-1"></a><span class="do">## On transforme en facteurs les colonnes </span></span>
<span id="cb621-2"><a href="leçon-6.html#cb621-2" tabindex="-1"></a><span class="do">## de caractères `Trait` et `Sexe`</span></span>
<span id="cb621-3"><a href="leçon-6.html#cb621-3" tabindex="-1"></a>calcium<span class="sc">$</span>Trait <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(calcium<span class="sc">$</span>Trait)</span>
<span id="cb621-4"><a href="leçon-6.html#cb621-4" tabindex="-1"></a>calcium<span class="sc">$</span>Sexe <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(calcium<span class="sc">$</span>Sexe)</span></code></pre></div>
<p>La Figure <a href="leçon-6.html#fig:boxplotcalcium">7.1</a> illustre les données selon les différentes combinaisons des deux facteurs.</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="leçon-6.html#cb622-1" tabindex="-1"></a><span class="do">## On crée un boxplot pour chaque</span></span>
<span id="cb622-2"><a href="leçon-6.html#cb622-2" tabindex="-1"></a><span class="do">## combinaison des deux facteurs</span></span>
<span id="cb622-3"><a href="leçon-6.html#cb622-3" tabindex="-1"></a><span class="fu">boxplot</span>(Concentration <span class="sc">~</span> Trait <span class="sc">+</span> Sexe, <span class="at">data =</span> calcium,</span>
<span id="cb622-4"><a href="leçon-6.html#cb622-4" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Concentration&quot;</span>, </span>
<span id="cb622-5"><a href="leçon-6.html#cb622-5" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Combinaison de traitement et sexe&quot;</span>,</span>
<span id="cb622-6"><a href="leçon-6.html#cb622-6" tabindex="-1"></a>        <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:boxplotcalcium"></span>
<img src="Cours_Stats_R_files/figure-html/boxplotcalcium-1.png" alt="Diagramme de boîtes et moustaches avec les données de concentration en calcium en fonction du traitement hormonal et du sexe." width="672" />
<p class="caption">
Figure 7.1: Diagramme de boîtes et moustaches avec les données de concentration en calcium en fonction du traitement hormonal et du sexe.
</p>
</div>
<p>On peut déterminer le nombre d’observations pour chaque combinaison des deux facteurs à l’aide de la fonction <code>table( )</code> :</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="leçon-6.html#cb623-1" tabindex="-1"></a><span class="do">## On détermine le nombre de répétitions par groupe</span></span>
<span id="cb623-2"><a href="leçon-6.html#cb623-2" tabindex="-1"></a><span class="fu">table</span>(calcium<span class="sc">$</span>Trait, calcium<span class="sc">$</span>Sexe)</span></code></pre></div>
<pre><code>##            
##             f m
##   horm      5 5
##   sans_horm 5 5</code></pre>
<p>On constate qu’il y a cinq observations pour chaque combinaison des niveaux des deux facteurs. Nous dirons donc qu’il y a cinq répétitions (<em>replicates</em>) par combinaison de traitements.</p>
<p>Calculons la somme des carrés totale :</p>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="leçon-6.html#cb625-1" tabindex="-1"></a><span class="do">##moyenne globale</span></span>
<span id="cb625-2"><a href="leçon-6.html#cb625-2" tabindex="-1"></a>y.bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(calcium<span class="sc">$</span>Concentration)</span>
<span id="cb625-3"><a href="leçon-6.html#cb625-3" tabindex="-1"></a><span class="do">##SST</span></span>
<span id="cb625-4"><a href="leçon-6.html#cb625-4" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((calcium<span class="sc">$</span>Concentration <span class="sc">-</span> y.bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb625-5"><a href="leçon-6.html#cb625-5" tabindex="-1"></a>SST</span></code></pre></div>
<pre><code>## [1] 1827.697</code></pre>
<div class="sourceCode" id="cb627"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb627-1"><a href="leçon-6.html#cb627-1" tabindex="-1"></a><span class="do">##df</span></span>
<span id="cb627-2"><a href="leçon-6.html#cb627-2" tabindex="-1"></a>df.SST <span class="ot">&lt;-</span> <span class="fu">length</span>(calcium<span class="sc">$</span>Concentration) <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div>
<p>On peut ensuite calculer la somme des carrés des facteurs <span class="math inline">\(A\)</span> et <span class="math inline">\(B\)</span> :</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="leçon-6.html#cb628-1" tabindex="-1"></a><span class="do">##sous-jeu de données</span></span>
<span id="cb628-2"><a href="leçon-6.html#cb628-2" tabindex="-1"></a>fem <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Sexe <span class="sc">==</span> <span class="st">&quot;f&quot;</span>, ]</span>
<span id="cb628-3"><a href="leçon-6.html#cb628-3" tabindex="-1"></a>mal <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Sexe <span class="sc">==</span> <span class="st">&quot;m&quot;</span>, ]</span>
<span id="cb628-4"><a href="leçon-6.html#cb628-4" tabindex="-1"></a>horm <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Trait <span class="sc">==</span> <span class="st">&quot;horm&quot;</span>, ]</span>
<span id="cb628-5"><a href="leçon-6.html#cb628-5" tabindex="-1"></a>nohorm <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Trait <span class="sc">==</span> <span class="st">&quot;sans_horm&quot;</span>, ]</span>
<span id="cb628-6"><a href="leçon-6.html#cb628-6" tabindex="-1"></a></span>
<span id="cb628-7"><a href="leçon-6.html#cb628-7" tabindex="-1"></a><span class="do">##moyenne des groupes</span></span>
<span id="cb628-8"><a href="leçon-6.html#cb628-8" tabindex="-1"></a>y.bar.f <span class="ot">&lt;-</span> <span class="fu">mean</span>(fem<span class="sc">$</span>Concentration)</span>
<span id="cb628-9"><a href="leçon-6.html#cb628-9" tabindex="-1"></a>y.bar.m <span class="ot">&lt;-</span> <span class="fu">mean</span>(mal<span class="sc">$</span>Concentration)</span>
<span id="cb628-10"><a href="leçon-6.html#cb628-10" tabindex="-1"></a>y.bar.horm <span class="ot">&lt;-</span> <span class="fu">mean</span>(horm<span class="sc">$</span>Concentration)</span>
<span id="cb628-11"><a href="leçon-6.html#cb628-11" tabindex="-1"></a>y.bar.nohorm <span class="ot">&lt;-</span> <span class="fu">mean</span>(nohorm<span class="sc">$</span>Concentration)</span>
<span id="cb628-12"><a href="leçon-6.html#cb628-12" tabindex="-1"></a><span class="do">## Calcul de SSA</span></span>
<span id="cb628-13"><a href="leçon-6.html#cb628-13" tabindex="-1"></a><span class="do">## où le nombre d&#39;observations femelle et mâle est</span></span>
<span id="cb628-14"><a href="leçon-6.html#cb628-14" tabindex="-1"></a><span class="fu">nrow</span>(fem)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="leçon-6.html#cb630-1" tabindex="-1"></a><span class="fu">nrow</span>(mal)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb632"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb632-1"><a href="leçon-6.html#cb632-1" tabindex="-1"></a>SSA <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">*</span>(y.bar.f <span class="sc">-</span> y.bar)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">*</span>(y.bar.m <span class="sc">-</span> y.bar)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb632-2"><a href="leçon-6.html#cb632-2" tabindex="-1"></a>SSA</span></code></pre></div>
<pre><code>## [1] 70.3125</code></pre>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="leçon-6.html#cb634-1" tabindex="-1"></a><span class="do">## Calculer df.SSA. On a df.SSA&lt;- a - 1 </span></span>
<span id="cb634-2"><a href="leçon-6.html#cb634-2" tabindex="-1"></a><span class="do">## où a est le nombre de groupes definis par le facteur A.</span></span>
<span id="cb634-3"><a href="leçon-6.html#cb634-3" tabindex="-1"></a><span class="do">## Ici, il y a homme et femme, donc a = 2.</span></span>
<span id="cb634-4"><a href="leçon-6.html#cb634-4" tabindex="-1"></a>df.SSA <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb634-5"><a href="leçon-6.html#cb634-5" tabindex="-1"></a>df.SSA</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="leçon-6.html#cb636-1" tabindex="-1"></a><span class="do">##SSB</span></span>
<span id="cb636-2"><a href="leçon-6.html#cb636-2" tabindex="-1"></a><span class="do">## où le nombre d&#39;observations horm et nohorm est</span></span>
<span id="cb636-3"><a href="leçon-6.html#cb636-3" tabindex="-1"></a><span class="fu">nrow</span>(horm)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb638"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb638-1"><a href="leçon-6.html#cb638-1" tabindex="-1"></a><span class="fu">nrow</span>(nohorm)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb640"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb640-1"><a href="leçon-6.html#cb640-1" tabindex="-1"></a>SSB <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">*</span>(y.bar.horm <span class="sc">-</span> y.bar)<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">*</span>(y.bar.nohorm <span class="sc">-</span> y.bar)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb640-2"><a href="leçon-6.html#cb640-2" tabindex="-1"></a>SSB</span></code></pre></div>
<pre><code>## [1] 1386.112</code></pre>
<div class="sourceCode" id="cb642"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb642-1"><a href="leçon-6.html#cb642-1" tabindex="-1"></a><span class="do">## Calculer df.SSB. On a df.SSB&lt;- b - 1 </span></span>
<span id="cb642-2"><a href="leçon-6.html#cb642-2" tabindex="-1"></a><span class="do">## où b est le nombre de groupes définis par le facteur B. </span></span>
<span id="cb642-3"><a href="leçon-6.html#cb642-3" tabindex="-1"></a><span class="do">## Ici, il y a traitement hormonal et pas</span></span>
<span id="cb642-4"><a href="leçon-6.html#cb642-4" tabindex="-1"></a><span class="do">## de traitement, donc b = 2</span></span>
<span id="cb642-5"><a href="leçon-6.html#cb642-5" tabindex="-1"></a>df.SSB <span class="ot">&lt;-</span>  <span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb642-6"><a href="leçon-6.html#cb642-6" tabindex="-1"></a>df.SSB</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>La somme des carrés des erreurs se calcule comme suit :</p>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="leçon-6.html#cb644-1" tabindex="-1"></a><span class="do">##sous-groupes en combinant les deux facteurs</span></span>
<span id="cb644-2"><a href="leçon-6.html#cb644-2" tabindex="-1"></a>f.horm <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Sexe <span class="sc">==</span> <span class="st">&quot;f&quot;</span> <span class="sc">&amp;</span> calcium<span class="sc">$</span>Trait <span class="sc">==</span> <span class="st">&quot;horm&quot;</span>, ]</span>
<span id="cb644-3"><a href="leçon-6.html#cb644-3" tabindex="-1"></a>m.horm <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Sexe <span class="sc">==</span> <span class="st">&quot;m&quot;</span> <span class="sc">&amp;</span> calcium<span class="sc">$</span>Trait <span class="sc">==</span> <span class="st">&quot;horm&quot;</span>, ] </span>
<span id="cb644-4"><a href="leçon-6.html#cb644-4" tabindex="-1"></a>f.nohorm <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Sexe <span class="sc">==</span> <span class="st">&quot;f&quot;</span> <span class="sc">&amp;</span> calcium<span class="sc">$</span>Trait <span class="sc">==</span> <span class="st">&quot;sans_horm&quot;</span>, ]</span>
<span id="cb644-5"><a href="leçon-6.html#cb644-5" tabindex="-1"></a>m.nohorm <span class="ot">&lt;-</span> calcium[calcium<span class="sc">$</span>Sexe <span class="sc">==</span> <span class="st">&quot;m&quot;</span> <span class="sc">&amp;</span> calcium<span class="sc">$</span>Trait <span class="sc">==</span> <span class="st">&quot;sans_horm&quot;</span>, ]</span>
<span id="cb644-6"><a href="leçon-6.html#cb644-6" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb644-7"><a href="leçon-6.html#cb644-7" tabindex="-1"></a><span class="do">##calculs des moyennes des combinaisons de groupes</span></span>
<span id="cb644-8"><a href="leçon-6.html#cb644-8" tabindex="-1"></a>y.bar.f.horm <span class="ot">&lt;-</span> <span class="fu">mean</span>(f.horm<span class="sc">$</span>Concentration)</span>
<span id="cb644-9"><a href="leçon-6.html#cb644-9" tabindex="-1"></a>y.bar.m.horm <span class="ot">&lt;-</span> <span class="fu">mean</span>(m.horm<span class="sc">$</span>Concentration)</span>
<span id="cb644-10"><a href="leçon-6.html#cb644-10" tabindex="-1"></a>y.bar.f.nohorm <span class="ot">&lt;-</span> <span class="fu">mean</span>(f.nohorm<span class="sc">$</span>Concentration)</span>
<span id="cb644-11"><a href="leçon-6.html#cb644-11" tabindex="-1"></a>y.bar.m.nohorm <span class="ot">&lt;-</span> <span class="fu">mean</span>(m.nohorm<span class="sc">$</span>Concentration)</span>
<span id="cb644-12"><a href="leçon-6.html#cb644-12" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb644-13"><a href="leçon-6.html#cb644-13" tabindex="-1"></a><span class="do">## Calcul de SSE</span></span>
<span id="cb644-14"><a href="leçon-6.html#cb644-14" tabindex="-1"></a>SSE.f.horm <span class="ot">&lt;-</span> <span class="fu">sum</span>((f.horm<span class="sc">$</span>Concentration <span class="sc">-</span> y.bar.f.horm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb644-15"><a href="leçon-6.html#cb644-15" tabindex="-1"></a>SSE.m.horm <span class="ot">&lt;-</span> <span class="fu">sum</span>((m.horm<span class="sc">$</span>Concentration <span class="sc">-</span> y.bar.m.horm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb644-16"><a href="leçon-6.html#cb644-16" tabindex="-1"></a>SSE.f.nohorm <span class="ot">&lt;-</span> <span class="fu">sum</span>((f.nohorm<span class="sc">$</span>Concentration <span class="sc">-</span> y.bar.f.nohorm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb644-17"><a href="leçon-6.html#cb644-17" tabindex="-1"></a>SSE.m.nohorm <span class="ot">&lt;-</span> <span class="fu">sum</span>((m.nohorm<span class="sc">$</span>Concentration <span class="sc">-</span> y.bar.m.nohorm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb644-18"><a href="leçon-6.html#cb644-18" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SSE.f.horm <span class="sc">+</span> SSE.m.horm <span class="sc">+</span> SSE.f.nohorm <span class="sc">+</span> SSE.m.nohorm</span>
<span id="cb644-19"><a href="leçon-6.html#cb644-19" tabindex="-1"></a>SSE</span></code></pre></div>
<pre><code>## [1] 366.372</code></pre>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="leçon-6.html#cb646-1" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb646-2"><a href="leçon-6.html#cb646-2" tabindex="-1"></a><span class="do">## Cacul des degrés de liberté</span></span>
<span id="cb646-3"><a href="leçon-6.html#cb646-3" tabindex="-1"></a><span class="do">## df.SSE = ab(n-1), où a et b sont le nombre de groupes </span></span>
<span id="cb646-4"><a href="leçon-6.html#cb646-4" tabindex="-1"></a><span class="do">## du facteur A et B, respectivement,</span></span>
<span id="cb646-5"><a href="leçon-6.html#cb646-5" tabindex="-1"></a><span class="do">## et n est le nombre d&#39;observations pour chaque combinaison </span></span>
<span id="cb646-6"><a href="leçon-6.html#cb646-6" tabindex="-1"></a><span class="do">## des facteurs A et B.</span></span>
<span id="cb646-7"><a href="leçon-6.html#cb646-7" tabindex="-1"></a>df.SSE <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">levels</span>(calcium<span class="sc">$</span>Sexe)) <span class="sc">*</span> </span>
<span id="cb646-8"><a href="leçon-6.html#cb646-8" tabindex="-1"></a>          <span class="fu">length</span>(<span class="fu">levels</span>(calcium<span class="sc">$</span>Trait)) <span class="sc">*</span> (<span class="dv">5</span> <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb646-9"><a href="leçon-6.html#cb646-9" tabindex="-1"></a>df.SSE</span></code></pre></div>
<pre><code>## [1] 16</code></pre>
<p>Finalement, on obtient la somme des carrés du terme d’interaction entre les deux facteurs. Notez que l’équation pour <span class="math inline">\(SSinter\)</span> peut se décomposer de la façon suivante :</p>
<p><span class="math display">\[\begin{align*}
SS_{\text{inter}} &amp;= n \sum_{i=1}^a \sum_{j=1}^b  (\bar{y}_{ij} - \bar{y}_i - \bar{y}_j + \bar{y})^2 \\
&amp;= n \sum_{i=1}^a \left( (\bar{y}_{i.\text{horm}} - \bar{y}_i - \bar{y}_{\text{horm}} + \bar{y})^2 + (\bar{y}_{i.\text{nohorm}} - \bar{y}_i - \bar{y}_{\text{nohorm}} + \bar{y})^2 \right) \\
&amp;= n \left( (\bar{y}_{f.\text{horm}} - \bar{y}_f - \bar{y}_{\text{horm}} + \bar{y})^2 \right. \\
&amp;\quad + (\bar{y}_{f.\text{nohorm}} - \bar{y}_f - \bar{y}_{\text{nohorm}} + \bar{y})^2 \\
&amp;\quad + (\bar{y}_{m.\text{horm}} - \bar{y}_m - \bar{y}_{\text{horm}} + \bar{y})^2 \\
&amp;\quad \left. + (\bar{y}_{m.\text{nohorm}} - \bar{y}_m - \bar{y}_{\text{nohorm}} + \bar{y})^2 \right)
\end{align*}\]</span></p>
<p>Ansi, nous calculons <span class="math inline">\(SSinter\)</span> de la façon suivante :</p>
<div class="sourceCode" id="cb648"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb648-1"><a href="leçon-6.html#cb648-1" tabindex="-1"></a><span class="do">## SS de l&#39;interaction</span></span>
<span id="cb648-2"><a href="leçon-6.html#cb648-2" tabindex="-1"></a>SSInter.f.horm <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">*</span><span class="fu">sum</span>((y.bar.f.horm <span class="sc">-</span> y.bar.f <span class="sc">-</span> y.bar.horm <span class="sc">+</span> y.bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb648-3"><a href="leçon-6.html#cb648-3" tabindex="-1"></a>SSInter.m.horm <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">*</span><span class="fu">sum</span>((y.bar.m.horm <span class="sc">-</span> y.bar.m <span class="sc">-</span> y.bar.horm <span class="sc">+</span> y.bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb648-4"><a href="leçon-6.html#cb648-4" tabindex="-1"></a>SSInter.f.nohorm <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">*</span><span class="fu">sum</span>((y.bar.f.nohorm <span class="sc">-</span> y.bar.f <span class="sc">-</span> </span>
<span id="cb648-5"><a href="leçon-6.html#cb648-5" tabindex="-1"></a>                             y.bar.nohorm <span class="sc">+</span> y.bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb648-6"><a href="leçon-6.html#cb648-6" tabindex="-1"></a>SSInter.m.nohorm <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">*</span><span class="fu">sum</span>((y.bar.m.nohorm <span class="sc">-</span> y.bar.m <span class="sc">-</span> </span>
<span id="cb648-7"><a href="leçon-6.html#cb648-7" tabindex="-1"></a>                             y.bar.nohorm <span class="sc">+</span> y.bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb648-8"><a href="leçon-6.html#cb648-8" tabindex="-1"></a>SSInter <span class="ot">&lt;-</span> SSInter.f.horm <span class="sc">+</span> SSInter.m.horm <span class="sc">+</span> </span>
<span id="cb648-9"><a href="leçon-6.html#cb648-9" tabindex="-1"></a>           SSInter.f.nohorm <span class="sc">+</span> SSInter.m.nohorm</span>
<span id="cb648-10"><a href="leçon-6.html#cb648-10" tabindex="-1"></a></span>
<span id="cb648-11"><a href="leçon-6.html#cb648-11" tabindex="-1"></a>SSInter</span></code></pre></div>
<pre><code>## [1] 4.9005</code></pre>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="leçon-6.html#cb650-1" tabindex="-1"></a><span class="do">## degrés de liberté de SSInter</span></span>
<span id="cb650-2"><a href="leçon-6.html#cb650-2" tabindex="-1"></a><span class="do">## df.SSInter = (a-1)(b-1), où a et b correspondent aux  </span></span>
<span id="cb650-3"><a href="leçon-6.html#cb650-3" tabindex="-1"></a><span class="do">## nombre de groupes du facteur A et B, respectivement.</span></span>
<span id="cb650-4"><a href="leçon-6.html#cb650-4" tabindex="-1"></a></span>
<span id="cb650-5"><a href="leçon-6.html#cb650-5" tabindex="-1"></a>df.SSInter <span class="ot">&lt;-</span> df.SSA <span class="sc">*</span> df.SSB</span>
<span id="cb650-6"><a href="leçon-6.html#cb650-6" tabindex="-1"></a>df.SSInter</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>On peut réaliser tous ces calculs directement dans R à l’aide de la fonction <code>aov( )</code> :</p>
<div class="sourceCode" id="cb652"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb652-1"><a href="leçon-6.html#cb652-1" tabindex="-1"></a>aov2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Concentration <span class="sc">~</span> Sexe <span class="sc">+</span> Trait <span class="sc">+</span> Sexe<span class="sc">:</span>Trait, <span class="at">data =</span> calcium)</span>
<span id="cb652-2"><a href="leçon-6.html#cb652-2" tabindex="-1"></a><span class="fu">summary</span>(aov2)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Sexe         1   70.3    70.3   3.071   0.0989 .  
## Trait        1 1386.1  1386.1  60.534 7.94e-07 ***
## Sexe:Trait   1    4.9     4.9   0.214   0.6499    
## Residuals   16  366.4    22.9                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>On peut reconstituer ce même tableau à partir des calculs que nous avons effectués plus haut :</p>
<div class="sourceCode" id="cb654"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb654-1"><a href="leçon-6.html#cb654-1" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Df =</span> <span class="fu">c</span>(df.SSA, df.SSB, df.SSInter, df.SSE),</span>
<span id="cb654-2"><a href="leçon-6.html#cb654-2" tabindex="-1"></a>                     <span class="at">Sum.Sq =</span> <span class="fu">c</span>(SSA, SSB, SSInter, SSE))</span>
<span id="cb654-3"><a href="leçon-6.html#cb654-3" tabindex="-1"></a>result<span class="sc">$</span>Mean.Sq <span class="ot">&lt;-</span> result<span class="sc">$</span>Sum.Sq<span class="sc">/</span>result<span class="sc">$</span>Df</span>
<span id="cb654-4"><a href="leçon-6.html#cb654-4" tabindex="-1"></a>result<span class="sc">$</span>F.value <span class="ot">&lt;-</span> <span class="fu">c</span>(result<span class="sc">$</span>Mean.Sq[<span class="dv">1</span>]<span class="sc">/</span>result<span class="sc">$</span>Mean.Sq[<span class="dv">4</span>],</span>
<span id="cb654-5"><a href="leçon-6.html#cb654-5" tabindex="-1"></a>                    result<span class="sc">$</span>Mean.Sq[<span class="dv">2</span>]<span class="sc">/</span>result<span class="sc">$</span>Mean.Sq[<span class="dv">4</span>],</span>
<span id="cb654-6"><a href="leçon-6.html#cb654-6" tabindex="-1"></a>                    result<span class="sc">$</span>Mean.Sq[<span class="dv">3</span>]<span class="sc">/</span>result<span class="sc">$</span>Mean.Sq[<span class="dv">4</span>],</span>
<span id="cb654-7"><a href="leçon-6.html#cb654-7" tabindex="-1"></a>                    <span class="cn">NA</span>)</span>
<span id="cb654-8"><a href="leçon-6.html#cb654-8" tabindex="-1"></a>result<span class="sc">$</span>P.value <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(result<span class="sc">$</span>F.value[<span class="dv">1</span>], </span>
<span id="cb654-9"><a href="leçon-6.html#cb654-9" tabindex="-1"></a>                    <span class="at">df1 =</span> result<span class="sc">$</span>Df[<span class="dv">1</span>], </span>
<span id="cb654-10"><a href="leçon-6.html#cb654-10" tabindex="-1"></a>                    <span class="at">df2 =</span> result<span class="sc">$</span>Df[<span class="dv">4</span>]),</span>
<span id="cb654-11"><a href="leçon-6.html#cb654-11" tabindex="-1"></a>                    <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(result<span class="sc">$</span>F.value[<span class="dv">2</span>], </span>
<span id="cb654-12"><a href="leçon-6.html#cb654-12" tabindex="-1"></a>                    <span class="at">df1 =</span> result<span class="sc">$</span>Df[<span class="dv">2</span>], </span>
<span id="cb654-13"><a href="leçon-6.html#cb654-13" tabindex="-1"></a>                    <span class="at">df2 =</span> result<span class="sc">$</span>Df[<span class="dv">4</span>]),</span>
<span id="cb654-14"><a href="leçon-6.html#cb654-14" tabindex="-1"></a>                    <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(result<span class="sc">$</span>F.value[<span class="dv">3</span>], </span>
<span id="cb654-15"><a href="leçon-6.html#cb654-15" tabindex="-1"></a>                    <span class="at">df1 =</span> result<span class="sc">$</span>Df[<span class="dv">3</span>],  </span>
<span id="cb654-16"><a href="leçon-6.html#cb654-16" tabindex="-1"></a>                    <span class="at">df2 =</span> result<span class="sc">$</span>Df[<span class="dv">4</span>]), </span>
<span id="cb654-17"><a href="leçon-6.html#cb654-17" tabindex="-1"></a>                    <span class="cn">NA</span>)  </span>
<span id="cb654-18"><a href="leçon-6.html#cb654-18" tabindex="-1"></a></span>
<span id="cb654-19"><a href="leçon-6.html#cb654-19" tabindex="-1"></a><span class="do">##tableau identique à aov( )</span></span>
<span id="cb654-20"><a href="leçon-6.html#cb654-20" tabindex="-1"></a>result</span></code></pre></div>
<pre><code>##   Df    Sum.Sq    Mean.Sq   F.value      P.value
## 1  1   70.3125   70.31250  3.070650 9.885618e-02
## 2  1 1386.1125 1386.11250 60.533556 7.943078e-07
## 3  1    4.9005    4.90050  0.214012 6.498700e-01
## 4 16  366.3720   22.89825        NA           NA</code></pre>
<p>Avant d’interpréter les résultats, on doit vérifier les suppositions du modèle. On vérifie les suppositions de l’ANOVA à deux critères avec les mêmes outils que pour l’ANOVA à un critère. On constate que les résidus suivent une distribution normale (Figure <a href="leçon-6.html#fig:normcalcium">7.2</a>a):</p>
<div class="sourceCode" id="cb656"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb656-1"><a href="leçon-6.html#cb656-1" tabindex="-1"></a><span class="do">##vérification de la normalité des résidus</span></span>
<span id="cb656-2"><a href="leçon-6.html#cb656-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb656-3"><a href="leçon-6.html#cb656-3" tabindex="-1"></a></span>
<span id="cb656-4"><a href="leçon-6.html#cb656-4" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(aov2),</span>
<span id="cb656-5"><a href="leçon-6.html#cb656-5" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Normalité des résidus&quot;</span>,</span>
<span id="cb656-6"><a href="leçon-6.html#cb656-6" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Quantiles observés&quot;</span>, </span>
<span id="cb656-7"><a href="leçon-6.html#cb656-7" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;Quantiles théoriques&quot;</span>, </span>
<span id="cb656-8"><a href="leçon-6.html#cb656-8" tabindex="-1"></a>       <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb656-9"><a href="leçon-6.html#cb656-9" tabindex="-1"></a></span>
<span id="cb656-10"><a href="leçon-6.html#cb656-10" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(aov2))</span>
<span id="cb656-11"><a href="leçon-6.html#cb656-11" tabindex="-1"></a></span>
<span id="cb656-12"><a href="leçon-6.html#cb656-12" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="sc">-</span><span class="fl">1.9</span>, <span class="at">y =</span> <span class="fl">7.5</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb656-13"><a href="leçon-6.html#cb656-13" tabindex="-1"></a></span>
<span id="cb656-14"><a href="leçon-6.html#cb656-14" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(aov2) <span class="sc">~</span> <span class="fu">fitted</span>(aov2), </span>
<span id="cb656-15"><a href="leçon-6.html#cb656-15" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>,</span>
<span id="cb656-16"><a href="leçon-6.html#cb656-16" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Résidus&quot;</span>, </span>
<span id="cb656-17"><a href="leçon-6.html#cb656-17" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb656-18"><a href="leçon-6.html#cb656-18" tabindex="-1"></a></span>
<span id="cb656-19"><a href="leçon-6.html#cb656-19" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">12.5</span>, <span class="at">y =</span> <span class="fl">7.5</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:normcalcium"></span>
<img src="Cours_Stats_R_files/figure-html/normcalcium-1.png" alt="Graphique quantile-quantile évaluant la normalité des résidus (a) et le graphique des résidus en fonction des valeurs prédites pour diagnostiquer l'hétérogénéité de la variance (b) à partir de l'ANOVA à deux critères sur les données de concentration en calcium dans le plasma sanguin." width="672" />
<p class="caption">
Figure 7.2: Graphique quantile-quantile évaluant la normalité des résidus (a) et le graphique des résidus en fonction des valeurs prédites pour diagnostiquer l’hétérogénéité de la variance (b) à partir de l’ANOVA à deux critères sur les données de concentration en calcium dans le plasma sanguin.
</p>
</div>
<p>Le graphique des résidus en fonction des valeurs prédites présente des signes d’hétérogénéité de la variance (Figure <a href="leçon-6.html#fig:normcalcium">7.2</a>b). En effet, le patron en forme d’entonnoir montre que la variance augmente avec les valeurs prédites. Par conséquent, on ne peut pas interpréter le tableau de l’ANOVA obtenu plus haut. Afin de corriger l’hétérogénéité de la variance, la transformation logarithmique s’avère souvent efficace. Essayons-la sur la concentration en calcium.</p>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="leçon-6.html#cb657-1" tabindex="-1"></a><span class="do">## Transformation log</span></span>
<span id="cb657-2"><a href="leçon-6.html#cb657-2" tabindex="-1"></a>calcium<span class="sc">$</span>log.concentration <span class="ot">&lt;-</span> <span class="fu">log</span>(calcium<span class="sc">$</span>Concentration)</span>
<span id="cb657-3"><a href="leçon-6.html#cb657-3" tabindex="-1"></a>aov.log <span class="ot">&lt;-</span> <span class="fu">aov</span>(log.concentration <span class="sc">~</span> Trait <span class="sc">+</span> Sexe <span class="sc">+</span> Trait<span class="sc">:</span>Sexe,</span>
<span id="cb657-4"><a href="leçon-6.html#cb657-4" tabindex="-1"></a>               <span class="at">data =</span> calcium)</span></code></pre></div>
<p>Produisons le nouveau graphique pour évaluer la normalité des résidus et l’hétérogénéité de la variace.</p>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb658-1"><a href="leçon-6.html#cb658-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb658-2"><a href="leçon-6.html#cb658-2" tabindex="-1"></a></span>
<span id="cb658-3"><a href="leçon-6.html#cb658-3" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(aov.log), </span>
<span id="cb658-4"><a href="leçon-6.html#cb658-4" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Quantiles observés&quot;</span>,</span>
<span id="cb658-5"><a href="leçon-6.html#cb658-5" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;Quantiles prédits&quot;</span>,</span>
<span id="cb658-6"><a href="leçon-6.html#cb658-6" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot; &quot;</span>, <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb658-7"><a href="leçon-6.html#cb658-7" tabindex="-1"></a></span>
<span id="cb658-8"><a href="leçon-6.html#cb658-8" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(aov.log))</span>
<span id="cb658-9"><a href="leçon-6.html#cb658-9" tabindex="-1"></a></span>
<span id="cb658-10"><a href="leçon-6.html#cb658-10" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">1.5</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.35</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb658-11"><a href="leçon-6.html#cb658-11" tabindex="-1"></a></span>
<span id="cb658-12"><a href="leçon-6.html#cb658-12" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(aov.log) <span class="sc">~</span> <span class="fu">fitted</span>(aov.log),</span>
<span id="cb658-13"><a href="leçon-6.html#cb658-13" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Résidus&quot;</span>, </span>
<span id="cb658-14"><a href="leçon-6.html#cb658-14" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>,</span>
<span id="cb658-15"><a href="leçon-6.html#cb658-15" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb658-16"><a href="leçon-6.html#cb658-16" tabindex="-1"></a></span>
<span id="cb658-17"><a href="leçon-6.html#cb658-17" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">3.3</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.35</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:logcheck"></span>
<img src="Cours_Stats_R_files/figure-html/logcheck-1.png" alt="Graphique quantile-quantile (a) et résidus en fonction des valeurs prédites (b) de l'ANOVA à deux critères réalisée à partir des données de concentration de calcium log-transformées." width="672" />
<p class="caption">
Figure 7.3: Graphique quantile-quantile (a) et résidus en fonction des valeurs prédites (b) de l’ANOVA à deux critères réalisée à partir des données de concentration de calcium log-transformées.
</p>
</div>
<p>Les suppositions de normalité et d’homogénéité de la variance sont maintenant respectées (Figure <a href="leçon-6.html#fig:logcheck">7.3</a>).</p>
<p>Le tableau d’ANOVA réalisé à partir du logarithme de la concentration en calcium donne :</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="leçon-6.html#cb659-1" tabindex="-1"></a><span class="do">## Résultats</span></span>
<span id="cb659-2"><a href="leçon-6.html#cb659-2" tabindex="-1"></a><span class="fu">summary</span>(aov.log)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Trait        1  3.196   3.196  86.121 7.69e-08 ***
## Sexe         1  0.145   0.145   3.901   0.0658 .  
## Trait:Sexe   1  0.007   0.007   0.176   0.6805    
## Residuals   16  0.594   0.037                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Lorsqu’on effectue une analyse de variance à deux critères avec répétitions, on doit toujours vérifier en premier la signification du terme d’interaction. Ici, on remarque qu’il n’y a pas d’interaction entre les deux facteurs (). Par ailleurs, on remarque un effet marginal du sexe ()<a href="#fn21" class="footnote-ref" id="fnref21"><sup>21</sup></a> et un effet important du traitement hormonal sur le log de la concentration en calcium (<span class="math inline">\(F_{1, 16} = 86.12, P &lt; 0.0001\)</span>). L’effet de chaque facteur est indépendant de l’effet de l’autre, puisque l’ANOVA n’a pu démontrer que le terme d’interaction était statistiquement significatif.</p>
<p>Tout comme l’ANOVA à un critère, on peut poursuivre l’ANOVA à deux critères avec des comparaisons multiples afin de déterminer où se trouvent les différences lorsque nous avons rejeté <span class="math inline">\(H_0\)</span><a href="#fn22" class="footnote-ref" id="fnref22"><sup>22</sup></a>.</p>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="leçon-6.html#cb661-1" tabindex="-1"></a><span class="do">##comparaisons multiples - Sexe</span></span>
<span id="cb661-2"><a href="leçon-6.html#cb661-2" tabindex="-1"></a>sexe.mult <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(aov.log, <span class="at">which =</span> <span class="st">&quot;Sexe&quot;</span>)</span>
<span id="cb661-3"><a href="leçon-6.html#cb661-3" tabindex="-1"></a>sexe.mult<span class="sc">$</span>Sexe</span></code></pre></div>
<pre><code>##           diff        lwr        upr      p adj
## m-f -0.1701524 -0.3527725 0.01246759 0.06576033</code></pre>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="leçon-6.html#cb663-1" tabindex="-1"></a><span class="do">##comparaisons multiples - Trait</span></span>
<span id="cb663-2"><a href="leçon-6.html#cb663-2" tabindex="-1"></a>trait.mult <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(aov.log, <span class="at">which =</span> <span class="st">&quot;Trait&quot;</span>)</span>
<span id="cb663-3"><a href="leçon-6.html#cb663-3" tabindex="-1"></a>trait.mult<span class="sc">$</span>Trait</span></code></pre></div>
<pre><code>##                      diff        lwr        upr        p adj
## sans_horm-horm -0.7994414 -0.9820614 -0.6168213 7.686578e-08</code></pre>
<p>Les comparaisons multiples basées sur le test de Tukey indiquent la même conclusion que le tableau d’ANOVA, puisque chaque facteur ne comporte ici que deux niveaux. Le log de la concentration en calcium du plasma sanguin des femelles est marginalement supérieur à celui des mâles (<span class="math inline">\(\bar{x}_{\mathrm{m\hat{a}les}} - \bar{x}_{\mathrm{femelles}} = -0.17, P = 0.0658\)</span>). En ce qui concerne le facteur du traitement hormonal, on constate que le groupe avec traitement hormonal est supérieur à celui du groupe sans traitement hormonal (<span class="math inline">\(\bar{x}_{\mathrm{sans\_horm}} - \bar{x}_{\mathrm{horm}} = -0.799, P &lt; 0.0001\)</span>).</p>
<p>On peut aussi illustrer les résultats à l’aide d’un graphique en représentant les moyennes de chaque groupe <span class="math inline">\(\pm\)</span> un intervalle de confiance à 95 %. Tout d’abord produisons un graphique sur une échelle logarithmique.</p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="leçon-6.html#cb665-1" tabindex="-1"></a><span class="do">## Sexe - moyenne des groupes</span></span>
<span id="cb665-2"><a href="leçon-6.html#cb665-2" tabindex="-1"></a><span class="do">## valeurs pour lesquelles faire des prédictions</span></span>
<span id="cb665-3"><a href="leçon-6.html#cb665-3" tabindex="-1"></a><span class="do">## On commence par créer un tableau dans lequel </span></span>
<span id="cb665-4"><a href="leçon-6.html#cb665-4" tabindex="-1"></a><span class="do">## chaque ligne correspond à une combinaison des facteurs A et B.</span></span>
<span id="cb665-5"><a href="leçon-6.html#cb665-5" tabindex="-1"></a>pred.set <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Sexe =</span> <span class="fu">c</span>(<span class="st">&quot;m&quot;</span>, <span class="st">&quot;f&quot;</span>), </span>
<span id="cb665-6"><a href="leçon-6.html#cb665-6" tabindex="-1"></a>                        <span class="at">Trait =</span> <span class="fu">c</span>(<span class="st">&quot;sans_horm&quot;</span>, <span class="st">&quot;horm&quot;</span>))</span>
<span id="cb665-7"><a href="leçon-6.html#cb665-7" tabindex="-1"></a></span>
<span id="cb665-8"><a href="leçon-6.html#cb665-8" tabindex="-1"></a><span class="do">## La fonction predict nous donne les valeurs prédites par l’ANOVA</span></span>
<span id="cb665-9"><a href="leçon-6.html#cb665-9" tabindex="-1"></a>sex.means <span class="ot">&lt;-</span> <span class="fu">predict</span>(aov.log, <span class="at">newdata =</span> pred.set, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb665-10"><a href="leçon-6.html#cb665-10" tabindex="-1"></a></span>
<span id="cb665-11"><a href="leçon-6.html#cb665-11" tabindex="-1"></a><span class="do">## Ajout des prédictions dans le jeu de données</span></span>
<span id="cb665-12"><a href="leçon-6.html#cb665-12" tabindex="-1"></a>pred.set<span class="sc">$</span>fit <span class="ot">&lt;-</span> sex.means<span class="sc">$</span>fit</span>
<span id="cb665-13"><a href="leçon-6.html#cb665-13" tabindex="-1"></a>pred.set<span class="sc">$</span>se.fit <span class="ot">&lt;-</span> sex.means<span class="sc">$</span>se.fit</span>
<span id="cb665-14"><a href="leçon-6.html#cb665-14" tabindex="-1"></a></span>
<span id="cb665-15"><a href="leçon-6.html#cb665-15" tabindex="-1"></a><span class="do">##IC à 95%</span></span>
<span id="cb665-16"><a href="leçon-6.html#cb665-16" tabindex="-1"></a><span class="do">## On détermine l’intervalle de confiance pour </span></span>
<span id="cb665-17"><a href="leçon-6.html#cb665-17" tabindex="-1"></a><span class="do">## construire nos barres d’erreur</span></span>
<span id="cb665-18"><a href="leçon-6.html#cb665-18" tabindex="-1"></a><span class="do">## Rappelons que l’intervalle de confiance est donné par : </span></span>
<span id="cb665-19"><a href="leçon-6.html#cb665-19" tabindex="-1"></a><span class="do">## (IC.inf, IC.sup) (voir leçon 2)</span></span>
<span id="cb665-20"><a href="leçon-6.html#cb665-20" tabindex="-1"></a><span class="do">## IC.inf = x.bar + qt(p=0.025, df)*SE</span></span>
<span id="cb665-21"><a href="leçon-6.html#cb665-21" tabindex="-1"></a><span class="do">## IC.sup = x.bar - qt(p=0.025, df)*SE</span></span>
<span id="cb665-22"><a href="leçon-6.html#cb665-22" tabindex="-1"></a></span>
<span id="cb665-23"><a href="leçon-6.html#cb665-23" tabindex="-1"></a>pred.set<span class="sc">$</span>low95 <span class="ot">&lt;-</span> pred.set<span class="sc">$</span>fit <span class="sc">+</span> </span>
<span id="cb665-24"><a href="leçon-6.html#cb665-24" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> aov.log<span class="sc">$</span>df.residual) <span class="sc">*</span> pred.set<span class="sc">$</span>se.fit</span>
<span id="cb665-25"><a href="leçon-6.html#cb665-25" tabindex="-1"></a></span>
<span id="cb665-26"><a href="leçon-6.html#cb665-26" tabindex="-1"></a>pred.set<span class="sc">$</span>upp95 <span class="ot">&lt;-</span> pred.set<span class="sc">$</span>fit <span class="sc">-</span> </span>
<span id="cb665-27"><a href="leçon-6.html#cb665-27" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> aov.log<span class="sc">$</span>df.residual) <span class="sc">*</span> pred.set<span class="sc">$</span>se.fit</span>
<span id="cb665-28"><a href="leçon-6.html#cb665-28" tabindex="-1"></a>pred.set</span>
<span id="cb665-29"><a href="leçon-6.html#cb665-29" tabindex="-1"></a></span>
<span id="cb665-30"><a href="leçon-6.html#cb665-30" tabindex="-1"></a><span class="do">##créer le graphique</span></span>
<span id="cb665-31"><a href="leçon-6.html#cb665-31" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> <span class="dv">0</span>, <span class="at">x =</span> <span class="dv">0</span>, </span>
<span id="cb665-32"><a href="leçon-6.html#cb665-32" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Log de la concentration en calcium&quot;</span>,</span>
<span id="cb665-33"><a href="leçon-6.html#cb665-33" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Traitement&quot;</span>, </span>
<span id="cb665-34"><a href="leçon-6.html#cb665-34" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(pred.set<span class="sc">$</span>low95), <span class="fu">max</span>(pred.set<span class="sc">$</span>upp95)), </span>
<span id="cb665-35"><a href="leçon-6.html#cb665-35" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="dv">2</span>,</span>
<span id="cb665-36"><a href="leçon-6.html#cb665-36" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>), </span>
<span id="cb665-37"><a href="leçon-6.html#cb665-37" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb665-38"><a href="leçon-6.html#cb665-38" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="dv">2</span>, </span>
<span id="cb665-39"><a href="leçon-6.html#cb665-39" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb665-40"><a href="leçon-6.html#cb665-40" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Moyennes ± IC 95 % (échelle log)&quot;</span>, </span>
<span id="cb665-41"><a href="leçon-6.html#cb665-41" tabindex="-1"></a>     <span class="at">cex.main =</span> <span class="dv">2</span>)</span>
<span id="cb665-42"><a href="leçon-6.html#cb665-42" tabindex="-1"></a></span>
<span id="cb665-43"><a href="leçon-6.html#cb665-43" tabindex="-1"></a><span class="do">##ajout de l&#39;axe des x&#39;s</span></span>
<span id="cb665-44"><a href="leçon-6.html#cb665-44" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb665-45"><a href="leçon-6.html#cb665-45" tabindex="-1"></a>     <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb665-46"><a href="leçon-6.html#cb665-46" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;sans horm&quot;</span>, <span class="st">&quot;horm&quot;</span>), </span>
<span id="cb665-47"><a href="leçon-6.html#cb665-47" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="dv">2</span>)</span>
<span id="cb665-48"><a href="leçon-6.html#cb665-48" tabindex="-1"></a></span>
<span id="cb665-49"><a href="leçon-6.html#cb665-49" tabindex="-1"></a><span class="do">##ajout des points pour mâles</span></span>
<span id="cb665-50"><a href="leçon-6.html#cb665-50" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> pred.set<span class="sc">$</span>fit[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)], </span>
<span id="cb665-51"><a href="leçon-6.html#cb665-51" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">1.9</span>), </span>
<span id="cb665-52"><a href="leçon-6.html#cb665-52" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>, </span>
<span id="cb665-53"><a href="leçon-6.html#cb665-53" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb665-54"><a href="leçon-6.html#cb665-54" tabindex="-1"></a></span>
<span id="cb665-55"><a href="leçon-6.html#cb665-55" tabindex="-1"></a><span class="do">##ajout des points pour femelles</span></span>
<span id="cb665-56"><a href="leçon-6.html#cb665-56" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> pred.set<span class="sc">$</span>fit[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)], </span>
<span id="cb665-57"><a href="leçon-6.html#cb665-57" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">c</span>(<span class="fl">1.1</span>, <span class="fl">2.1</span>), </span>
<span id="cb665-58"><a href="leçon-6.html#cb665-58" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">2</span>, </span>
<span id="cb665-59"><a href="leçon-6.html#cb665-59" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb665-60"><a href="leçon-6.html#cb665-60" tabindex="-1"></a></span>
<span id="cb665-61"><a href="leçon-6.html#cb665-61" tabindex="-1"></a><span class="do">##barres d&#39;erreurs pour mâles</span></span>
<span id="cb665-62"><a href="leçon-6.html#cb665-62" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">1.9</span>), </span>
<span id="cb665-63"><a href="leçon-6.html#cb665-63" tabindex="-1"></a>       <span class="at">y0 =</span> pred.set<span class="sc">$</span>low95[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)], </span>
<span id="cb665-64"><a href="leçon-6.html#cb665-64" tabindex="-1"></a>       <span class="at">y1 =</span> pred.set<span class="sc">$</span>upp95[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)],</span>
<span id="cb665-65"><a href="leçon-6.html#cb665-65" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">1.9</span>), </span>
<span id="cb665-66"><a href="leçon-6.html#cb665-66" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb665-67"><a href="leçon-6.html#cb665-67" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb665-68"><a href="leçon-6.html#cb665-68" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb665-69"><a href="leçon-6.html#cb665-69" tabindex="-1"></a></span>
<span id="cb665-70"><a href="leçon-6.html#cb665-70" tabindex="-1"></a><span class="do">##barres d&#39;erreurs pour femelles</span></span>
<span id="cb665-71"><a href="leçon-6.html#cb665-71" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>, <span class="fl">2.1</span>), </span>
<span id="cb665-72"><a href="leçon-6.html#cb665-72" tabindex="-1"></a>       <span class="at">y0 =</span> pred.set<span class="sc">$</span>low95[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)], </span>
<span id="cb665-73"><a href="leçon-6.html#cb665-73" tabindex="-1"></a>       <span class="at">y1 =</span> pred.set<span class="sc">$</span>upp95[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)],</span>
<span id="cb665-74"><a href="leçon-6.html#cb665-74" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>, <span class="fl">2.1</span>), </span>
<span id="cb665-75"><a href="leçon-6.html#cb665-75" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb665-76"><a href="leçon-6.html#cb665-76" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb665-77"><a href="leçon-6.html#cb665-77" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb665-78"><a href="leçon-6.html#cb665-78" tabindex="-1"></a></span>
<span id="cb665-79"><a href="leçon-6.html#cb665-79" tabindex="-1"></a><span class="do">##ajouter légende</span></span>
<span id="cb665-80"><a href="leçon-6.html#cb665-80" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>, </span>
<span id="cb665-81"><a href="leçon-6.html#cb665-81" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;mâles&quot;</span>, <span class="st">&quot;femelles&quot;</span>), </span>
<span id="cb665-82"><a href="leçon-6.html#cb665-82" tabindex="-1"></a>       <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb665-83"><a href="leçon-6.html#cb665-83" tabindex="-1"></a></span>
<span id="cb665-84"><a href="leçon-6.html#cb665-84" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">2.8</span>, <span class="at">y =</span> <span class="fl">2.3</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<!-- Ce prochain chunk de code n'apparait pas mais est utilisé pour générer la figure' -->
<pre><code>##   Sexe     Trait      fit     se.fit    low95    upp95
## 1    m sans_horm 2.482887 0.08614538 2.300267 2.665507
## 2    f sans_horm 2.689163 0.08614538 2.506543 2.871783
## 3    m      horm 3.318452 0.08614538 3.135832 3.501072
## 4    f      horm 3.452481 0.08614538 3.269861 3.635101</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotresult"></span>
<img src="Cours_Stats_R_files/figure-html/plotresult-1.png" alt="Résultats de l'ANOVA à deux critères présentés sur l'échelle logarithmique (a) et sur l'échelle originale de la variable réponse (b)." width="672" />
<p class="caption">
Figure 7.4: Résultats de l’ANOVA à deux critères présentés sur l’échelle logarithmique (a) et sur l’échelle originale de la variable réponse (b).
</p>
</div>
<p>Le graphique sur l’échelle logarithmique (Figure <a href="leçon-6.html#fig:plotresult">7.4</a>a) montre clairement que les effets sont additifs (pas d’effet d’interaction), puisque la distance entre le cercle et le triangle du traitement hormonal est la même que celle entre les deux symboles du traitement sans hormone.</p>
<p>Il est aussi approprié de présenter les résultats sur l’échelle originale de la variable réponse en effectuant l’opération inverse du logarithme naturel (c.-à-d., <code>exp( )</code>) sur la moyenne et sur les bornes inférieures et supérieures des intervalles de confiance.</p>
<div class="sourceCode" id="cb667"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb667-1"><a href="leçon-6.html#cb667-1" tabindex="-1"></a><span class="do">## On prend l’exponentiel pour convertir les données </span></span>
<span id="cb667-2"><a href="leçon-6.html#cb667-2" tabindex="-1"></a><span class="do">## transformées par le logarithme.</span></span>
<span id="cb667-3"><a href="leçon-6.html#cb667-3" tabindex="-1"></a>pred.set<span class="sc">$</span>orig.fit <span class="ot">&lt;-</span> <span class="fu">exp</span>(pred.set<span class="sc">$</span>fit)</span>
<span id="cb667-4"><a href="leçon-6.html#cb667-4" tabindex="-1"></a>pred.set<span class="sc">$</span>orig.low95 <span class="ot">&lt;-</span> <span class="fu">exp</span>(pred.set<span class="sc">$</span>low95)</span>
<span id="cb667-5"><a href="leçon-6.html#cb667-5" tabindex="-1"></a>pred.set<span class="sc">$</span>orig.upp95 <span class="ot">&lt;-</span> <span class="fu">exp</span>(pred.set<span class="sc">$</span>upp95)</span>
<span id="cb667-6"><a href="leçon-6.html#cb667-6" tabindex="-1"></a></span>
<span id="cb667-7"><a href="leçon-6.html#cb667-7" tabindex="-1"></a><span class="do">##créer graphique</span></span>
<span id="cb667-8"><a href="leçon-6.html#cb667-8" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> <span class="dv">0</span>, <span class="at">x =</span> <span class="dv">0</span>, </span>
<span id="cb667-9"><a href="leçon-6.html#cb667-9" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Concentration en calcium&quot;</span>,</span>
<span id="cb667-10"><a href="leçon-6.html#cb667-10" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Traitement&quot;</span>, </span>
<span id="cb667-11"><a href="leçon-6.html#cb667-11" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="dv">2</span>, </span>
<span id="cb667-12"><a href="leçon-6.html#cb667-12" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(pred.set<span class="sc">$</span>orig.low95), <span class="fu">max</span>(pred.set<span class="sc">$</span>orig.upp95)), </span>
<span id="cb667-13"><a href="leçon-6.html#cb667-13" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>), </span>
<span id="cb667-14"><a href="leçon-6.html#cb667-14" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb667-15"><a href="leçon-6.html#cb667-15" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="dv">2</span>, </span>
<span id="cb667-16"><a href="leçon-6.html#cb667-16" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb667-17"><a href="leçon-6.html#cb667-17" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Moyennes ± IC 95 % (échelle originale)&quot;</span>, </span>
<span id="cb667-18"><a href="leçon-6.html#cb667-18" tabindex="-1"></a>     <span class="at">cex.main =</span> <span class="dv">2</span>)</span>
<span id="cb667-19"><a href="leçon-6.html#cb667-19" tabindex="-1"></a></span>
<span id="cb667-20"><a href="leçon-6.html#cb667-20" tabindex="-1"></a><span class="do">##ajout de l&#39;axe des x&#39;s</span></span>
<span id="cb667-21"><a href="leçon-6.html#cb667-21" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb667-22"><a href="leçon-6.html#cb667-22" tabindex="-1"></a>     <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb667-23"><a href="leçon-6.html#cb667-23" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;sans horm&quot;</span>, <span class="st">&quot;horm&quot;</span>), </span>
<span id="cb667-24"><a href="leçon-6.html#cb667-24" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="dv">2</span>)</span>
<span id="cb667-25"><a href="leçon-6.html#cb667-25" tabindex="-1"></a></span>
<span id="cb667-26"><a href="leçon-6.html#cb667-26" tabindex="-1"></a><span class="do">##ajout des points pour mâles</span></span>
<span id="cb667-27"><a href="leçon-6.html#cb667-27" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> pred.set<span class="sc">$</span>orig.fit[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)], </span>
<span id="cb667-28"><a href="leçon-6.html#cb667-28" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">1.9</span>), </span>
<span id="cb667-29"><a href="leçon-6.html#cb667-29" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>, </span>
<span id="cb667-30"><a href="leçon-6.html#cb667-30" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb667-31"><a href="leçon-6.html#cb667-31" tabindex="-1"></a></span>
<span id="cb667-32"><a href="leçon-6.html#cb667-32" tabindex="-1"></a><span class="do">##ajout des points pour femelles</span></span>
<span id="cb667-33"><a href="leçon-6.html#cb667-33" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> pred.set<span class="sc">$</span>orig.fit[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>)],</span>
<span id="cb667-34"><a href="leçon-6.html#cb667-34" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">c</span>(<span class="fl">1.1</span>, <span class="fl">2.1</span>), </span>
<span id="cb667-35"><a href="leçon-6.html#cb667-35" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">2</span>, </span>
<span id="cb667-36"><a href="leçon-6.html#cb667-36" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb667-37"><a href="leçon-6.html#cb667-37" tabindex="-1"></a></span>
<span id="cb667-38"><a href="leçon-6.html#cb667-38" tabindex="-1"></a><span class="do">##barres d&#39;erreurs pour mâles</span></span>
<span id="cb667-39"><a href="leçon-6.html#cb667-39" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">1.9</span>), </span>
<span id="cb667-40"><a href="leçon-6.html#cb667-40" tabindex="-1"></a>       <span class="at">y0 =</span> pred.set<span class="sc">$</span>orig.low95[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)], </span>
<span id="cb667-41"><a href="leçon-6.html#cb667-41" tabindex="-1"></a>       <span class="at">y1 =</span> pred.set<span class="sc">$</span>orig.upp95[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)],</span>
<span id="cb667-42"><a href="leçon-6.html#cb667-42" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">1.9</span>), </span>
<span id="cb667-43"><a href="leçon-6.html#cb667-43" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb667-44"><a href="leçon-6.html#cb667-44" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb667-45"><a href="leçon-6.html#cb667-45" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb667-46"><a href="leçon-6.html#cb667-46" tabindex="-1"></a></span>
<span id="cb667-47"><a href="leçon-6.html#cb667-47" tabindex="-1"></a><span class="do">##barres d&#39;erreurs pour femelles</span></span>
<span id="cb667-48"><a href="leçon-6.html#cb667-48" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>, <span class="fl">2.1</span>), </span>
<span id="cb667-49"><a href="leçon-6.html#cb667-49" tabindex="-1"></a>       <span class="at">y0 =</span> pred.set<span class="sc">$</span>orig.low95[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)], </span>
<span id="cb667-50"><a href="leçon-6.html#cb667-50" tabindex="-1"></a>       <span class="at">y1 =</span> pred.set<span class="sc">$</span>orig.upp95[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>)],</span>
<span id="cb667-51"><a href="leçon-6.html#cb667-51" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="fu">c</span>(<span class="fl">1.1</span>, <span class="fl">2.1</span>), </span>
<span id="cb667-52"><a href="leçon-6.html#cb667-52" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb667-53"><a href="leçon-6.html#cb667-53" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb667-54"><a href="leçon-6.html#cb667-54" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb667-55"><a href="leçon-6.html#cb667-55" tabindex="-1"></a></span>
<span id="cb667-56"><a href="leçon-6.html#cb667-56" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="fl">2.8</span>, </span>
<span id="cb667-57"><a href="leçon-6.html#cb667-57" tabindex="-1"></a>     <span class="at">y =</span> <span class="dv">10</span>, </span>
<span id="cb667-58"><a href="leçon-6.html#cb667-58" tabindex="-1"></a>     <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, </span>
<span id="cb667-59"><a href="leçon-6.html#cb667-59" tabindex="-1"></a>     <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb667-60"><a href="leçon-6.html#cb667-60" tabindex="-1"></a></span>
<span id="cb667-61"><a href="leçon-6.html#cb667-61" tabindex="-1"></a><span class="do">##ajouter légende</span></span>
<span id="cb667-62"><a href="leçon-6.html#cb667-62" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>, </span>
<span id="cb667-63"><a href="leçon-6.html#cb667-63" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;mâles&quot;</span>, <span class="st">&quot;femelles&quot;</span>), </span>
<span id="cb667-64"><a href="leçon-6.html#cb667-64" tabindex="-1"></a>       <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb667-65"><a href="leçon-6.html#cb667-65" tabindex="-1"></a>       <span class="at">cex =</span> <span class="dv">2</span>)</span></code></pre></div>
<p>En l’absence d’une interaction statistiquement significative (comme dans cet exemple), on présente les résultats séparément pour chaque facteur (Figure <a href="leçon-6.html#fig:resCalcium">7.5</a>). On voit à la Figure <a href="leçon-6.html#fig:resCalcium">7.5</a> que la concentration de calcium du groupe sans traitement hormonal est bien inférieure à celle du groupe avec traitement hormonal, alors que les différences entre mâles et femelles sont beaucoup moins marquées.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:resCalcium"></span>
<img src="Cours_Stats_R_files/figure-html/resCalcium-1.png" alt="Résultats présentés séparément pour chaque facteur de l'ANOVA à deux critères présentés sur l'échelle d'origine. Les groupes qui ont les mêmes lettres ne diffèrent pas entre eux pour un facteur donné et avec un seuil de d'effet significatif $\alpha$ &lt; 0.05." width="672" />
<p class="caption">
Figure 7.5: Résultats présentés séparément pour chaque facteur de l’ANOVA à deux critères présentés sur l’échelle d’origine. Les groupes qui ont les mêmes lettres ne diffèrent pas entre eux pour un facteur donné et avec un seuil de d’effet significatif <span class="math inline">\(\alpha\)</span> &lt; 0.05.
</p>
</div>
</div>
</div>
<div id="effets-additifs" class="section level3 hasAnchor" number="7.1.5">
<h3><span class="header-section-number">7.1.5</span> Effets additifs<a href="leçon-6.html#effets-additifs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dans l’exemple précédent, on remarque que l’effet du premier facteur est indépendant de l’effet du deuxième facteur. En d’autres mots, la différence entre les mâles et les femelles est constante, peu importe le traitement hormonal. En l’absence d’une interaction statistiquement significative entre les deux facteurs, nous dirons que les effets des facteurs sont <strong>additifs</strong>. C’est ce qu’on entend par l’<strong>additivité</strong> des facteurs. En contrepartie, la présence d’une interaction significative entre les facteurs complique l’interprétation des résultats de l’expérimentation. Effectivement, la présence d’une interaction permet d’identifier des phénomènes souvent plus intéressants scientifiquement que s’il n’y avait pas d’interaction entre les facteurs. C’est ce que nous constaterons dans certains des exemples suivants.</p>
<div class="exemple" section="7">
<p>Nous désirons déterminer l’effet du type de moulée (avoine, blé ou orge) et du type de supplément alimentaire (<em>agrimore</em>, <em>control</em>, <em>supergain</em> et <em>supersupp</em>) sur le gain en masse en kg de bétail après 6 semaines. Les données sont stockées dans le fichier <code>croissance.csv</code><a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a>.</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="leçon-6.html#cb668-1" tabindex="-1"></a><span class="do">## importation avec séparateur virgule car ici les champs sont séparés par des virgules</span></span>
<span id="cb668-2"><a href="leçon-6.html#cb668-2" tabindex="-1"></a>croissance <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Module_7/data/croissance.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">&quot;,&quot;</span>)</span>
<span id="cb668-3"><a href="leçon-6.html#cb668-3" tabindex="-1"></a><span class="fu">head</span>(croissance)</span></code></pre></div>
<pre><code>##   Supplement Diete     Gain
## 1  supergain   ble 17.37125
## 2  supergain   ble 16.81489
## 3  supergain   ble 18.08184
## 4  supergain   ble 15.78175
## 5    control   ble 17.70656
## 6    control   ble 18.22717</code></pre>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb670-1"><a href="leçon-6.html#cb670-1" tabindex="-1"></a><span class="do">## la fonction str() affiche la structure interne du tableau C’est une fonction alternative à summary()</span></span>
<span id="cb670-2"><a href="leçon-6.html#cb670-2" tabindex="-1"></a><span class="fu">str</span>(croissance)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    48 obs. of  3 variables:
##  $ Supplement: chr  &quot;supergain&quot; &quot;supergain&quot; &quot;supergain&quot; &quot;supergain&quot; ...
##  $ Diete     : chr  &quot;ble&quot; &quot;ble&quot; &quot;ble&quot; &quot;ble&quot; ...
##  $ Gain      : num  17.4 16.8 18.1 15.8 17.7 ...</code></pre>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb672-1"><a href="leçon-6.html#cb672-1" tabindex="-1"></a><span class="do">## comparer avec importation sans sep = &#39;,&#39;</span></span>
<span id="cb672-2"><a href="leçon-6.html#cb672-2" tabindex="-1"></a>crois2 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Module_7/data/croissance.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb672-3"><a href="leçon-6.html#cb672-3" tabindex="-1"></a><span class="fu">head</span>(crois2)</span></code></pre></div>
<pre><code>##   Supplement   X..Diete...Gain.
## 1  supergain ,&quot;ble&quot;,17.37125111
## 2  supergain ,&quot;ble&quot;,16.81488903
## 3  supergain  ,&quot;ble&quot;,18.0818374
## 4  supergain ,&quot;ble&quot;,15.78174829
## 5    control ,&quot;ble&quot;,17.70656456
## 6    control ,&quot;ble&quot;,18.22716932</code></pre>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="leçon-6.html#cb674-1" tabindex="-1"></a><span class="do">## on remarque un problème à l&#39;importation les étiquettes des variables et les valeurs sont erronées</span></span>
<span id="cb674-2"><a href="leçon-6.html#cb674-2" tabindex="-1"></a><span class="fu">str</span>(crois2)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    48 obs. of  2 variables:
##  $ Supplement      : chr  &quot;supergain&quot; &quot;supergain&quot; &quot;supergain&quot; &quot;supergain&quot; ...
##  $ X..Diete...Gain.: chr  &quot;,\&quot;ble\&quot;,17.37125111&quot; &quot;,\&quot;ble\&quot;,16.81488903&quot; &quot;,\&quot;ble\&quot;,18.0818374&quot; &quot;,\&quot;ble\&quot;,15.78174829&quot; ...</code></pre>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="leçon-6.html#cb676-1" tabindex="-1"></a><span class="do">## transformer en facteurs les variables en caracteres</span></span>
<span id="cb676-2"><a href="leçon-6.html#cb676-2" tabindex="-1"></a>croissance<span class="sc">$</span>Supplement <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(croissance<span class="sc">$</span>Supplement)</span>
<span id="cb676-3"><a href="leçon-6.html#cb676-3" tabindex="-1"></a>croissance<span class="sc">$</span>Diete <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(croissance<span class="sc">$</span>Diete)</span></code></pre></div>
<p>On vérifie le nombre de répétitions pour chaque combinaison des deux facteurs :</p>
<div class="sourceCode" id="cb677"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb677-1"><a href="leçon-6.html#cb677-1" tabindex="-1"></a><span class="fu">table</span>(croissance<span class="sc">$</span>Supplement, croissance<span class="sc">$</span>Diete)</span></code></pre></div>
<pre><code>##            
##             avoine ble orge
##   agrimore       4   4    4
##   control        4   4    4
##   supergain      4   4    4
##   supersupp      4   4    4</code></pre>
<p>Nous disposons de quatre répétitions pour chaque combinaison de facteurs. Ainsi, nous pourrons inclure un terme d’interaction dans l’ANOVA à deux facteurs. Avant de lancer l’analyse, on peut jeter un coup d’oeil aux données brutes à l’aide d’un diagramme de boîtes et moustaches (Figure <a href="leçon-6.html#fig:croisbox">7.6</a>).</p>
<div class="sourceCode" id="cb679"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb679-1"><a href="leçon-6.html#cb679-1" tabindex="-1"></a><span class="do">##on crée un boxplot</span></span>
<span id="cb679-2"><a href="leçon-6.html#cb679-2" tabindex="-1"></a><span class="fu">boxplot</span>(Gain <span class="sc">~</span> Supplement <span class="sc">+</span> Diete, <span class="at">data =</span> croissance)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:croisbox"></span>
<img src="Cours_Stats_R_files/figure-html/croisbox-1.png" alt="Diagramme de boîtes et moustaches présentant les données de gain de masse en fonction du type de moulée (Diete) et de supplément (Supplement)." width="672" />
<p class="caption">
Figure 7.6: Diagramme de boîtes et moustaches présentant les données de gain de masse en fonction du type de moulée (Diete) et de supplément (Supplement).
</p>
</div>
<p>Calculons maintenant l’ANOVA :</p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="leçon-6.html#cb680-1" tabindex="-1"></a>aov.crois <span class="ot">&lt;-</span> <span class="fu">aov</span>(Gain <span class="sc">~</span> Supplement <span class="sc">+</span> Diete <span class="sc">+</span> Supplement<span class="sc">:</span>Diete,</span>
<span id="cb680-2"><a href="leçon-6.html#cb680-2" tabindex="-1"></a>                 <span class="at">data =</span> croissance)</span>
<span id="cb680-3"><a href="leçon-6.html#cb680-3" tabindex="-1"></a><span class="fu">summary</span>(aov.crois)</span></code></pre></div>
<pre><code>##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Supplement        3  91.88   30.63   17.82 2.95e-07 ***
## Diete             2 287.17  143.59   83.52 3.00e-14 ***
## Supplement:Diete  6   3.41    0.57    0.33    0.917    
## Residuals        36  61.89    1.72                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Avant d’interpréter les résultats, on vérifie les suppositions du modèle.</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="leçon-6.html#cb682-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb682-2"><a href="leçon-6.html#cb682-2" tabindex="-1"></a></span>
<span id="cb682-3"><a href="leçon-6.html#cb682-3" tabindex="-1"></a><span class="do">##Vérification de la normalité des résidus</span></span>
<span id="cb682-4"><a href="leçon-6.html#cb682-4" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(aov.crois), </span>
<span id="cb682-5"><a href="leçon-6.html#cb682-5" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Quantiles observés&quot;</span>,</span>
<span id="cb682-6"><a href="leçon-6.html#cb682-6" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;Quantiles théoriques&quot;</span>, </span>
<span id="cb682-7"><a href="leçon-6.html#cb682-7" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Graphique quantile-quantile&quot;</span>,</span>
<span id="cb682-8"><a href="leçon-6.html#cb682-8" tabindex="-1"></a>       <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span>
<span id="cb682-9"><a href="leçon-6.html#cb682-9" tabindex="-1"></a></span>
<span id="cb682-10"><a href="leçon-6.html#cb682-10" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(aov.crois))</span>
<span id="cb682-11"><a href="leçon-6.html#cb682-11" tabindex="-1"></a></span>
<span id="cb682-12"><a href="leçon-6.html#cb682-12" tabindex="-1"></a><span class="do">##Vérification de l&#39;homogénéité de la variance</span></span>
<span id="cb682-13"><a href="leçon-6.html#cb682-13" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(aov.crois) <span class="sc">~</span> <span class="fu">fitted</span>(aov.crois), </span>
<span id="cb682-14"><a href="leçon-6.html#cb682-14" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Résidus&quot;</span>, </span>
<span id="cb682-15"><a href="leçon-6.html#cb682-15" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>, </span>
<span id="cb682-16"><a href="leçon-6.html#cb682-16" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="fu">bold</span>(Résidus), <span class="st">&quot; &quot;</span>, <span class="fu">bold</span>(<span class="fu">italic</span>(vs)), <span class="st">&quot; &quot;</span>, </span>
<span id="cb682-17"><a href="leçon-6.html#cb682-17" tabindex="-1"></a>         <span class="fu">bold</span>(valeurs), <span class="st">&quot; &quot;</span>, <span class="fu">bold</span>(prédites))), </span>
<span id="cb682-18"><a href="leçon-6.html#cb682-18" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:croisdiag"></span>
<img src="Cours_Stats_R_files/figure-html/croisdiag-1.png" alt="Vérification des suppositions de l'ANOVA à deux critères." width="672" />
<p class="caption">
Figure 7.7: Vérification des suppositions de l’ANOVA à deux critères.
</p>
</div>
<p>Nous remarquons que les résidus sur le graphique suivent généralement une distribution normale et qu’à l’exception de trois observations, l’homogénéité des variances est respectée (Figure <a href="leçon-6.html#fig:croisdiag">7.7</a>). Nous pouvons donc procéder à l’interprétation des résultats.</p>
<p>Le type de supplément et le type de moulée ont tous deux un effet important sur le gain de masse (supplément: <span class="math inline">\(F_{3, 36} = 17.81, P &lt; 0.0001\)</span>; type de moulée: <span class="math inline">\(F_{2, 36} = 83.52, P &lt; 0.0001\)</span>). Toutefois, il n’y aucune preuve d’une interaction entre les deux facteurs (<span class="math inline">\(F_{6, 36} = 0.33, P = 0.92\)</span>). On peut donc conclure que les effets sont additifs. Les comparaisons multiples suggèrent des différences entre certains groupes de chaque facteur :</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="leçon-6.html#cb683-1" tabindex="-1"></a><span class="do">##On test d’abord les interactions entre les suppléments</span></span>
<span id="cb683-2"><a href="leçon-6.html#cb683-2" tabindex="-1"></a><span class="fu">tapply</span>(<span class="at">X =</span> croissance<span class="sc">$</span>Gain, <span class="at">INDEX =</span> croissance<span class="sc">$</span>Supplement, </span>
<span id="cb683-3"><a href="leçon-6.html#cb683-3" tabindex="-1"></a>       <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##  agrimore   control supergain supersupp 
##  23.09531  20.39861  19.71385  22.36796</code></pre>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="leçon-6.html#cb685-1" tabindex="-1"></a><span class="do">##</span></span>
<span id="cb685-2"><a href="leçon-6.html#cb685-2" tabindex="-1"></a><span class="do">##Tukey</span></span>
<span id="cb685-3"><a href="leçon-6.html#cb685-3" tabindex="-1"></a>mult.supp <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(aov.crois, <span class="at">which =</span> <span class="st">&quot;Supplement&quot;</span>)</span>
<span id="cb685-4"><a href="leçon-6.html#cb685-4" tabindex="-1"></a>mult.supp<span class="sc">$</span>Supplement</span></code></pre></div>
<pre><code>##                           diff       lwr        upr        p adj
## control-agrimore    -2.6967005 -4.138342 -1.2550592 7.641492e-05
## supergain-agrimore  -3.3814586 -4.823100 -1.9398173 1.534370e-06
## supersupp-agrimore  -0.7273521 -2.168993  0.7142892 5.326710e-01
## supergain-control   -0.6847581 -2.126399  0.7568832 5.817637e-01
## supersupp-control    1.9693484  0.527707  3.4109897 4.053368e-03
## supersupp-supergain  2.6541065  1.212465  4.0957478 9.722472e-05</code></pre>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="leçon-6.html#cb687-1" tabindex="-1"></a><span class="do">##On test les interactions entre les diètes</span></span>
<span id="cb687-2"><a href="leçon-6.html#cb687-2" tabindex="-1"></a><span class="fu">tapply</span>(<span class="at">X =</span> croissance<span class="sc">$</span>Gain, <span class="at">INDEX =</span> croissance<span class="sc">$</span>Diete, </span>
<span id="cb687-3"><a href="leçon-6.html#cb687-3" tabindex="-1"></a>       <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##   avoine      ble     orge 
## 21.32882 18.43134 24.42164</code></pre>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="leçon-6.html#cb689-1" tabindex="-1"></a><span class="do">##Tukey</span></span>
<span id="cb689-2"><a href="leçon-6.html#cb689-2" tabindex="-1"></a>mult.diete <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(aov.crois, <span class="at">which =</span> <span class="st">&quot;Diete&quot;</span>)</span>
<span id="cb689-3"><a href="leçon-6.html#cb689-3" tabindex="-1"></a>mult.diete<span class="sc">$</span>Diete</span></code></pre></div>
<pre><code>##                  diff       lwr       upr        p adj
## ble-avoine  -2.897481 -4.030582 -1.764379 9.530072e-07
## orge-avoine  3.092817  1.959715  4.225918 2.634600e-07
## orge-ble     5.990298  4.857196  7.123399 0.000000e+00</code></pre>
<p>On peut représenter les résultats des comparaisons multiples comme suit pour le type de supplément :</p>
<table class="table" style="color: black; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
supergain
</th>
<th style="text-align:center;">
control
</th>
<th style="text-align:center;">
supersupp
</th>
<th style="text-align:center;">
agrimore
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 10em; ">
19.714
</td>
<td style="text-align:center;width: 10em; ">
20.399
</td>
<td style="text-align:center;width: 10em; ">
22.368
</td>
<td style="text-align:center;width: 10em; ">
23.005
</td>
</tr>
</tbody>
</table>
<p>On peut représenter les résultats des comparaisons multiples comme suit pour le type de moulée (<code>Diete</code>) :</p>
<table class="table" style="color: black; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
blé
</th>
<th style="text-align:center;">
avoine
</th>
<th style="text-align:center;">
orge
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;width: 10em; ">
18.431
</td>
<td style="text-align:center;width: 10em; ">
21.329
</td>
<td style="text-align:center;width: 10em; ">
24.422
</td>
</tr>
</tbody>
</table>
<p>La figure <a href="leçon-6.html#fig:figcrois">7.8</a> illustre les résultats.</p>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="leçon-6.html#cb691-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb691-2"><a href="leçon-6.html#cb691-2" tabindex="-1"></a><span class="do">##supplement</span></span>
<span id="cb691-3"><a href="leçon-6.html#cb691-3" tabindex="-1"></a>supp.means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> croissance<span class="sc">$</span>Gain, </span>
<span id="cb691-4"><a href="leçon-6.html#cb691-4" tabindex="-1"></a>                     <span class="at">INDEX =</span> croissance<span class="sc">$</span>Supplement, <span class="at">FUN =</span> mean)</span>
<span id="cb691-5"><a href="leçon-6.html#cb691-5" tabindex="-1"></a>supp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(supp.means, <span class="at">MSE =</span> <span class="fl">1.719</span>)</span>
<span id="cb691-6"><a href="leçon-6.html#cb691-6" tabindex="-1"></a>supp<span class="sc">$</span>RMSE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(supp<span class="sc">$</span>MSE)</span>
<span id="cb691-7"><a href="leçon-6.html#cb691-7" tabindex="-1"></a>supp<span class="sc">$</span>low <span class="ot">&lt;-</span> supp<span class="sc">$</span>supp.means <span class="sc">-</span> supp<span class="sc">$</span>RMSE</span>
<span id="cb691-8"><a href="leçon-6.html#cb691-8" tabindex="-1"></a>supp<span class="sc">$</span>upp <span class="ot">&lt;-</span> supp<span class="sc">$</span>supp.means <span class="sc">+</span> supp<span class="sc">$</span>RMSE</span>
<span id="cb691-9"><a href="leçon-6.html#cb691-9" tabindex="-1"></a></span>
<span id="cb691-10"><a href="leçon-6.html#cb691-10" tabindex="-1"></a><span class="do">##diete</span></span>
<span id="cb691-11"><a href="leçon-6.html#cb691-11" tabindex="-1"></a>diet.means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> croissance<span class="sc">$</span>Gain, </span>
<span id="cb691-12"><a href="leçon-6.html#cb691-12" tabindex="-1"></a>                     <span class="at">INDEX =</span> croissance<span class="sc">$</span>Diet, <span class="at">FUN =</span> mean)</span>
<span id="cb691-13"><a href="leçon-6.html#cb691-13" tabindex="-1"></a>diet <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(diet.means, <span class="at">MSE =</span> <span class="fl">1.719</span>)</span>
<span id="cb691-14"><a href="leçon-6.html#cb691-14" tabindex="-1"></a>diet<span class="sc">$</span>RMSE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(diet<span class="sc">$</span>MSE)</span>
<span id="cb691-15"><a href="leçon-6.html#cb691-15" tabindex="-1"></a>diet<span class="sc">$</span>low <span class="ot">&lt;-</span> diet<span class="sc">$</span>diet.means <span class="sc">-</span> diet<span class="sc">$</span>RMSE</span>
<span id="cb691-16"><a href="leçon-6.html#cb691-16" tabindex="-1"></a>diet<span class="sc">$</span>upp <span class="ot">&lt;-</span> diet<span class="sc">$</span>diet.means <span class="sc">+</span> diet<span class="sc">$</span>RMSE</span>
<span id="cb691-17"><a href="leçon-6.html#cb691-17" tabindex="-1"></a></span>
<span id="cb691-18"><a href="leçon-6.html#cb691-18" tabindex="-1"></a><span class="do">##créer graphique</span></span>
<span id="cb691-19"><a href="leçon-6.html#cb691-19" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> <span class="dv">0</span>, <span class="at">x =</span> <span class="dv">0</span>, </span>
<span id="cb691-20"><a href="leçon-6.html#cb691-20" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Gain de masse (kg)&quot;</span>,</span>
<span id="cb691-21"><a href="leçon-6.html#cb691-21" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Supplément&quot;</span>, </span>
<span id="cb691-22"><a href="leçon-6.html#cb691-22" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="fu">max</span>(supp<span class="sc">$</span>upp)), </span>
<span id="cb691-23"><a href="leçon-6.html#cb691-23" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>), </span>
<span id="cb691-24"><a href="leçon-6.html#cb691-24" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb691-25"><a href="leçon-6.html#cb691-25" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>, </span>
<span id="cb691-26"><a href="leçon-6.html#cb691-26" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb691-27"><a href="leçon-6.html#cb691-27" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Moyennes ± racine carrée de MSE&quot;</span>)</span>
<span id="cb691-28"><a href="leçon-6.html#cb691-28" tabindex="-1"></a></span>
<span id="cb691-29"><a href="leçon-6.html#cb691-29" tabindex="-1"></a><span class="do">##ajout de l&#39;axe des x&#39;s</span></span>
<span id="cb691-30"><a href="leçon-6.html#cb691-30" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb691-31"><a href="leçon-6.html#cb691-31" tabindex="-1"></a>     <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), </span>
<span id="cb691-32"><a href="leçon-6.html#cb691-32" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;agri&quot;</span>, <span class="st">&quot;cont&quot;</span>, <span class="st">&quot;sgain&quot;</span>, <span class="st">&quot;ssupp&quot;</span>), </span>
<span id="cb691-33"><a href="leçon-6.html#cb691-33" tabindex="-1"></a>     <span class="at">cex.axis =</span> <span class="fl">0.85</span>)</span>
<span id="cb691-34"><a href="leçon-6.html#cb691-34" tabindex="-1"></a></span>
<span id="cb691-35"><a href="leçon-6.html#cb691-35" tabindex="-1"></a><span class="do">##ajout des points pour l&#39;ensemble des cereales</span></span>
<span id="cb691-36"><a href="leçon-6.html#cb691-36" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> supp<span class="sc">$</span>supp.means, <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">pch =</span> <span class="dv">1</span>)</span>
<span id="cb691-37"><a href="leçon-6.html#cb691-37" tabindex="-1"></a></span>
<span id="cb691-38"><a href="leçon-6.html#cb691-38" tabindex="-1"></a><span class="do">##barres d&#39;erreurs</span></span>
<span id="cb691-39"><a href="leçon-6.html#cb691-39" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, </span>
<span id="cb691-40"><a href="leçon-6.html#cb691-40" tabindex="-1"></a>       <span class="at">y0 =</span> supp<span class="sc">$</span>low, </span>
<span id="cb691-41"><a href="leçon-6.html#cb691-41" tabindex="-1"></a>       <span class="at">y1 =</span> supp<span class="sc">$</span>upp,</span>
<span id="cb691-42"><a href="leçon-6.html#cb691-42" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, </span>
<span id="cb691-43"><a href="leçon-6.html#cb691-43" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb691-44"><a href="leçon-6.html#cb691-44" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb691-45"><a href="leçon-6.html#cb691-45" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb691-46"><a href="leçon-6.html#cb691-46" tabindex="-1"></a></span>
<span id="cb691-47"><a href="leçon-6.html#cb691-47" tabindex="-1"></a><span class="do">##groups</span></span>
<span id="cb691-48"><a href="leçon-6.html#cb691-48" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">18.93</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-49"><a href="leçon-6.html#cb691-49" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">18.25</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-50"><a href="leçon-6.html#cb691-50" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">21.61</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-51"><a href="leçon-6.html#cb691-51" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="fl">20.89</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-52"><a href="leçon-6.html#cb691-52" tabindex="-1"></a>     </span>
<span id="cb691-53"><a href="leçon-6.html#cb691-53" tabindex="-1"></a><span class="do">##créer graphique</span></span>
<span id="cb691-54"><a href="leçon-6.html#cb691-54" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> <span class="dv">0</span>, <span class="at">x =</span> <span class="dv">0</span>, </span>
<span id="cb691-55"><a href="leçon-6.html#cb691-55" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Gain de masse (kg)&quot;</span>,</span>
<span id="cb691-56"><a href="leçon-6.html#cb691-56" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Diète&quot;</span>, </span>
<span id="cb691-57"><a href="leçon-6.html#cb691-57" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="fu">max</span>(diet<span class="sc">$</span>upp)), </span>
<span id="cb691-58"><a href="leçon-6.html#cb691-58" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>), </span>
<span id="cb691-59"><a href="leçon-6.html#cb691-59" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb691-60"><a href="leçon-6.html#cb691-60" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>, </span>
<span id="cb691-61"><a href="leçon-6.html#cb691-61" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb691-62"><a href="leçon-6.html#cb691-62" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Moyennes ± racine carrée de MSE&quot;</span>)</span>
<span id="cb691-63"><a href="leçon-6.html#cb691-63" tabindex="-1"></a></span>
<span id="cb691-64"><a href="leçon-6.html#cb691-64" tabindex="-1"></a><span class="do">##ajout de l&#39;axe des x&#39;s</span></span>
<span id="cb691-65"><a href="leçon-6.html#cb691-65" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb691-66"><a href="leçon-6.html#cb691-66" tabindex="-1"></a>     <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), </span>
<span id="cb691-67"><a href="leçon-6.html#cb691-67" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;avoine&quot;</span>, <span class="st">&quot;blé&quot;</span>, <span class="st">&quot;orge&quot;</span>), </span>
<span id="cb691-68"><a href="leçon-6.html#cb691-68" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-69"><a href="leçon-6.html#cb691-69" tabindex="-1"></a></span>
<span id="cb691-70"><a href="leçon-6.html#cb691-70" tabindex="-1"></a><span class="do">##ajout des points pour blé</span></span>
<span id="cb691-71"><a href="leçon-6.html#cb691-71" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> diet<span class="sc">$</span>diet.means, <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">pch =</span> <span class="dv">1</span>)</span>
<span id="cb691-72"><a href="leçon-6.html#cb691-72" tabindex="-1"></a></span>
<span id="cb691-73"><a href="leçon-6.html#cb691-73" tabindex="-1"></a><span class="do">##barres d&#39;erreurs</span></span>
<span id="cb691-74"><a href="leçon-6.html#cb691-74" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb691-75"><a href="leçon-6.html#cb691-75" tabindex="-1"></a>       <span class="at">y0 =</span> diet<span class="sc">$</span>low, </span>
<span id="cb691-76"><a href="leçon-6.html#cb691-76" tabindex="-1"></a>       <span class="at">y1 =</span> diet<span class="sc">$</span>upp,</span>
<span id="cb691-77"><a href="leçon-6.html#cb691-77" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb691-78"><a href="leçon-6.html#cb691-78" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb691-79"><a href="leçon-6.html#cb691-79" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb691-80"><a href="leçon-6.html#cb691-80" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb691-81"><a href="leçon-6.html#cb691-81" tabindex="-1"></a></span>
<span id="cb691-82"><a href="leçon-6.html#cb691-82" tabindex="-1"></a><span class="do">##groups</span></span>
<span id="cb691-83"><a href="leçon-6.html#cb691-83" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">19.7</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-84"><a href="leçon-6.html#cb691-84" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">16.8</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb691-85"><a href="leçon-6.html#cb691-85" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">22.8</span>, <span class="at">labels =</span> <span class="st">&quot;c&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figcrois"></span>
<img src="Cours_Stats_R_files/figure-html/figcrois-1.png" alt="Graphique des effets du type de supplément alimentaire ( exttt{Supplement}) et du type de moulée (   exttt{Diete}) sur le gain de masse en kilogrammes." width="672" />
<p class="caption">
Figure 7.8: Graphique des effets du type de supplément alimentaire ( exttt{Supplement}) et du type de moulée ( exttt{Diete}) sur le gain de masse en kilogrammes.
</p>
</div>
</div>
<p><br></p>
<div class="exemple" section="7">
<p>Comme dernier exemple, nous analyserons l’effet de la concentration d’un antibiotique et de l’humidité sur la croissance d’une espèce de bactéries que l’on peut cultiver en laboratoire dans des plats de Pétri contenant un substrat de sucres appelé agar-agar. La variable réponse ici est la surface du substrat couverte par les colonies de bactérie mesurée en mm<span class="math inline">\(^2\)</span>. Le fichier <code>antibio.txt</code> contient les données.</p>
<div class="sourceCode" id="cb692"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb692-1"><a href="leçon-6.html#cb692-1" tabindex="-1"></a>antibio <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Module_7/data/antibio.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb692-2"><a href="leçon-6.html#cb692-2" tabindex="-1"></a><span class="fu">head</span>(antibio)</span></code></pre></div>
<pre><code>##    Surface Humidite Concentration
## 1 2.103529      sec        faible
## 2 2.732448      sec        faible
## 3 1.864153      sec        faible
## 4 2.358879      sec        faible
## 5 2.195207      sec        faible
## 6 1.897846      sec       moderee</code></pre>
<div class="sourceCode" id="cb694"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb694-1"><a href="leçon-6.html#cb694-1" tabindex="-1"></a><span class="do">##on détermine le nombre de répétitions</span></span>
<span id="cb694-2"><a href="leçon-6.html#cb694-2" tabindex="-1"></a><span class="fu">table</span>(antibio<span class="sc">$</span>Humidite, antibio<span class="sc">$</span>Concentration)</span></code></pre></div>
<pre><code>##         
##          elevee faible moderee
##   humide      5      5       5
##   sec         5      5       5</code></pre>
<p>On présente les données par un diagramme de boîtes et moustaches (Figure <a href="leçon-6.html#fig:boxantibio">7.9</a>).</p>
<div class="sourceCode" id="cb696"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb696-1"><a href="leçon-6.html#cb696-1" tabindex="-1"></a><span class="fu">boxplot</span>(Surface <span class="sc">~</span> Humidite <span class="sc">+</span> Concentration, <span class="at">data =</span> antibio)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:boxantibio"></span>
<img src="Cours_Stats_R_files/figure-html/boxantibio-1.png" alt="Diagramme de boîtes et moustaches de la surface couverte en mm$^2$ en fonction de la concentration d'un antibiotique et de l'humidité." width="672" />
<p class="caption">
Figure 7.9: Diagramme de boîtes et moustaches de la surface couverte en mm<span class="math inline">\(^2\)</span> en fonction de la concentration d’un antibiotique et de l’humidité.
</p>
</div>
<!-- L'ordre des codes et textes dans dans le pdf c'est : le texte "On vérifie..." puis on a directement ensuite "On réalise...", puis le code de l'anova et puis la figure 10. Donc j'ai inversé les codes ici pour matcher avec le pdf car dans .rnw c'est text "On vérifie...", code anova, code graph, text "On réalise...", re-code anova -->
<p>On vérifie ensuite les suppositions d’homogénéité des variances et de normalités des résidus. On remarque que celles sont respectées (fig. <a href="leçon-6.html#fig:antibioDiag">7.10</a>).</p>
<p>On réalise maintenant l’ANOVA à deux critères :</p>
<div class="sourceCode" id="cb697"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb697-1"><a href="leçon-6.html#cb697-1" tabindex="-1"></a>aov.antibio <span class="ot">&lt;-</span> <span class="fu">aov</span>(Surface <span class="sc">~</span> Humidite <span class="sc">+</span> Concentration <span class="sc">+</span> </span>
<span id="cb697-2"><a href="leçon-6.html#cb697-2" tabindex="-1"></a>                   Humidite<span class="sc">:</span>Concentration,</span>
<span id="cb697-3"><a href="leçon-6.html#cb697-3" tabindex="-1"></a>                   <span class="at">data =</span> antibio)</span>
<span id="cb697-4"><a href="leçon-6.html#cb697-4" tabindex="-1"></a><span class="fu">summary</span>(aov.antibio)</span></code></pre></div>
<pre><code>##                        Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Humidite                1  20.23  20.228   181.6 1.09e-12 ***
## Concentration           2  15.93   7.965    71.5 7.76e-11 ***
## Humidite:Concentration  2  36.40  18.199   163.4 1.05e-14 ***
## Residuals              24   2.67   0.111                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:antibioDiag"></span>
<img src="Cours_Stats_R_files/figure-html/antibioDiag-1.png" alt="Homogénéité des variances et normalité des résidus de l'ANOVA à deux critères réalisées sur les données d'activité bactérienne (surface couverte par les colonies de bactéries)." width="672" />
<p class="caption">
Figure 7.10: Homogénéité des variances et normalité des résidus de l’ANOVA à deux critères réalisées sur les données d’activité bactérienne (surface couverte par les colonies de bactéries).
</p>
</div>
<p>Le tableau d’ANOVA montre une interaction importante entre les facteurs <code>Humidite</code> et <code>Concentration</code> (<span class="math inline">\(F_{2, 24} = 163.4, P &lt; 0.0001\)</span>). Les effets de la concentration d’antibiotique et de l’humidité ne sont pas additifs. Ceci implique que nous ne pouvons pas interpréter ces effets séparément, car l’effet d’un facteur dépend du niveau de l’autre facteur. Nous pouvons utiliser les comparaisons multiples pour trouver les différences entre les groupes définis par les différentes combinaisons des deux facteurs.</p>
<div class="sourceCode" id="cb699"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb699-1"><a href="leçon-6.html#cb699-1" tabindex="-1"></a><span class="fu">tapply</span>(<span class="at">X =</span> antibio<span class="sc">$</span>Surface, </span>
<span id="cb699-2"><a href="leçon-6.html#cb699-2" tabindex="-1"></a>       <span class="at">INDEX =</span> <span class="fu">list</span>(antibio<span class="sc">$</span>Humidite, antibio<span class="sc">$</span>Concentration), </span>
<span id="cb699-3"><a href="leçon-6.html#cb699-3" tabindex="-1"></a>       <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##          elevee   faible  moderee
## humide 1.637384 5.865661 5.036441
## sec    3.069767 2.250843 2.292084</code></pre>
<div class="sourceCode" id="cb701"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb701-1"><a href="leçon-6.html#cb701-1" tabindex="-1"></a>mult.inter <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(aov.antibio, <span class="at">which =</span> <span class="st">&quot;Humidite:Concentration&quot;</span>)</span>
<span id="cb701-2"><a href="leçon-6.html#cb701-2" tabindex="-1"></a>mult.inter<span class="sc">$</span><span class="st">&#39;Humidite:Concentration&#39;</span></span></code></pre></div>
<pre><code>##                                     diff          lwr        upr        p adj
## sec:elevee-humide:elevee      1.43238312  0.779715574  2.0850507 6.988460e-06
## humide:faible-humide:elevee   4.22827694  3.575609401  4.8809445 2.331468e-14
## sec:faible-humide:elevee      0.61345927 -0.039208277  1.2661268 7.400734e-02
## humide:moderee-humide:elevee  3.39905706  2.746389512  4.0517246 3.608225e-13
## sec:moderee-humide:elevee     0.65470026  0.002032716  1.3073678 4.897318e-02
## humide:faible-sec:elevee      2.79589383  2.143226283  3.4485614 2.259004e-11
## sec:faible-sec:elevee        -0.81892385 -1.471591395 -0.1662563 8.269047e-03
## humide:moderee-sec:elevee     1.96667394  1.314006394  2.6193415 2.716546e-08
## sec:moderee-sec:elevee       -0.77768286 -1.430350402 -0.1250153 1.312775e-02
## sec:faible-humide:faible     -3.61481768 -4.267485222 -2.9621501 1.112443e-13
## humide:moderee-humide:faible -0.82921989 -1.481887432 -0.1765523 7.359216e-03
## sec:moderee-humide:faible    -3.57357668 -4.226244229 -2.9209091 1.366685e-13
## humide:moderee-sec:faible     2.78559779  2.132930246  3.4382653 2.443656e-11
## sec:moderee-sec:faible        0.04124099 -0.611426550  0.6939085 9.999549e-01
## sec:moderee-humide:moderee   -2.74435680 -3.397024340 -2.0916893 3.354361e-11</code></pre>
<p>Les comparaisons multiples suggèrent les groupes suivants :</p>
<table>
<tr class="centered-row">
<th>
humide-élevée
</th>
<th>
sec-faible
</th>
<th>
sec-modérée
</th>
<th>
sec-élevée
</th>
<th>
humide-modérée
</th>
<th>
humide-faible
</th>
</tr>
<tr class="centered-row">
<td>
1.64 mm<sup>2</sup>
</td>
<td>
2.25 mm<sup>2</sup>
</td>
<td>
2.29 mm<sup>2</sup>
</td>
<td>
3.07 mm<sup>2</sup>
</td>
<td>
5.04 mm<sup>2
</td>
<td>
5.87 mm<sup>2</sup>
</td>
</tr>
<tr class="custom-row">
<td colspan="2" style="border-bottom: 2px solid;">
 
</td>
<td>
</td>
<td style="border-bottom: 2px solid;">
 
</td>
<td>
</td>
<td style="border-bottom: 2px solid;">
 
</td>
</tr>
<tr class="custom-row">
<td>
</td>
<td colspan="2" style="border-bottom: 2px solid;">
 
</td>
<td>
</td>
<td style="border-bottom: 2px solid;">
 
</td>
<td>
</td>
</tr>
</table>
<p>Représentons maintenant les résultats graphiquement.</p>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb703-1"><a href="leçon-6.html#cb703-1" tabindex="-1"></a><span class="do">##valeurs prédites</span></span>
<span id="cb703-2"><a href="leçon-6.html#cb703-2" tabindex="-1"></a>pred.out <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">Humidite =</span> <span class="fu">c</span>(<span class="st">&quot;sec&quot;</span>, <span class="st">&quot;humide&quot;</span>), </span>
<span id="cb703-3"><a href="leçon-6.html#cb703-3" tabindex="-1"></a>              <span class="at">Concentration =</span> <span class="fu">c</span>(<span class="st">&quot;faible&quot;</span>, <span class="st">&quot;moderee&quot;</span>, <span class="st">&quot;elevee&quot;</span>))</span>
<span id="cb703-4"><a href="leçon-6.html#cb703-4" tabindex="-1"></a></span>
<span id="cb703-5"><a href="leçon-6.html#cb703-5" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(aov.antibio, <span class="at">newdata =</span> pred.out, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb703-6"><a href="leçon-6.html#cb703-6" tabindex="-1"></a></span>
<span id="cb703-7"><a href="leçon-6.html#cb703-7" tabindex="-1"></a>pred.out<span class="sc">$</span>mean <span class="ot">&lt;-</span> preds<span class="sc">$</span>fit</span>
<span id="cb703-8"><a href="leçon-6.html#cb703-8" tabindex="-1"></a>pred.out<span class="sc">$</span>se <span class="ot">&lt;-</span> preds<span class="sc">$</span>se.fit</span>
<span id="cb703-9"><a href="leçon-6.html#cb703-9" tabindex="-1"></a></span>
<span id="cb703-10"><a href="leçon-6.html#cb703-10" tabindex="-1"></a><span class="do">##IC à 95%</span></span>
<span id="cb703-11"><a href="leçon-6.html#cb703-11" tabindex="-1"></a>pred.out<span class="sc">$</span>low95 <span class="ot">&lt;-</span> pred.out<span class="sc">$</span>mean <span class="sc">+</span> </span>
<span id="cb703-12"><a href="leçon-6.html#cb703-12" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> aov.antibio<span class="sc">$</span>df.residual) <span class="sc">*</span> pred.out<span class="sc">$</span>se</span>
<span id="cb703-13"><a href="leçon-6.html#cb703-13" tabindex="-1"></a>pred.out<span class="sc">$</span>upp95 <span class="ot">&lt;-</span> pred.out<span class="sc">$</span>mean <span class="sc">-</span> </span>
<span id="cb703-14"><a href="leçon-6.html#cb703-14" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> aov.antibio<span class="sc">$</span>df.residual) <span class="sc">*</span> pred.out<span class="sc">$</span>se</span>
<span id="cb703-15"><a href="leçon-6.html#cb703-15" tabindex="-1"></a></span>
<span id="cb703-16"><a href="leçon-6.html#cb703-16" tabindex="-1"></a><span class="do">##graphique</span></span>
<span id="cb703-17"><a href="leçon-6.html#cb703-17" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> <span class="dv">0</span>, <span class="at">x =</span> <span class="dv">0</span>, </span>
<span id="cb703-18"><a href="leçon-6.html#cb703-18" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb703-19"><a href="leçon-6.html#cb703-19" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Concentration d&#39;antibiotique&quot;</span>, </span>
<span id="cb703-20"><a href="leçon-6.html#cb703-20" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fu">max</span>(pred.out<span class="sc">$</span>upp95)), </span>
<span id="cb703-21"><a href="leçon-6.html#cb703-21" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>), </span>
<span id="cb703-22"><a href="leçon-6.html#cb703-22" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb703-23"><a href="leçon-6.html#cb703-23" tabindex="-1"></a>     <span class="at">cex.lab =</span> <span class="fl">1.2</span>, </span>
<span id="cb703-24"><a href="leçon-6.html#cb703-24" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb703-25"><a href="leçon-6.html#cb703-25" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Moyennes ± IC à 95 %&quot;</span>)</span>
<span id="cb703-26"><a href="leçon-6.html#cb703-26" tabindex="-1"></a></span>
<span id="cb703-27"><a href="leçon-6.html#cb703-27" tabindex="-1"></a><span class="do">##ajout d&#39;étiquette en marge</span></span>
<span id="cb703-28"><a href="leçon-6.html#cb703-28" tabindex="-1"></a><span class="do">##expression permet d&#39;ajouter des lettres grecques,</span></span>
<span id="cb703-29"><a href="leçon-6.html#cb703-29" tabindex="-1"></a><span class="do">##indices ou exposants</span></span>
<span id="cb703-30"><a href="leçon-6.html#cb703-30" tabindex="-1"></a><span class="fu">mtext</span>(<span class="at">text =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Surface (&quot;</span>, mm<span class="sc">^</span><span class="dv">2</span>, <span class="st">&quot;)&quot;</span>)),</span>
<span id="cb703-31"><a href="leçon-6.html#cb703-31" tabindex="-1"></a>      <span class="at">side =</span> <span class="dv">2</span>, </span>
<span id="cb703-32"><a href="leçon-6.html#cb703-32" tabindex="-1"></a>      <span class="at">line =</span> <span class="dv">2</span>, </span>
<span id="cb703-33"><a href="leçon-6.html#cb703-33" tabindex="-1"></a>      <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-34"><a href="leçon-6.html#cb703-34" tabindex="-1"></a></span>
<span id="cb703-35"><a href="leçon-6.html#cb703-35" tabindex="-1"></a><span class="do">##ajout de l&#39;axe des x&#39;s</span></span>
<span id="cb703-36"><a href="leçon-6.html#cb703-36" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb703-37"><a href="leçon-6.html#cb703-37" tabindex="-1"></a>     <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), </span>
<span id="cb703-38"><a href="leçon-6.html#cb703-38" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;faible&quot;</span>, <span class="st">&quot;modérée&quot;</span>, <span class="st">&quot;élevée&quot;</span>), </span>
<span id="cb703-39"><a href="leçon-6.html#cb703-39" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-40"><a href="leçon-6.html#cb703-40" tabindex="-1"></a></span>
<span id="cb703-41"><a href="leçon-6.html#cb703-41" tabindex="-1"></a><span class="do">##points pour sec</span></span>
<span id="cb703-42"><a href="leçon-6.html#cb703-42" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> pred.out<span class="sc">$</span>mean[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)], <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">pch =</span> <span class="dv">1</span>)</span>
<span id="cb703-43"><a href="leçon-6.html#cb703-43" tabindex="-1"></a></span>
<span id="cb703-44"><a href="leçon-6.html#cb703-44" tabindex="-1"></a><span class="do">##barres d&#39;erreurs</span></span>
<span id="cb703-45"><a href="leçon-6.html#cb703-45" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb703-46"><a href="leçon-6.html#cb703-46" tabindex="-1"></a>       <span class="at">y0 =</span> pred.out<span class="sc">$</span>low95[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)], </span>
<span id="cb703-47"><a href="leçon-6.html#cb703-47" tabindex="-1"></a>       <span class="at">y1 =</span> pred.out<span class="sc">$</span>upp95[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)],</span>
<span id="cb703-48"><a href="leçon-6.html#cb703-48" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb703-49"><a href="leçon-6.html#cb703-49" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb703-50"><a href="leçon-6.html#cb703-50" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb703-51"><a href="leçon-6.html#cb703-51" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb703-52"><a href="leçon-6.html#cb703-52" tabindex="-1"></a></span>
<span id="cb703-53"><a href="leçon-6.html#cb703-53" tabindex="-1"></a><span class="do">##points pour humide</span></span>
<span id="cb703-54"><a href="leçon-6.html#cb703-54" tabindex="-1"></a><span class="fu">points</span>(<span class="at">y =</span> pred.out<span class="sc">$</span>mean[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>)], <span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">pch =</span> <span class="dv">2</span>)</span>
<span id="cb703-55"><a href="leçon-6.html#cb703-55" tabindex="-1"></a></span>
<span id="cb703-56"><a href="leçon-6.html#cb703-56" tabindex="-1"></a><span class="do">##barres d&#39;erreurs</span></span>
<span id="cb703-57"><a href="leçon-6.html#cb703-57" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb703-58"><a href="leçon-6.html#cb703-58" tabindex="-1"></a>       <span class="at">y0 =</span> pred.out<span class="sc">$</span>low95[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>)], </span>
<span id="cb703-59"><a href="leçon-6.html#cb703-59" tabindex="-1"></a>       <span class="at">y1 =</span> pred.out<span class="sc">$</span>upp95[<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>)],</span>
<span id="cb703-60"><a href="leçon-6.html#cb703-60" tabindex="-1"></a>       <span class="at">x1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb703-61"><a href="leçon-6.html#cb703-61" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, </span>
<span id="cb703-62"><a href="leçon-6.html#cb703-62" tabindex="-1"></a>       <span class="at">code =</span> <span class="dv">3</span>, </span>
<span id="cb703-63"><a href="leçon-6.html#cb703-63" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb703-64"><a href="leçon-6.html#cb703-64" tabindex="-1"></a></span>
<span id="cb703-65"><a href="leçon-6.html#cb703-65" tabindex="-1"></a><span class="do">##légende</span></span>
<span id="cb703-66"><a href="leçon-6.html#cb703-66" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">&quot;topright&quot;</span>, </span>
<span id="cb703-67"><a href="leçon-6.html#cb703-67" tabindex="-1"></a>       <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), </span>
<span id="cb703-68"><a href="leçon-6.html#cb703-68" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;sec&quot;</span>, <span class="st">&quot;humide&quot;</span>),</span>
<span id="cb703-69"><a href="leçon-6.html#cb703-69" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Humidité&quot;</span>)</span>
<span id="cb703-70"><a href="leçon-6.html#cb703-70" tabindex="-1"></a></span>
<span id="cb703-71"><a href="leçon-6.html#cb703-71" tabindex="-1"></a><span class="do">##groupes</span></span>
<span id="cb703-72"><a href="leçon-6.html#cb703-72" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">5.4</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-73"><a href="leçon-6.html#cb703-73" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">4.6</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-74"><a href="leçon-6.html#cb703-74" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">1.2</span>, <span class="at">labels =</span> <span class="st">&quot;c&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-75"><a href="leçon-6.html#cb703-75" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">1.82</span>, <span class="at">labels =</span> <span class="st">&quot;cd&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-76"><a href="leçon-6.html#cb703-76" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">1.87</span>, <span class="at">labels =</span> <span class="st">&quot;d&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb703-77"><a href="leçon-6.html#cb703-77" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">2.6</span>, <span class="at">labels =</span> <span class="st">&quot;e&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:antibioRes"></span>
<img src="Cours_Stats_R_files/figure-html/antibioRes-1.png" alt="Interaction significative entre l'humidité et la concentration d'antibiotique sur l'activité bactérienne." width="672" />
<p class="caption">
Figure 7.11: Interaction significative entre l’humidité et la concentration d’antibiotique sur l’activité bactérienne.
</p>
</div>
<p>La Figure <a href="leçon-6.html#fig:antibioRes">7.11</a> montre qu’il y a bien une interaction entre les deux facteurs. Nous voyons clairement que la différence entre la moyenne du groupe “sec” et celle du groupe “humide” varie énormément avec la concentration d’antibiotique, et que cette différence est la plus faible quand la concentration d’antibiotique est élevée.</p>
<p>On remarque qu’il y a une inversion des différences entre les groupes “sec” et les groupes “humide” : la surface couverte moyenne du groupe “humide” est supérieure à celle du groupe “sec” aux concentrations faible et modérée d’antibitioque. Toutefois, le groupe “sec” a une plus grande surface couverte moyenne que le groupe “humide” à la concentration élevée d’antibiotique. On conclut que l’augmentation de la concentration de l’antibiotique réduit l’activité bactérienne sous des conditions humides, mais augmente l’activité bactérienne en conditions plus sèches.</p>
</div>
</div>
<div id="conclusion-6" class="section level3 hasAnchor" number="7.1.6">
<h3><span class="header-section-number">7.1.6</span> Conclusion<a href="leçon-6.html#conclusion-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dans ce texte, vous vous êtes familiarisés avec l’ANOVA à deux critères avec plusieurs répétitions par groupe aux traitements combinés, et particulièrement avec les concepts d’interaction et d’additivité. Trois exemples ont été présentés afin d’illustrer les différentes étapes de l’analyse, de la vérification des suppositions, de l’interprétation et de la présentation graphique des résultats. Nous avons vu qu’en présence d’une interaction entre deux facteurs, on ne peut pas interpréter les effets principaux, car l’effet d’un facteur sur la variable réponse dépend du niveau de l’autre. On dit dans ce cas que les effets ne sont pas additifs. C’est justement ce qu’illustre le dernier exemple sur l’activité bactérienne: l’augmentation de la concentration d’antibiotique n’avait pas le même effet selon le niveau d’humidité du milieu. Le concept d’interaction est important et il est souvent associé à des hypothèses intéressantes en sciences. Nous vous encourageons à revoir les exemples afin de bien saisir la notion d’interaction, car nous l’étudierons à nouveau dans les leçons à venir.</p>
<!--

## Laboratoire

Les données peuvent être retrouvées dans le dossier [Module 7](https://github.com/sci1018/sci1018_data/raw/main/Module_7.zip).

### Question 1 {-}

On effectue une expérience pour déterminer si la longueur en cm chez une espèce de poisson varie selon le sexe ou le pH de l'eau. Importez le fichier `Longueur_poisson.xls` pour voir les données^[Si `MS Excel` n'est pas installé sur votre ordinateur, il est possible d'importer le fichier à l'aide des suites bureautiques libres `OpenOffice` [http://www.openoffice.org/fr/Produits/](http://www.openoffice.org/fr/Produits/) ou `LibreOffice` [http://fr.libreoffice.org/](http://fr.libreoffice.org/).].

**a.** Déterminez le nombre de répétitions (*replicates*) pour chaque combinaison des deux facteurs. Veuillez interpréter les résultats obtenus avec `RStudio` ou `R Commander`.  

 
**b.** Réalisez une ANOVA à deux critères (fournir le tableau de l’ANOVA) et effectuez tous les diagnostics permettant d'évaluer la pertinence de votre analyse. Que pouvez-vous conclure?  

  
**c.** Lorsqu'il est approprié de le faire, utilisez un test de Tukey (fournir l’*output*) afin d'identifier les différences entre les moyennes. Que pouvez-vous conclure?  

 
**d.** Illustrez vos conclusions de l'étude à l'aide d'un graphique.  

 
**e.** Les effets sont-ils additifs?  

-->

</div>
</div>
<!-- </div> -->
<div class="footnotes">
<hr />
<ol start="21">
<li id="fn21"><p>Les résultats de l’ANOVA montrent que la probabilité associée au facteur sexe est suffisamment près du seuil de 0.05 pour que l’effet soit considéré biologiquement significatif. Pour cette raison, on peut retenir ce facteur dans les comparaisons multiples.<a href="leçon-6.html#fnref21" class="footnote-back">↩︎</a></p></li>
<li id="fn22"><p>À noter que dans notre exemple, il n’y a que deux niveaux (groupes) à chaque facteur: sexe a deux niveaux (mâle, femelle), et traitement hormonal n’a que deux niveaux (avec traitement, sans traitement). Ainsi, il ne serait pas absolument nécessaire de poursuivre avec des comparaisons multiples, car si on rejette <span class="math inline">\(H_0\)</span>, on sait que les deux groupes diffèrent entre eux.<a href="leçon-6.html#fnref22" class="footnote-back">↩︎</a></p></li>
<li id="fn23"><p>Le fichier <code>csv</code> est un type de fichier de texte standard où chaque élément est séparé le plus souvent par une virgule, un espace ou une point-virgule. Ce format s’importe dans R à l’aide de <code>read.table( )</code> puisque c’est un fichier de texte, en modifiant la valeur de l’argument <code>delim</code>.<a href="leçon-6.html#fnref23" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lecon7.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lecon8.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": false
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
