<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10.1 Leçon | Statistiques avec R</title>
  <meta name="description" content="10.1 Leçon | Statistiques avec R" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="10.1 Leçon | Statistiques avec R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="10.1 Leçon | Statistiques avec R" />
  <meta name="github-repo" content="sci1018/sci1018" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10.1 Leçon | Statistiques avec R" />
  
  <meta name="twitter:description" content="10.1 Leçon | Statistiques avec R" />
  

<meta name="author" content="" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lecon10.html"/>
<link rel="next" href="autoévaluation-6.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TÉLUQ - SCI 1018</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="part"><span><b>I SCI 1018</b></span></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html"><i class="fa fa-check"></i>À propos du cours</a>
<ul>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#pr%C3%A9sentation"><i class="fa fa-check"></i>Présentation</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#route"><i class="fa fa-check"></i>Feuille de route</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#cr%C3%A9dits"><i class="fa fa-check"></i>Crédits</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html"><i class="fa fa-check"></i>Ressources</a>
<ul>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#travaux-not%C3%A9s"><i class="fa fa-check"></i>Travaux notés</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#donn%C3%A9es"><i class="fa fa-check"></i>Données</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#forum"><i class="fa fa-check"></i>Forum du cours</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#guides-r"><i class="fa fa-check"></i>Guides R</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#ressources-r"><i class="fa fa-check"></i>Ressources R</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#ressources-r-commander"><i class="fa fa-check"></i>Ressources R commander</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#r%C3%A9f%C3%A9rences"><i class="fa fa-check"></i>Références</a></li>
</ul></li>
<li class="part"><span><b>II GUIDE R</b></span></li>
<li class="chapter" data-level="" data-path="InstallationR.html"><a href="InstallationR.html"><i class="fa fa-check"></i>Installation de R</a>
<ul>
<li class="chapter" data-level="" data-path="InstallationR.html"><a href="InstallationR.html#o%C3%B9-se-procurer"><i class="fa fa-check"></i>Où se procurer ?</a></li>
<li class="chapter" data-level="" data-path="pour-débuter-avec-r.html"><a href="pour-débuter-avec-r.html"><i class="fa fa-check"></i>Pour débuter avec R</a></li>
<li class="chapter" data-level="" data-path="choisir-son-éditeur.html"><a href="choisir-son-éditeur.html"><i class="fa fa-check"></i>Choisir son éditeur</a></li>
</ul></li>
<li class="part"><span><b>III APPRENTISSAGE</b></span></li>
<li class="chapter" data-level="" data-path="programmation-avec-r.html"><a href="programmation-avec-r.html"><i class="fa fa-check"></i>Programmation avec R</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistiques avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="leçon-9" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Leçon<a href="leçon-9.html#le%C3%A7on-9" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="la-régression-linéaire" class="section level3 hasAnchor" number="10.1.1">
<h3><span class="header-section-number">10.1.1</span> La régression linéaire<a href="leçon-9.html#la-r%C3%A9gression-lin%C3%A9aire" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La <strong>régression linéaire simple</strong> (<em>simple linear regression</em>) est le cas où une variable réponse, aussi appelée <strong>variable dépendante</strong> (<em>dependent variable</em>), varie en fonction d’une variable explicative, aussi appelée <strong>variable indépendante</strong> (<em>independent variable</em>) ou <strong>prédicteur</strong> (<em>predictor</em>). On utilise l’appellation régression <strong>linéaire</strong> puisque la relation entre les deux variables est linéaire: on trace une droite linéaire pour représenter la relation entre les deux variables. La régression linéaire implique une relation de cause à effet. Les variations des observations de la variable réponse (variable dépendante) sont causées, du moins en partie, par une variable explicative (variable indépendante).</p>
<div id="équation-de-régression" class="section level4 hasAnchor" number="10.1.1.1">
<h4><span class="header-section-number">10.1.1.1</span> Équation de régression<a href="leçon-9.html#%C3%A9quation-de-r%C3%A9gression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>On peut représenter l’<strong>équation de la droite de régression linéaire</strong> comme suit :</p>
<p><span class="math display">\[y_i = a + bx_i + \epsilon_i\]</span></p>
<p>où <span class="math inline">\(y_i\)</span> correspond à l’observation <span class="math inline">\(i\)</span> de la variable réponse <span class="math inline">\(y\)</span>, <span class="math inline">\(a\)</span> correspond à l’<strong>ordonnée à l’origine</strong> (<em>intercept</em>). L’ordonnée à l’origine représente le point sur l’axe des y’s qui est croisé par la droite de régression. Le terme <span class="math inline">\(b\)</span> correspond à l’estimation de la pente, qui indique le taux d’accroissement de <span class="math inline">\(y\)</span> avec une augmentation d’une unité de la variable explicative <span class="math inline">\(x\)</span>. Le terme <span class="math inline">\(x_i\)</span> correspond à l’observation <span class="math inline">\(i\)</span> de la variable explicative <span class="math inline">\(x\)</span>, et <span class="math inline">\(\epsilon_i\)</span> correspond au terme d’erreur associé à l’estimation de l’observation <span class="math inline">\(y_i\)</span>. Une notation équivalente utilise des termes <span class="math inline">\(\beta\)</span>, tels que :</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_{x} x_i + \epsilon_i\]</span></p>
<p>où <span class="math inline">\(\beta_0\)</span> représente l’ordonnée à l’origine et <span class="math inline">\(\beta_{x}\)</span> indique la pente de la variable explicative <span class="math inline">\(x\)</span>. C’est cette dernière notation que nous utiliserons dans cette leçon. De manière générale, on emploie le terme générique <strong>coefficient</strong> pour désigner <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_{x}\)</span>, <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span>. Ces coefficients représentent l’estimation de paramètres de la population (<em>parameter estimate</em>) pour désigner la valeur numérique de l’ordonnée à l’origine et de la pente. Le prochain exemple présente un jeu de données typique sur lequel on peut réaliser une régression linéaire.</p>
<div class="exemple" section="10">
<p>Nous nous intéressons au pouvoir des campagnes publicitaires lorsqu’elles utilisent principalement des “influenceurs” ou “influenceuses” du web, c.-à-d. des personnes très influentes sur les réseaux sociaux qui font du placement de produit à travers leurs vidéos ou leurs photos. Plus spécifiquement, nous voulons décrire le facteur d’augmentation des ventes de divers produits cosmétiques suite à une campagne publicitaire faisant appel à un nombre plus ou moins grands d’influenceurs ayant chacun au moins 20 000 abonnés sur ses plateformes. Le jeu de données est contenu dans le fichier <code>influenceurs.csv</code>.</p>
<div class="sourceCode" id="cb747"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb747-1"><a href="leçon-9.html#cb747-1" tabindex="-1"></a><span class="do">##on importe les données</span></span>
<span id="cb747-2"><a href="leçon-9.html#cb747-2" tabindex="-1"></a>influenceurs <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> <span class="st">&quot;Module_10/data/influenceurs.csv&quot;</span>, <span class="at">sep =</span> <span class="st">&#39;</span><span class="sc">\t</span><span class="st">&#39;</span>,</span>
<span id="cb747-3"><a href="leçon-9.html#cb747-3" tabindex="-1"></a>                      <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb747-4"><a href="leçon-9.html#cb747-4" tabindex="-1"></a><span class="fu">head</span>(influenceurs)</span></code></pre></div>
<pre><code>##   Nombre Facteur
## 1      3     1.4
## 2      4     3.1
## 3      5     2.2
## 4      6     2.4
## 5      8     3.6
## 6      9     3.2</code></pre>
<p>La figure <a href="leçon-9.html#fig:plotinf">10.1</a> illustre les données. On remarque déjà un patron linéaire et la droite de régression décrira formellement cette relation.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotinf"></span>
<img src="Cours_Stats_R_files/figure-html/plotinf-1.png" alt="Augmentation des ventes de divers produits cosmétiques en fonction du nombre d'influenceurs participant à la campagne publicitaire de ces nouveaux produits." width="672" />
<p class="caption">
Figure 10.1: Augmentation des ventes de divers produits cosmétiques en fonction du nombre d’influenceurs participant à la campagne publicitaire de ces nouveaux produits.
</p>
</div>
</div>
</div>
<div id="estimation" class="section level4 hasAnchor" number="10.1.1.2">
<h4><span class="header-section-number">10.1.1.2</span> Estimation<a href="leçon-9.html#estimation" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La régression linéaire minimise la somme des carrés des erreurs (<span class="math inline">\(SSE\)</span>)<a href="#fn28" class="footnote-ref" id="fnref28"><sup>28</sup></a> par la méthode des moindres carrés pour obtenir les estimations de l’ordonnée à l’origine et de la pente. Autrement dit, pour un jeu de données, l’équation de régression est l’équation qui donne la plus faible distance verticale entre chaque point (<span class="math inline">\(y_i\)</span>) et la droite de régression (<span class="math inline">\(\hat{y}_i\)</span>). Pour des problèmes plus complexes, comme la régression multiple que nous ne verrons pas dans le cours, les paramètres sont estimés à l’aide d’algèbre matricielle.</p>
<p>On peut calculer différentes sommes des carrés à partir des données de la régression linéaire, un peu comme nous l’avons effectué pour l’ANOVA. Les prochaines lignes montrent les sommes des carrés qui nous permettront d’obtenir les estimations des paramètres (variance résiduelle et coefficients de régression) à l’aide de la méthode des moindres carrés.</p>
<p>La somme des carrés des erreurs (<span class="math inline">\(SSE\)</span>) donne la somme des carrés de la déviation entre les valeurs observées de la variable dépendante (<span class="math inline">\(y_i\)</span>) et les valeurs prédites (<span class="math inline">\(\hat{y}_i\)</span>) par l’équation de régression :</p>
<p><span class="math display">\[  SSE = \sum_{i=1}^n (y_i - \hat{y_i})^2\]</span></p>
<p>La somme des carrés totale de <span class="math inline">\(Y\)</span> (<span class="math inline">\(SSY\)</span>) donne la somme des carrés de la déviation entre les valeurs observées de la variable dépendante (<span class="math inline">\(y_i\)</span>) et la moyenne de cette variable (<span class="math inline">\(\bar{y}\)</span>)</p>
<p><span class="math display">\[SSY = \sum_{i=1}^n (y_i - \bar{y})^2\]</span></p>
<p>La somme des carrés totale de <span class="math inline">\(X\)</span> (<span class="math inline">\(SSX\)</span>) donne la somme des carrés de la déviation entre les valeurs observées de la variable explicative (<span class="math inline">\(x_i\)</span>) et la moyenne de cette variable (<span class="math inline">\(\bar{x}\)</span>) :</p>
<p><span class="math display">\[SSX = \sum_{i=1}^n (x_i - \bar{x})^2\]</span></p>
<p>La somme des produits croisés (<span class="math inline">\(SSXY\)</span>, <em>sum of cross products</em>) donne la somme du produit des déviations entre la variable dépendante et sa moyenne et des déviations entre la variable explicative et sa moyenne :</p>
<p><span class="math display">\[SSXY = \sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})\]</span>
À partir de ces valeurs, nous pouvons obtenir la somme des carrés de la régression (<span class="math inline">\(SS_{\mathrm{r\acute{e}gression}}\)</span>) :</p>
<p><span class="math display">\[SS_{\mathrm{r\acute{e}gression}} = \frac{SSXY^2}{SSX}\]</span></p>
<p>La somme des carrés totale de <span class="math inline">\(Y\)</span> (<span class="math inline">\(SSY\)</span>), la somme des carrés de la régression (<span class="math inline">\(SS_{\mathrm{r\acute{e}gression}}\)</span>) et la somme des carrés des erreurs (<span class="math inline">\(SSE\)</span>) sont reliées par la relation suivante :</p>
<p><span class="math display">\[SSE = SSY - SS_{\mathrm{r\acute{e}gression}}\]</span></p>
<p>La pente (<span class="math inline">\(b\)</span>, <span class="math inline">\(\beta_{x}\)</span>) s’obtient :</p>
<p><span class="math display">\[\beta_{x} = \frac{SSXY}{SSX}\]</span>
Puisque la droite de régression passe par le point <span class="math inline">\(\bar{y}\)</span> et <span class="math inline">\(\bar{x}\)</span>, on peut trouver l’ordonnée à l’origine (<span class="math inline">\(a\)</span>, <span class="math inline">\(\beta_0\)</span>) :</p>
<p><span class="math display">\[\bar{y} = \beta_0 + \beta_{x}\bar{x} \]</span>
<span class="math display">\[\bar{y} - \beta_{x}\bar{x} = \beta_0 \]</span>
<span class="math display">\[\beta_0 = \bar{y} - \beta_{x}\bar{x} \]</span></p>
<p>Tout comme avec l’ANOVA, on peut estimer la variance résiduelle (<span class="math inline">\(\sigma^2\)</span>) à l’aide du carré moyen des erreurs (<span class="math inline">\(MSE\)</span>), où la variance résiduelle correspond à la partie de la variance des observations de <span class="math inline">\(y\)</span> qui n’est pas expliquée par <span class="math inline">\(x\)</span>:</p>
<p><span class="math display">\[MSE = \frac{SSE}{n - 2}\]</span></p>
<p>Appliquons maintenant ces calculs à l’exemple du placement de produits par des influenceurs.</p>
<div class="exemple" section="10">
<p>Nous allons estimer le facteur d’augmentation des ventes à partir des équations vues dans la section précédente.</p>
<p>La somme des carrés de <span class="math inline">\(Y\)</span> :</p>
<p><span class="math display">\[\begin{align*}
SSY &amp;= \sum_{i=1}^n (y_i - \bar{y})^2 \\
SSY &amp;= (1.4 - 3.4)^2 + \ldots + (4.5 - 3.4)^2 \\
SSY &amp;= 13
\end{align*}\]</span></p>
<p>La somme des carrés de <span class="math inline">\(X\)</span> :</p>
<p><span class="math display">\[\begin{align*}
SSX &amp;= \sum_{i=1}^n (x_i - \bar{x})^2 \\
SSX &amp;= (3 - 10)^2 + \ldots + (17 - 10)^2 \\
SSX &amp;= 262
\end{align*}\]</span></p>
<p>La somme des produits croisés :</p>
<p><span class="math display">\[\begin{align*}
SSXY &amp;= \sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y}) \\
SSXY &amp;= (1.4 - 3.4)(3 - 10) + \ldots \\
&amp;\quad + (4.5 - 3.4)(17 - 10) \\
SSXY &amp;= 51.1
\end{align*}\]</span></p>
<p>La somme des carrés de la régression :</p>
<p><span class="math display">\[\begin{align*}
SS_{\mathrm{r\acute{e}gression}} &amp;= \frac{SSXY^2}{SSX} \\
SS_{\mathrm{r\acute{e}gression}} &amp;= \frac{51.1^2}{262} \\
SS_{\mathrm{r\acute{e}gression}} &amp;= 10
\end{align*}\]</span></p>
<p>La somme des carrés des erreurs :</p>
<p><span class="math display">\[\begin{align*}
SSE &amp;= SSY - SS_{\mathrm{r\acute{e}gression}} \\
SSE &amp;= 13 - 10 \\
SSE &amp;= 3
\end{align*}\]</span></p>
<p>Nous pouvons ensuite calculer la pente de la droite de régression :</p>
<p><span class="math display">\[\begin{align*}
\beta_x &amp;= \frac{SSXY}{SSX} \\
\beta_x &amp;= \frac{51.1}{262} \\
\beta_x &amp;= 0.2
\end{align*}\]</span></p>
<p>L’ordonnée à l’origine s’obtient comme suit :</p>
<p><span class="math display">\[\begin{align*}
\beta_0 &amp;= \bar{y} - \beta_x \bar{x} \\
\beta_0 &amp;= 3.4 - 0.2 \times 10 \\
\beta_0 &amp;= 1.5
\end{align*}\]</span></p>
<p>Et la variance résiduelle est donnée par :</p>
<p><span class="math display">\[\begin{align*}
MSE &amp;= \frac{SSE}{n - 2} \\
MSE &amp;= \frac{3.1}{13 - 2} \\
MSE &amp;= 0.3
\end{align*}\]</span></p>
<p>Nous pouvons réaliser rapidement tous ces calculs en appliquant les formules dans R ou encore en utilisant directement la fonction <code>lm( )</code> :</p>
<div class="sourceCode" id="cb749"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb749-1"><a href="leçon-9.html#cb749-1" tabindex="-1"></a><span class="do">##on crée des objets pour stocker chaque variable</span></span>
<span id="cb749-2"><a href="leçon-9.html#cb749-2" tabindex="-1"></a>nombre <span class="ot">&lt;-</span> influenceurs<span class="sc">$</span>Nombre</span>
<span id="cb749-3"><a href="leçon-9.html#cb749-3" tabindex="-1"></a>facteur <span class="ot">&lt;-</span> influenceurs<span class="sc">$</span>Facteur</span>
<span id="cb749-4"><a href="leçon-9.html#cb749-4" tabindex="-1"></a><span class="do">##SSY</span></span>
<span id="cb749-5"><a href="leçon-9.html#cb749-5" tabindex="-1"></a>SSY <span class="ot">&lt;-</span> <span class="fu">sum</span>((facteur <span class="sc">-</span> <span class="fu">mean</span>(facteur))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb749-6"><a href="leçon-9.html#cb749-6" tabindex="-1"></a>SSY</span></code></pre></div>
<pre><code>## [1] 13.04769</code></pre>
<div class="sourceCode" id="cb751"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb751-1"><a href="leçon-9.html#cb751-1" tabindex="-1"></a><span class="do">##SSX</span></span>
<span id="cb751-2"><a href="leçon-9.html#cb751-2" tabindex="-1"></a>SSX <span class="ot">&lt;-</span> <span class="fu">sum</span>((nombre <span class="sc">-</span> <span class="fu">mean</span>(nombre))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb751-3"><a href="leçon-9.html#cb751-3" tabindex="-1"></a>SSX</span></code></pre></div>
<pre><code>## [1] 262</code></pre>
<div class="sourceCode" id="cb753"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb753-1"><a href="leçon-9.html#cb753-1" tabindex="-1"></a><span class="do">##SSXY</span></span>
<span id="cb753-2"><a href="leçon-9.html#cb753-2" tabindex="-1"></a>SSXY <span class="ot">&lt;-</span> <span class="fu">sum</span>((facteur <span class="sc">-</span> <span class="fu">mean</span>(facteur)) <span class="sc">*</span> (nombre <span class="sc">-</span> <span class="fu">mean</span>(nombre)))</span>
<span id="cb753-3"><a href="leçon-9.html#cb753-3" tabindex="-1"></a>SSXY</span></code></pre></div>
<pre><code>## [1] 51.1</code></pre>
<div class="sourceCode" id="cb755"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb755-1"><a href="leçon-9.html#cb755-1" tabindex="-1"></a><span class="do">##SSReg</span></span>
<span id="cb755-2"><a href="leçon-9.html#cb755-2" tabindex="-1"></a>SSReg <span class="ot">&lt;-</span> (SSXY<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>SSX</span>
<span id="cb755-3"><a href="leçon-9.html#cb755-3" tabindex="-1"></a>SSReg</span></code></pre></div>
<pre><code>## [1] 9.96645</code></pre>
<div class="sourceCode" id="cb757"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb757-1"><a href="leçon-9.html#cb757-1" tabindex="-1"></a><span class="do">##SSE</span></span>
<span id="cb757-2"><a href="leçon-9.html#cb757-2" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SSY <span class="sc">-</span> SSReg</span>
<span id="cb757-3"><a href="leçon-9.html#cb757-3" tabindex="-1"></a>SSE</span></code></pre></div>
<pre><code>## [1] 3.081242</code></pre>
<div class="sourceCode" id="cb759"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb759-1"><a href="leçon-9.html#cb759-1" tabindex="-1"></a><span class="do">##pente</span></span>
<span id="cb759-2"><a href="leçon-9.html#cb759-2" tabindex="-1"></a>beta.x <span class="ot">&lt;-</span> SSXY<span class="sc">/</span>SSX</span>
<span id="cb759-3"><a href="leçon-9.html#cb759-3" tabindex="-1"></a>beta.x</span></code></pre></div>
<pre><code>## [1] 0.1950382</code></pre>
<div class="sourceCode" id="cb761"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb761-1"><a href="leçon-9.html#cb761-1" tabindex="-1"></a><span class="do">##ordonnée à l&#39;origine</span></span>
<span id="cb761-2"><a href="leçon-9.html#cb761-2" tabindex="-1"></a>beta<span class="fl">.0</span> <span class="ot">&lt;-</span> <span class="fu">mean</span>(facteur) <span class="sc">-</span> beta.x <span class="sc">*</span> <span class="fu">mean</span>(nombre)</span>
<span id="cb761-3"><a href="leçon-9.html#cb761-3" tabindex="-1"></a>beta<span class="fl">.0</span></span></code></pre></div>
<pre><code>## [1] 1.480388</code></pre>
<div class="sourceCode" id="cb763"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb763-1"><a href="leçon-9.html#cb763-1" tabindex="-1"></a><span class="do">##variance résiduelle</span></span>
<span id="cb763-2"><a href="leçon-9.html#cb763-2" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE<span class="sc">/</span>(<span class="fu">length</span>(facteur) <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb763-3"><a href="leçon-9.html#cb763-3" tabindex="-1"></a>MSE</span></code></pre></div>
<pre><code>## [1] 0.2801129</code></pre>
<div class="sourceCode" id="cb765"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb765-1"><a href="leçon-9.html#cb765-1" tabindex="-1"></a><span class="do">##régression linéaire avec lm( )</span></span>
<span id="cb765-2"><a href="leçon-9.html#cb765-2" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Facteur <span class="sc">~</span> Nombre, <span class="at">data =</span> influenceurs)</span>
<span id="cb765-3"><a href="leçon-9.html#cb765-3" tabindex="-1"></a>m1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Facteur ~ Nombre, data = influenceurs)
## 
## Coefficients:
## (Intercept)       Nombre  
##       1.480        0.195</code></pre>
<div class="sourceCode" id="cb767"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb767-1"><a href="leçon-9.html#cb767-1" tabindex="-1"></a><span class="do">##SSE à partir des valeurs prédites</span></span>
<span id="cb767-2"><a href="leçon-9.html#cb767-2" tabindex="-1"></a><span class="do">##fitted() utilise l&#39;objet m1 (résultat du modèle) </span></span>
<span id="cb767-3"><a href="leçon-9.html#cb767-3" tabindex="-1"></a><span class="do">##et retourne les valeurs prédites pour chaque </span></span>
<span id="cb767-4"><a href="leçon-9.html#cb767-4" tabindex="-1"></a><span class="do">##ligne  du jeu de données influenceurs</span></span>
<span id="cb767-5"><a href="leçon-9.html#cb767-5" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>((facteur <span class="sc">-</span> <span class="fu">fitted</span>(m1))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb767-6"><a href="leçon-9.html#cb767-6" tabindex="-1"></a>SSE</span></code></pre></div>
<pre><code>## [1] 3.081242</code></pre>
<p>En assemblant les coefficients de régression, nous obtenons l’équation de régression linéaire suivante:
<span class="math display">\[y_i = \beta_0 + \beta_xx_i + \epsilon_i\]</span>
<span class="math display">\[y_i = 1.5 + 0.2Nombre_i + \epsilon_i\]</span></p>
<p>À noter que les valeurs prédites (<span class="math inline">\(\hat{y}_i\)</span>) sont obtenues avec <span class="math inline">\(1.5 + 0.2Nombre_i\)</span>. Par exemple, nous avons observé un facteur d’augmentation des ventes de 1.5 avec 3 influenceurs participant à une campagne publicitaire. Nous pouvons calculer le facteur d’augmentation prédit par la régression (c.-à-d., <span class="math inline">\(\hat{y}_i\)</span> avec 3 influenceurs) :</p>
<p><span class="math display">\[\hat{y}_1 = 1.5 + 0.2 \cdot 3 \\
  = 2.1 \]</span></p>
<p>On peut procéder de la même façon pour calculer les autres valeurs prédites. Finalement, on ajoute la droite de régression sur le graphique présentant le facteur d’augmentation des ventes en fonction du nombre d’influenceurs (Figure <a href="leçon-9.html#fig:lineinf">10.2</a>a).</p>
<div class="sourceCode" id="cb769"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb769-1"><a href="leçon-9.html#cb769-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb769-2"><a href="leçon-9.html#cb769-2" tabindex="-1"></a><span class="do">##graphique 1</span></span>
<span id="cb769-3"><a href="leçon-9.html#cb769-3" tabindex="-1"></a><span class="fu">plot</span>(influenceurs<span class="sc">$</span>Facteur <span class="sc">~</span> influenceurs<span class="sc">$</span>Nombre,</span>
<span id="cb769-4"><a href="leçon-9.html#cb769-4" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Facteur d&#39;augmentation des ventes&quot;</span>,</span>
<span id="cb769-5"><a href="leçon-9.html#cb769-5" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Nombre d&#39;influenceurs&quot;</span>)</span>
<span id="cb769-6"><a href="leçon-9.html#cb769-6" tabindex="-1"></a><span class="do">##ajout de la droite de régression</span></span>
<span id="cb769-7"><a href="leçon-9.html#cb769-7" tabindex="-1"></a><span class="fu">abline</span>(m1)</span>
<span id="cb769-8"><a href="leçon-9.html#cb769-8" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="dv">5</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>)</span>
<span id="cb769-9"><a href="leçon-9.html#cb769-9" tabindex="-1"></a></span>
<span id="cb769-10"><a href="leçon-9.html#cb769-10" tabindex="-1"></a><span class="do">##graphique 2</span></span>
<span id="cb769-11"><a href="leçon-9.html#cb769-11" tabindex="-1"></a><span class="fu">plot</span>(influenceurs<span class="sc">$</span>Facteur <span class="sc">~</span> influenceurs<span class="sc">$</span>Nombre,</span>
<span id="cb769-12"><a href="leçon-9.html#cb769-12" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Facteur d&#39;augmentation des ventes&quot;</span>,</span>
<span id="cb769-13"><a href="leçon-9.html#cb769-13" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Nombre d&#39;influenceurs&quot;</span>)</span>
<span id="cb769-14"><a href="leçon-9.html#cb769-14" tabindex="-1"></a><span class="fu">abline</span>(m1)</span>
<span id="cb769-15"><a href="leçon-9.html#cb769-15" tabindex="-1"></a><span class="fu">segments</span>(<span class="at">x0 =</span> nombre, <span class="at">y0 =</span> facteur, <span class="at">x1 =</span> nombre, <span class="at">y1 =</span> <span class="fu">fitted</span>(m1), <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb769-16"><a href="leçon-9.html#cb769-16" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="dv">5</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:lineinf"></span>
<img src="Cours_Stats_R_files/figure-html/lineinf-1.png" alt="Droite de régression linéaire du facteur d'augmentation des ventes en fonction du nombre d'influenceurs (a) et distance entre les observations ($y_i$) et la valeur prédite correspondante ($\hat{y_i}$) (b)." width="672" />
<p class="caption">
Figure 10.2: Droite de régression linéaire du facteur d’augmentation des ventes en fonction du nombre d’influenceurs (a) et distance entre les observations (<span class="math inline">\(y_i\)</span>) et la valeur prédite correspondante (<span class="math inline">\(\hat{y_i}\)</span>) (b).
</p>
</div>
<p>Puisque les erreurs (<span class="math inline">\(\epsilon_i\)</span>) correspondent aux résidus, on peut réécrire:</p>
<p><span class="math display">\[y_i = \hat{y_i} + \epsilon_i\]</span>
<span class="math display">\[y_i - \hat{y_i} = \epsilon_i \]</span>
<span class="math display">\[\epsilon_i = y_i - \hat{y_i}\]</span></p>
<p>La droite de régression minimise la somme des carrés des erreurs qui dépend directement de la distance (verticale) entre chaque <span class="math inline">\(y_i\)</span> et sa valeur prédite <span class="math inline">\(\hat{y_i}\)</span> correspondante (Figure <a href="leçon-9.html#fig:lineinf">10.2</a>b). Dans R, on peut extraire les résidus du modèle de régression à l’aide de la fonction <code>residuals( )</code> en fournissant comme argument l’objet qui contient le résultat du modèle (c.-à-d., m1 dans notre exemple), alors que la fonction <code>fitted( )</code> extrait les valeurs prédites du modèle. Nous utiliserons ces deux éléments pour vérifier les suppositions de la régression linéaire.</p>
</div>
</div>
<div id="suppositions-4" class="section level4 hasAnchor" number="10.1.1.3">
<h4><span class="header-section-number">10.1.1.3</span> Suppositions<a href="leçon-9.html#suppositions-4" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>La régression linéaire comporte les suppositions suivantes :</p>
<ol style="list-style-type: decimal">
<li><strong>existence:</strong> à chaque valeur de <span class="math inline">\(x\)</span>, il existe une distribution de valeurs de <span class="math inline">\(y\)</span> dans la population. Cette supposition ne peut être vérifiée formellement, mais implique qu’il y a une série de valeurs de <span class="math inline">\(y\)</span> possibles à chaque valeur de <span class="math inline">\(x\)</span>;</li>
<li><strong>normalité:</strong> les erreurs proviennent d’une distribution normale. Cette supposition peut être vérifiée à l’aide d’un graphique quantile-quantile à partir des résidus;</li>
<li><strong>homoscédasticité:</strong> la variance de <span class="math inline">\(y\)</span> (et des erreurs) est la même pour chaque <span class="math inline">\(x\)</span>. Le graphique des résidus en fonction des valeurs prédites permet de diagnostiquer des problèmes associés à l’hétérogénéité de la variance;</li>
<li><strong>indépendance:</strong> es valeurs de <span class="math inline">\(y\)</span> (et les erreurs) sont indépendantes les unes des autres. L’échantillonnage aléatoire des observations assure l’indépendance des observations et des erreurs;</li>
<li><strong>linéarité:</strong> la relation entre <span class="math inline">\(y\)</span> et <span class="math inline">\(x\)</span> est linéaire. La régression linéaire implique une relation linéaire: un graphique des valeurs observées (<span class="math inline">\(y\)</span>) en fonction de la variable explicative (<span class="math inline">\(x\)</span>) permet de vérifier la plausibilité de cette supposition. Si la relation n’a pas une forme linéaire (une relation exponentielle par exemple), on peut considérer une transformation afin de linéariser la relation<a href="#fn29" class="footnote-ref" id="fnref29"><sup>29</sup></a>.</li>
<li><strong>mesure de <span class="math inline">\(x\)</span> sans erreur:</strong> les valeurs de <span class="math inline">\(x\)</span> sont mesurées sans erreur. Un assouplissement de cette supposition consiste à supposer que l’erreur sur <span class="math inline">\(x\)</span> est très faible par rapport à l’erreur de mesure de <span class="math inline">\(y\)</span>. La prévention et la rigueur dans la prise de mesure permet de satisfaire à cette condition.</li>
</ol>
<div class="exemple" section="10">
<p>Poursuivons le développement de l’exemple sur l’augmentation des ventes suite à une campagne publicitaire avec des influenceurs du web en vérifiant les suppositions pour la régression linéaire. Nous pouvons vérifier l’homogénéité des variances et la normalité à l’aide des mêmes outils que pour l’ANOVA.</p>
<div class="sourceCode" id="cb770"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb770-1"><a href="leçon-9.html#cb770-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb770-2"><a href="leçon-9.html#cb770-2" tabindex="-1"></a><span class="do">##homogénéité de la variance</span></span>
<span id="cb770-3"><a href="leçon-9.html#cb770-3" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">residuals</span>(m1) <span class="sc">~</span> <span class="fu">fitted</span>(m1), <span class="at">ylab =</span> <span class="st">&quot;Résidus&quot;</span>,</span>
<span id="cb770-4"><a href="leçon-9.html#cb770-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>, </span>
<span id="cb770-5"><a href="leçon-9.html#cb770-5" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Homogénéité des variances&quot;</span>, <span class="at">cex.main =</span> <span class="dv">1</span>)</span>
<span id="cb770-6"><a href="leçon-9.html#cb770-6" tabindex="-1"></a><span class="do">##normalité</span></span>
<span id="cb770-7"><a href="leçon-9.html#cb770-7" tabindex="-1"></a><span class="fu">text</span>(<span class="st">&quot;a&quot;</span>, <span class="at">x=</span> <span class="fl">2.3</span>, <span class="at">y =</span> <span class="fl">0.7</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb770-8"><a href="leçon-9.html#cb770-8" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(m1), <span class="at">ylab =</span> <span class="st">&quot;Quantiles observés&quot;</span>,</span>
<span id="cb770-9"><a href="leçon-9.html#cb770-9" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;Quantiles théoriques&quot;</span>,</span>
<span id="cb770-10"><a href="leçon-9.html#cb770-10" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Normalité des résidus&quot;</span>, <span class="at">cex.main =</span> <span class="dv">1</span>)</span>
<span id="cb770-11"><a href="leçon-9.html#cb770-11" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(m1))</span>
<span id="cb770-12"><a href="leçon-9.html#cb770-12" tabindex="-1"></a><span class="fu">text</span>(<span class="st">&quot;b&quot;</span>, <span class="at">x=</span> <span class="sc">-</span><span class="fl">1.4</span>, <span class="at">y =</span> <span class="fl">0.7</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotdiaginf"></span>
<img src="Cours_Stats_R_files/figure-html/plotdiaginf-1.png" alt="Homogénéité des variances (a) et normalité des résidus (b) obtenus à partir de la droite de régression linéaire du facteur d'augmentation des ventes en fonction du nombre d'influenceurs faisant campagne pour le produit." width="672" />
<p class="caption">
Figure 10.3: Homogénéité des variances (a) et normalité des résidus (b) obtenus à partir de la droite de régression linéaire du facteur d’augmentation des ventes en fonction du nombre d’influenceurs faisant campagne pour le produit.
</p>
</div>
<p>La figure <a href="leçon-9.html#fig:plotdiaginf">10.3</a>a montre que les variances sont homogènes. Comme pour l’ANOVA, la suppositon d’homogénéité des variances doit être respectée. Bien que quelques résidus dévient de la normalité (<a href="leçon-9.html#fig:plotdiaginf">10.3</a>b), la régression linéaire est appropriée. Nous pouvons procéder à l’interprétation de la régression.</p>
</div>
</div>
<div id="valeurs-extrêmes" class="section level4 hasAnchor" number="10.1.1.4">
<h4><span class="header-section-number">10.1.1.4</span> Valeurs extrêmes<a href="leçon-9.html#valeurs-extr%C3%AAmes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Une observation qui se démarque du reste des observations est une observation <strong>extrême</strong> (<em>outlier</em>). Cette caractéristique d’une observation peut entraîner des problèmes d’estimation. La présence d’une valeur extrême dans une variable peut fortement influencer la moyenne arithmétique de cette même variable. Par exemple, dans un vecteur avec les 5 valeurs suivantes <span class="math inline">\(0.1, 0.1, 0.2, 0.2, 0.3\)</span>, nous obtenons une moyenne arithmétique de 0.18. Si on remplace la valeur de 0.3 par 30, la moyenne deviendra 6.12 et très différente de la moyenne originale. Le même phénomène se produit avec la régression.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:leverage"></span>
<img src="Cours_Stats_R_files/figure-html/leverage-1.png" alt="Régression sans valeur extrême (a) où la pente est de `0.195` et (b) régression avec les mêmes données sauf pour une observation extrême identifiée en bleu ($x$ = 1, $y$ = 5) qui modifie la pente à la valeur `-0.021`." width="672" />
<p class="caption">
Figure 10.4: Régression sans valeur extrême (a) où la pente est de <code>0.195</code> et (b) régression avec les mêmes données sauf pour une observation extrême identifiée en bleu (<span class="math inline">\(x\)</span> = 1, <span class="math inline">\(y\)</span> = 5) qui modifie la pente à la valeur <code>-0.021</code>.
</p>
</div>
<div id="résidus-de-student" class="section level5 hasAnchor" number="10.1.1.4.1">
<h5><span class="header-section-number">10.1.1.4.1</span> Résidus de Student<a href="leçon-9.html#r%C3%A9sidus-de-student" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Les résidus de Student (<em>Student residuals</em>) permettent d’identifier des valeurs extrêmes dans une régression. Pour ce faire, chaque observation est comparée aux autres au moyen d’une variable binaire qui prend la valeur de 1 pour coder cette observation et de 0 pour les autres valeurs. Cette nouvelle variable est ajoutée à la régression et le test <span class="math inline">\(t\)</span> associé à ce coefficient donne le résidu de Student pour cette observation. La fonction <code>rstudent( )</code> extrait directement ces valeurs. Le code ci-dessous montre l’extraction des résidus de Student pour les deux premières observations.</p>
<div class="sourceCode" id="cb771"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb771-1"><a href="leçon-9.html#cb771-1" tabindex="-1"></a><span class="do">##on crée une variable binaire pour obs1</span></span>
<span id="cb771-2"><a href="leçon-9.html#cb771-2" tabindex="-1"></a>influenceurs<span class="sc">$</span>obs1 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">rownames</span>(influenceurs) <span class="sc">==</span> <span class="st">&quot;1&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb771-3"><a href="leçon-9.html#cb771-3" tabindex="-1"></a><span class="do">##on crée une variable binaire pour obs2</span></span>
<span id="cb771-4"><a href="leçon-9.html#cb771-4" tabindex="-1"></a>influenceurs<span class="sc">$</span>obs2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">rownames</span>(influenceurs) <span class="sc">==</span> <span class="st">&quot;2&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb771-5"><a href="leçon-9.html#cb771-5" tabindex="-1"></a><span class="do">##on ajoute cette variable à la régression</span></span>
<span id="cb771-6"><a href="leçon-9.html#cb771-6" tabindex="-1"></a>m1.obs1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Facteur <span class="sc">~</span> Nombre <span class="sc">+</span> obs1, <span class="at">data =</span> influenceurs)</span>
<span id="cb771-7"><a href="leçon-9.html#cb771-7" tabindex="-1"></a>m1.obs2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Facteur <span class="sc">~</span> Nombre <span class="sc">+</span> obs2, <span class="at">data =</span> influenceurs)</span>
<span id="cb771-8"><a href="leçon-9.html#cb771-8" tabindex="-1"></a><span class="fu">summary</span>(m1.obs1)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)  1.7915038  0.3919162  4.571140 0.0010244634
## Nombre       0.1708815  0.0344507  4.960176 0.0005698837
## obs1        -0.9041484  0.5804032 -1.557794 0.1503394339</code></pre>
<div class="sourceCode" id="cb773"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb773-1"><a href="leçon-9.html#cb773-1" tabindex="-1"></a><span class="fu">summary</span>(m1.obs2)<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##              Estimate Std. Error  t value     Pr(&gt;|t|)
## (Intercept) 1.1535127 0.35523771 3.247157 8.762565e-03
## Nombre      0.2195067 0.03129716 7.013631 3.655048e-05
## obs2        1.0684604 0.52727435 2.026384 7.022757e-02</code></pre>
<div class="sourceCode" id="cb775"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb775-1"><a href="leçon-9.html#cb775-1" tabindex="-1"></a><span class="do">##extraction des deux premiers résidus de Student du modèle m1</span></span>
<span id="cb775-2"><a href="leçon-9.html#cb775-2" tabindex="-1"></a><span class="fu">rstudent</span>(m1)[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>##         1         2 
## -1.557794  2.026384</code></pre>
<div class="sourceCode" id="cb777"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb777-1"><a href="leçon-9.html#cb777-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstudent</span>(m1) <span class="sc">~</span> <span class="fu">fitted</span>(m1), </span>
<span id="cb777-2"><a href="leçon-9.html#cb777-2" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Résidus de Student&quot;</span>, </span>
<span id="cb777-3"><a href="leçon-9.html#cb777-3" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:rstudinf"></span>
<img src="Cours_Stats_R_files/figure-html/rstudinf-1.png" alt="Résidus de Student en fonction des valeurs prédites de la régression de l'augmentation des ventes en fonction du nombre d'influenceurs du web participant à la campagne publicitaire." width="672" />
<p class="caption">
Figure 10.5: Résidus de Student en fonction des valeurs prédites de la régression de l’augmentation des ventes en fonction du nombre d’influenceurs du web participant à la campagne publicitaire.
</p>
</div>
<p>Puisque les résidus de Student sont sur l’échelle du <span class="math inline">\(t\)</span> de Student, des valeurs supérieures à 4 ou inférieures à -4 indiquent des valeurs qui se démarquent nettement des autres (voir la leçon 2). On peut visualiser rapidement les résidus de Student en fonction des valeurs prédites (fig. <a href="leçon-9.html#fig:rstudinf">10.5</a>).</p>
</div>
</div>
<div id="tests-dhypothèses" class="section level4 hasAnchor" number="10.1.1.5">
<h4><span class="header-section-number">10.1.1.5</span> Tests d’hypothèses<a href="leçon-9.html#tests-dhypoth%C3%A8ses" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Nous pouvons tester une série d’hypothèses statistiques à partir de la régression linéaire, notamment des tests d’hypothèses sur les coefficients ainsi que sur la régression. La fonction <code>summary( )</code> permet d’obtenir un bref résumé de l’analyse et le résultat de ces tests d’hypothèses. Nous utilisons cette fonction afin d’aller chercher le résumé de l’analyse réalisée plus tôt sur l’augmentation des ventes suite à du placement de produit fait par des influenceurs sur le web :</p>
<div class="sourceCode" id="cb778"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb778-1"><a href="leçon-9.html#cb778-1" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Facteur ~ Nombre, data = influenceurs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.91092 -0.25558 -0.03573  0.27915  0.83946 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.4804     0.3584   4.130  0.00167 ** 
## Nombre        0.1950     0.0327   5.965 9.39e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5293 on 11 degrees of freedom
## Multiple R-squared:  0.7638, Adjusted R-squared:  0.7424 
## F-statistic: 35.58 on 1 and 11 DF,  p-value: 9.388e-05</code></pre>
<p>Nous remarquons différents éléments dans les résultats de <code>summary( )</code>, incluant l’appel à la fonction (<code>Call:</code>), les quantiles des résidus (<code>Residuals</code>), suivi des coefficients de la régression (<code>Coefficients</code>). Pour chaque coefficient de régression, on retrouve quatre colonnes. La première colonne présente l’estimation (<code>Estimate</code>) et la deuxième donne l’erreur-type de l’estimation (<code>Std. Error</code>). La troisième colonne correspond à un test d’hypothèse sur l’estimation, à savoir, si sa valeur diffère significativement de 0 (<span class="math inline">\(H_0: \beta = 0\)</span>). Cette hypothèse est testée à l’aide d’un test <span class="math inline">\(t\)</span> de Wald, un test qui est formé de l’estimation divisée par son erreur-type (<span class="math inline">\(t \: \mathrm{de} \: \mathrm{Wald} = \frac{\beta}{SE_{\beta}}\)</span>). La quatrième colonne correspond à la probabilité cumulative associée à un test <span class="math inline">\(t\)</span> pour l’hypothèse nulle sur l’estimation et aux degrés de liberté résiduels du modèle (<span class="math inline">\(P(t_{df} \geq |t_{obs, df}|)\)</span>). À noter qu’on teste rarement si l’ordonnée à l’origine diffère de 0 (1ère rangée), puisque l’ordonnée à l’origine diffère la plupart du temps de 0 (2e rangée). C’est pourquoi on se limite généralement à tester la pente.</p>
<p>La dernière portion des résultats indique l’erreur-type résiduelle (<span class="math inline">\(\sqrt{MSE}\)</span>), les degrés de liberté résiduels du modèle de régression, ainsi le coefficient de détermination (<span class="math inline">\(R^2\)</span>) qui est une mesure de la force de la régression que nous verrons dans la prochaine section. La dernière ligne nous présente le <span class="math inline">\(F\)</span> sur l’ANOVA de la régression et la probabilité cumulative de cette statistique. Ce test détermine si globalement la portion de la variance expliquée par la variable explicative est supérieure à la portion inexpliquée (variance résiduelle, <span class="math inline">\(MSE\)</span>). %Ce test amène peu d’information additionnelle pour la régression linéaire simple, puisque le test-<span class="math inline">\(t\)</span> de Wald nous informe rapidement de l’importance du coefficient. C’est avec la régression multiple que ce résultat amène le plus d’information.</p>
<!-- CODE NON INCLUS DANS LE PDF MAIS DANS LE RNW -->
<p>Une alternative aux tests d’hypothèses classiques s’avère l’usage d’intervalles de confiance afin d’évaluer l’effet de l’estimation de la pente. La construction d’un intervalle de confiance autour d’une estimation est similaire à celle autour d’une moyenne d’un échantillon. On calculera l’intervalle de confiance à <span class="math inline">\(1 - \alpha \: \%\)</span> comme suit :</p>
<p><span class="math display">\[IC \: \text{à} \: 1 - \alpha \: \%: \\
  P(\beta_{x} - t_{\alpha/2, \: \mathrm{degr\acute{e}s \: de \: libert\acute{e} \: r\acute{e}siduels}} \cdot SE_{\beta_x} \leq \mu \leq \beta_{x} + t_{\alpha/2, \: \mathrm{degr\acute{e}s \: de \: libert\acute{e} \: r\acute{e}siduels}} \cdot SE_{\beta_x}) = (1 - \alpha)\]</span></p>
<p>où <span class="math inline">\(\beta_x\)</span> représente l’estimation de la pente, <span class="math inline">\(SE_{\beta_x}\)</span> donne la précision de cette estimation et <span class="math inline">\(t_{\alpha/2, \: \mathrm{degr\acute{e}s \: de \: libert\acute{e} \: r\acute{e}siduels}}\)</span> correspond à la statistique du <span class="math inline">\(t\)</span> de Student associée à la portion <span class="math inline">\(\alpha/2\)</span> % de la courbe et aux degrés de libertés résiduels. Ainsi, si l’intervalle de confiance exclut 0, nous déclarerons que l’estimation du coefficient diffère de 0. En poursuivant l’exemple de régression linéaire l’augmentation des ventes de produits avec une campagne publicitaire d’influenceurs du web, nous obtenons un intervalle de confiance à 95 % autour de la pente de <span class="math inline">\([-0.264, -1.486]\)</span> et nous concluons que l’estimation diffère de 0.</p>
<div class="sourceCode" id="cb780"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb780-1"><a href="leçon-9.html#cb780-1" tabindex="-1"></a><span class="do">##extraction de pente</span></span>
<span id="cb780-2"><a href="leçon-9.html#cb780-2" tabindex="-1"></a>pente <span class="ot">&lt;-</span> <span class="fu">coef</span>(m1)[<span class="dv">2</span>]</span>
<span id="cb780-3"><a href="leçon-9.html#cb780-3" tabindex="-1"></a><span class="do">##extraction de SE de la pente</span></span>
<span id="cb780-4"><a href="leçon-9.html#cb780-4" tabindex="-1"></a><span class="do">##à partir du summary() du modèle m1</span></span>
<span id="cb780-5"><a href="leçon-9.html#cb780-5" tabindex="-1"></a>SE.pente <span class="ot">&lt;-</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>coefficient[<span class="dv">2</span>,<span class="dv">2</span>]</span>
<span id="cb780-6"><a href="leçon-9.html#cb780-6" tabindex="-1"></a></span>
<span id="cb780-7"><a href="leçon-9.html#cb780-7" tabindex="-1"></a><span class="do">##df résiduels</span></span>
<span id="cb780-8"><a href="leçon-9.html#cb780-8" tabindex="-1"></a>df.res <span class="ot">&lt;-</span> m1<span class="sc">$</span>df.residual</span>
<span id="cb780-9"><a href="leçon-9.html#cb780-9" tabindex="-1"></a><span class="do">##limites de IC</span></span>
<span id="cb780-10"><a href="leçon-9.html#cb780-10" tabindex="-1"></a>inf95 <span class="ot">&lt;-</span> pente <span class="sc">+</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> df.res) <span class="sc">*</span> SE.pente</span>
<span id="cb780-11"><a href="leçon-9.html#cb780-11" tabindex="-1"></a>sup95 <span class="ot">&lt;-</span> pente <span class="sc">-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> df.res) <span class="sc">*</span> SE.pente</span>
<span id="cb780-12"><a href="leçon-9.html#cb780-12" tabindex="-1"></a><span class="do">##IC</span></span>
<span id="cb780-13"><a href="leçon-9.html#cb780-13" tabindex="-1"></a><span class="fu">c</span>(inf95, sup95)</span></code></pre></div>
<pre><code>##    Nombre    Nombre 
## 0.1230712 0.2670051</code></pre>
</div>
<div id="évaluer-le-pouvoir-prédictif" class="section level4 hasAnchor" number="10.1.1.6">
<h4><span class="header-section-number">10.1.1.6</span> Évaluer le pouvoir prédictif<a href="leçon-9.html#%C3%A9valuer-le-pouvoir-pr%C3%A9dictif" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le <strong>coefficient de détermination</strong> ou <span class="math inline">\(\boldsymbol{R^2}\)</span> est une mesure de la force de la régression. Elle indique si les observations sont près de la droite de régression. Le coefficient de détermination peut prendre des valeurs entre 0 (la régression n’explique aucune partie de la variance de <span class="math inline">\(y\)</span>) et 1 (la régression explique complètement la variance de <span class="math inline">\(y\)</span>). En multipliant le coefficient de détermination par 100, on peut l’interpréter comme un pourcentage de variance de la variable réponse (<span class="math inline">\(y\)</span>) expliquée par la variable explicative (<span class="math inline">\(x\)</span>). Le coefficient de détermination peut se calculer:</p>
<p><span class="math display">\[ R^2 = \frac{SSReg}{SSY}\]</span></p>
<p>où <span class="math inline">\(SSReg\)</span> correspond à la somme des carrés de la régression et <span class="math inline">\(SSY\)</span> correspond à la somme des carrés totale de <span class="math inline">\(y\)</span>. Le <span class="math inline">\(R^2\)</span> donne la fraction de la variance totale de <span class="math inline">\(y\)</span> expliquée par la régression. Pour l’exemple sur l’augmentation des ventes suite à une campagne publicitaire, nous obtenons <span class="math inline">\(R^2 = \frac{9.97}{13.05} = 0.76\)</span>. Nous pourrons conclure que 76 % de la variabilité de <span class="math inline">\(y\)</span> est expliquée par la régression, ce qui est très élevé. Avec certains jeux de données en sciences, nous nous réjouissons souvent d’avoir un <span class="math inline">\(R^2\)</span> de 0.30.</p>
<p>Bien que les tests d’hypothèses puissent être informatifs, il faut être conscient que dans certains cas, le rejet d’une hypothèse nulle n’entraîne pas nécessairement un résultat significatif du point de vue pratique. Avec un nombre d’observations suffisamment élevé, on peut rejeter pratiquement n’importe quelle hypothèse nulle statistique. C’est pourquoi l’utilisation de mesures de précision autour de la pente, telles que l’erreur-type ou l’intervalle de confiance, permettent de nous aider à évaluer la relation. Le coefficient de détermination aide à conclure sur la force de la relation et de la distance des points par rapport à la droite de régression – même avec un <span class="math inline">\(P &lt; 0.0001\)</span>, il est possible d’avoir un <span class="math inline">\(R^2\)</span> très près de 0. Le cas échéant, nous modulerons notre interprétation des résultats.</p>
</div>
<div id="prédiction" class="section level4 hasAnchor" number="10.1.1.7">
<h4><span class="header-section-number">10.1.1.7</span> Prédiction<a href="leçon-9.html#pr%C3%A9diction" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Un des objectifs de la régression linéaire est souvent de faire des prédictions. Pour ce faire, nous pouvons utiliser l’équation de régression et substituer la valeur de <span class="math inline">\(x\)</span> pour laquelle nous désirons une valeur prédite. Dans l’exemple sur l’augmentation des ventes en fonction du nombre d’influenceurs, l’équation de la droite de régression est :</p>
<p><span class="math display">\[\hat{y_i} = \beta_0 + \beta_xx_i  
  \hat{y_i} = 1.5 + 0.2 \cdot Nombre_i\]</span></p>
<p>Il est possible de faire des prédictions à l’intérieur de l’étendue des valeurs de la variable explicative. Ici, le nombre d’influenceurs promouvant un même produit varie de 3 à 17. En d’autres mots, on ne peut pas prédire le facteur d’augmentation des ventes pour un nombre d’influenceurs du web moindre que 3 ou plus grand que 17. Si nous voulons obtenir le facteur d’augmentation des ventes d’un campagne ayant 13 influenceurs du web y participant (notez que 13 fait partie de l’intervalle, mais qu’aucune observation n’avait été mesurée avec ce nombre d’influenceurs dans le jeu de données), nous n’avons qu’à substituer cette valeur dans l’équation qui donnera:</p>
<p><span class="math display">\[\hat{y_i} = 1.5 + 0.2 \cdot 13  
  \hat{y_i} = 4\]</span></p>
<p>Nous conclurons qu’une campagne publicitaire utilisant 13 influenceurs du web aura un facteur d’augmentation des ventes de 4. Cette réponse est seulement partielle pour l’instant. Bien que nous ayons une valeur prédite, cette valeur est difficile à interpréter sans mesure de précision. N’importe quel modèle peut nous produire une valeur prédite, mais les bons modèles fourniront des prédictions avec une bonne précision. On peut calculer l’erreur-type de la prédiction avec l’algèbre matricielle, mais la fonction dans permet d’extraire ces valeurs facilement. Par la suite, on peut calculer un intervalle de confiance autour de la valeur prédite selon la méthode habituelle:</p>
<p><span class="math display">\[IC \: \text{à} \: (1 - \alpha) \: \%: \\
  P(\hat{y_i} - t_{\alpha/2, \: \mathrm{degr\acute{e}s \: de \: libert\acute{e} \: r\acute{e}siduels}} \cdot SE_{\hat{y_i}} \leq \mu \leq \hat{y_i} + t_{\alpha/2, \: \mathrm{degr\acute{e}s \: de \: libert\acute{e} \: r\acute{e}siduels}} \cdot SE_{\hat{y_i}} = (1 - \alpha)\]</span>
où <span class="math inline">\(\hat{y_i}\)</span> représente l’estimation de la valeur prédite par l’équation de régression, <span class="math inline">\(SE_{\hat{y_i}}\)</span> donne la précision de cette estimation et <span class="math inline">\(t_{\alpha/2, \: \mathrm{degr\acute{e}s \: de \: libert\acute{e} \: r\acute{e}siduels}}\)</span> correspond à la statistique du <span class="math inline">\(t\)</span> de Student associée à la portion <span class="math inline">\((\alpha * 100)/2 \: \%\)</span> de la courbe et degrés de libertés résiduels. Afin d’utiliser <code>predict( )</code>, il faut fournir à l’argument <code>newdata</code> un jeu de données à partir duquel on fera les prédictions :</p>
<div class="sourceCode" id="cb782"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb782-1"><a href="leçon-9.html#cb782-1" tabindex="-1"></a><span class="do">##jeu de données à partir duquel on fait des prédictions</span></span>
<span id="cb782-2"><a href="leçon-9.html#cb782-2" tabindex="-1"></a>jeu.pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Nombre =</span> <span class="dv">13</span>)</span>
<span id="cb782-3"><a href="leçon-9.html#cb782-3" tabindex="-1"></a><span class="do">##on effectue la prédiction avec SE</span></span>
<span id="cb782-4"><a href="leçon-9.html#cb782-4" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1, <span class="at">newdata =</span> jeu.pred, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb782-5"><a href="leçon-9.html#cb782-5" tabindex="-1"></a><span class="do">##on calcule IC à 95 %</span></span>
<span id="cb782-6"><a href="leçon-9.html#cb782-6" tabindex="-1"></a>inf95 <span class="ot">&lt;-</span> pred<span class="sc">$</span>fit <span class="sc">+</span> </span>
<span id="cb782-7"><a href="leçon-9.html#cb782-7" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> m1<span class="sc">$</span>df.residual) <span class="sc">*</span> pred<span class="sc">$</span>se.fit</span>
<span id="cb782-8"><a href="leçon-9.html#cb782-8" tabindex="-1"></a>sup95 <span class="ot">&lt;-</span> pred<span class="sc">$</span>fit <span class="sc">-</span> </span>
<span id="cb782-9"><a href="leçon-9.html#cb782-9" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> m1<span class="sc">$</span>df.residual) <span class="sc">*</span> pred<span class="sc">$</span>se.fit</span>
<span id="cb782-10"><a href="leçon-9.html#cb782-10" tabindex="-1"></a><span class="fu">c</span>(inf95, sup95)</span></code></pre></div>
<pre><code>##        1        1 
## 3.627303 4.404464</code></pre>
<p>Nous concluons qu’une campagne publicitaire engageant 13 influenceurs du web aura un facteur d’augmentation des ventes de 4 avec un intervalle de confiance à 95 %: (<span class="math inline">\(3.6, 4.4\)</span>).</p>
<p>On peut utiliser la même stratégie afin d’ajouter des intervalles de confiance autour de la droite de régression (Figure <a href="leçon-9.html#fig:predic95">10.6</a>).</p>
<div class="sourceCode" id="cb784"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb784-1"><a href="leçon-9.html#cb784-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb784-2"><a href="leçon-9.html#cb784-2" tabindex="-1"></a><span class="do">##jeu de données à partir duquel on fait des prédictions</span></span>
<span id="cb784-3"><a href="leçon-9.html#cb784-3" tabindex="-1"></a>jeu.pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Nombre =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(influenceurs<span class="sc">$</span>Nombre), </span>
<span id="cb784-4"><a href="leçon-9.html#cb784-4" tabindex="-1"></a>                         <span class="at">to =</span> <span class="fu">max</span>(influenceurs<span class="sc">$</span>Nombre),</span>
<span id="cb784-5"><a href="leçon-9.html#cb784-5" tabindex="-1"></a>                         <span class="at">by =</span> <span class="dv">1</span>))</span>
<span id="cb784-6"><a href="leçon-9.html#cb784-6" tabindex="-1"></a><span class="do">##on effectue la prédiction avec SE</span></span>
<span id="cb784-7"><a href="leçon-9.html#cb784-7" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1, <span class="at">newdata =</span> jeu.pred, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb784-8"><a href="leçon-9.html#cb784-8" tabindex="-1"></a><span class="do">##ajout à jeu.pred</span></span>
<span id="cb784-9"><a href="leçon-9.html#cb784-9" tabindex="-1"></a>jeu.pred<span class="sc">$</span>fit <span class="ot">&lt;-</span> pred<span class="sc">$</span>fit</span>
<span id="cb784-10"><a href="leçon-9.html#cb784-10" tabindex="-1"></a>jeu.pred<span class="sc">$</span>se.fit <span class="ot">&lt;-</span> pred<span class="sc">$</span>se.fit</span>
<span id="cb784-11"><a href="leçon-9.html#cb784-11" tabindex="-1"></a><span class="do">##on calcule IC à 95 %</span></span>
<span id="cb784-12"><a href="leçon-9.html#cb784-12" tabindex="-1"></a>jeu.pred<span class="sc">$</span>inf95 <span class="ot">&lt;-</span> jeu.pred<span class="sc">$</span>fit <span class="sc">+</span> </span>
<span id="cb784-13"><a href="leçon-9.html#cb784-13" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> m1<span class="sc">$</span>df.residual) <span class="sc">*</span> jeu.pred<span class="sc">$</span>se.fit</span>
<span id="cb784-14"><a href="leçon-9.html#cb784-14" tabindex="-1"></a>jeu.pred<span class="sc">$</span>sup95 <span class="ot">&lt;-</span> jeu.pred<span class="sc">$</span>fit <span class="sc">-</span> </span>
<span id="cb784-15"><a href="leçon-9.html#cb784-15" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> m1<span class="sc">$</span>df.residual) <span class="sc">*</span> jeu.pred<span class="sc">$</span>se.fit</span>
<span id="cb784-16"><a href="leçon-9.html#cb784-16" tabindex="-1"></a><span class="do">##graphique avec points originaux</span></span>
<span id="cb784-17"><a href="leçon-9.html#cb784-17" tabindex="-1"></a><span class="fu">plot</span>(influenceurs<span class="sc">$</span>Facteur <span class="sc">~</span> influenceurs<span class="sc">$</span>Nombre,</span>
<span id="cb784-18"><a href="leçon-9.html#cb784-18" tabindex="-1"></a><span class="at">ylab =</span> <span class="st">&quot;Facteur d&#39;augmentation des ventes&quot;</span>,</span>
<span id="cb784-19"><a href="leçon-9.html#cb784-19" tabindex="-1"></a><span class="at">xlab =</span> <span class="st">&quot;Nombre d&#39;influenceurs&quot;</span>,</span>
<span id="cb784-20"><a href="leçon-9.html#cb784-20" tabindex="-1"></a><span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(jeu.pred<span class="sc">$</span>inf95), <span class="fu">max</span>(jeu.pred<span class="sc">$</span>sup95)),</span>
<span id="cb784-21"><a href="leçon-9.html#cb784-21" tabindex="-1"></a><span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb784-22"><a href="leçon-9.html#cb784-22" tabindex="-1"></a><span class="do">##ajoute droite</span></span>
<span id="cb784-23"><a href="leçon-9.html#cb784-23" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y =</span> jeu.pred<span class="sc">$</span>fit, <span class="at">x =</span> jeu.pred<span class="sc">$</span>Nombre)</span>
<span id="cb784-24"><a href="leçon-9.html#cb784-24" tabindex="-1"></a><span class="do">##ajoute limites de confiance</span></span>
<span id="cb784-25"><a href="leçon-9.html#cb784-25" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y =</span> jeu.pred<span class="sc">$</span>inf95, <span class="at">x =</span> jeu.pred<span class="sc">$</span>Nombre, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span>
<span id="cb784-26"><a href="leçon-9.html#cb784-26" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y =</span> jeu.pred<span class="sc">$</span>sup95, <span class="at">x =</span> jeu.pred<span class="sc">$</span>Nombre, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:predic95"></span>
<img src="Cours_Stats_R_files/figure-html/predic95-1.png" alt="Droite de régression avec limites de confiance à 95 % en pointillés et valeurs observées." width="672" />
<p class="caption">
Figure 10.6: Droite de régression avec limites de confiance à 95 % en pointillés et valeurs observées.
</p>
</div>
<p>Dans le reste du document, nous développons un autre exemple complet de régression linéaire afin d’appliquer les notions que nous avons apprises.</p>
<div class="exemple" section="10">
<p>Nous voulons déterminer si le prix de tablettes de chocolat (en dollars australiens) dépend de la masse en grammes de la tablette de chocolat. Une série de différentes tablettes de chocolat, toutes de différentes marques, ont été sélectionnées. Le fichier <code>chocolats.txt</code> contient ces données.</p>
<div class="sourceCode" id="cb785"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb785-1"><a href="leçon-9.html#cb785-1" tabindex="-1"></a><span class="do">##importation</span></span>
<span id="cb785-2"><a href="leçon-9.html#cb785-2" tabindex="-1"></a>chocs <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Module_10/data/chocolats.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb785-3"><a href="leçon-9.html#cb785-3" tabindex="-1"></a><span class="fu">head</span>(chocs)</span></code></pre></div>
<pre><code>##               Masse Prix
## Dark.Bounty      50 0.88
## Bounty           50 0.88
## Milo.Bar         40 1.15
## Viking           80 1.54
## KitKat.White     45 1.15
## KitKat.Chunky    78 1.40</code></pre>
<div class="sourceCode" id="cb787"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb787-1"><a href="leçon-9.html#cb787-1" tabindex="-1"></a><span class="do">##graphique des données</span></span>
<span id="cb787-2"><a href="leçon-9.html#cb787-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb787-3"><a href="leçon-9.html#cb787-3" tabindex="-1"></a><span class="fu">plot</span>(chocs<span class="sc">$</span>Prix <span class="sc">~</span> chocs<span class="sc">$</span>Masse, <span class="at">ylab =</span> <span class="st">&quot;Prix (dollars australiens)&quot;</span>,</span>
<span id="cb787-4"><a href="leçon-9.html#cb787-4" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Masse (g)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotchocs"></span>
<img src="Cours_Stats_R_files/figure-html/plotchocs-1.png" alt="Graphique du prix de tablettes de chocolat australiennes en fonction de leur masse." width="672" />
<p class="caption">
Figure 10.7: Graphique du prix de tablettes de chocolat australiennes en fonction de leur masse.
</p>
</div>
<p>Nous voyons qu’une relation linéaire entre ces deux variables est plausible (Figure <a href="leçon-9.html#fig:plotchocs">10.7</a>).</p>
<p>Nous pouvons essayer d’ajuster la régression linéaire aux données.</p>
<div class="sourceCode" id="cb788"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb788-1"><a href="leçon-9.html#cb788-1" tabindex="-1"></a>m.chocs <span class="ot">&lt;-</span> <span class="fu">lm</span>(Prix <span class="sc">~</span> Masse, <span class="at">data =</span> chocs)</span>
<span id="cb788-2"><a href="leçon-9.html#cb788-2" tabindex="-1"></a><span class="do">##vérifications des suppositions</span></span>
<span id="cb788-3"><a href="leçon-9.html#cb788-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb788-4"><a href="leçon-9.html#cb788-4" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">rstudent</span>(m.chocs) <span class="sc">~</span> <span class="fu">fitted</span>(m.chocs), </span>
<span id="cb788-5"><a href="leçon-9.html#cb788-5" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Résidus de Student&quot;</span>,</span>
<span id="cb788-6"><a href="leçon-9.html#cb788-6" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Valeurs prédites&quot;</span>,</span>
<span id="cb788-7"><a href="leçon-9.html#cb788-7" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Homogénéité des variances&quot;</span>, <span class="at">cex.main =</span> <span class="dv">1</span>)</span>
<span id="cb788-8"><a href="leçon-9.html#cb788-8" tabindex="-1"></a><span class="fu">text</span>(<span class="at">y =</span> <span class="fl">1.5</span>, <span class="at">x =</span> <span class="fl">1.025</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>)</span>
<span id="cb788-9"><a href="leçon-9.html#cb788-9" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">rstudent</span>(m.chocs), <span class="at">ylab =</span> <span class="st">&quot;Quantiles observés&quot;</span>,</span>
<span id="cb788-10"><a href="leçon-9.html#cb788-10" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">&quot;Quantiles théoriques&quot;</span>, </span>
<span id="cb788-11"><a href="leçon-9.html#cb788-11" tabindex="-1"></a>       <span class="at">main =</span> <span class="st">&quot;Normalité des résidus&quot;</span>, <span class="at">cex.main =</span> <span class="dv">1</span>)</span>
<span id="cb788-12"><a href="leçon-9.html#cb788-12" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">rstudent</span>(m.chocs))</span>
<span id="cb788-13"><a href="leçon-9.html#cb788-13" tabindex="-1"></a><span class="fu">text</span>(<span class="at">y =</span> <span class="fl">1.5</span>, <span class="at">x =</span> <span class="sc">-</span><span class="fl">1.9</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:regchocs"></span>
<img src="Cours_Stats_R_files/figure-html/regchocs-1.png" alt="Diagnostics des suppositions d'homogénéité des variances (a) et de normalité des résidus (b)." width="672" />
<p class="caption">
Figure 10.8: Diagnostics des suppositions d’homogénéité des variances (a) et de normalité des résidus (b).
</p>
</div>
<p>Les graphiques diagnostiques montrent que les variances sont sensiblement homogènes et que les résidus suivent approximativement une distribution normale (Figure <a href="leçon-9.html#fig:regchocs">10.8</a>). Puisque nous avons utilisé les résidus de Student, nous avons pu confirmer du même coup l’absence de valeurs extrêmes dans la figure <a href="leçon-9.html#fig:regchocs">10.8</a>a).</p>
<p>La fonction <code>summary( )</code> indique :</p>
<div class="sourceCode" id="cb789"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb789-1"><a href="leçon-9.html#cb789-1" tabindex="-1"></a><span class="fu">summary</span>(m.chocs)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Prix ~ Masse, data = chocs)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.28031 -0.14368  0.07184  0.12546  0.29969 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 0.574368   0.213738   2.687  0.01769 * 
## Masse       0.011266   0.003768   2.989  0.00975 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1891 on 14 degrees of freedom
## Multiple R-squared:  0.3896, Adjusted R-squared:  0.346 
## F-statistic: 8.937 on 1 and 14 DF,  p-value: 0.009753</code></pre>
<p>Nous concluons que la masse augmente significativement le prix de tablettes de chocolat en Australie avec une pente de 0.011 et un intervalle de confiance à 95 % de <span class="math inline">\((0.003, 0.019)\)</span>. La masse explique 39 % de la variance du prix, ce qui est satisfaisant avec ce type de données. Dans R, nous pouvons déterminer ces quantités de la façon suivante :</p>
<div class="sourceCode" id="cb791"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb791-1"><a href="leçon-9.html#cb791-1" tabindex="-1"></a><span class="do">##extraction de la pente et du degré de liberté</span></span>
<span id="cb791-2"><a href="leçon-9.html#cb791-2" tabindex="-1"></a><span class="do">##des résidus à partir de l&#39;objet m.chocs</span></span>
<span id="cb791-3"><a href="leçon-9.html#cb791-3" tabindex="-1"></a>pente <span class="ot">&lt;-</span> m.chocs<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb791-4"><a href="leçon-9.html#cb791-4" tabindex="-1"></a>df.res <span class="ot">&lt;-</span> m.chocs<span class="sc">$</span>df.residual</span>
<span id="cb791-5"><a href="leçon-9.html#cb791-5" tabindex="-1"></a></span>
<span id="cb791-6"><a href="leçon-9.html#cb791-6" tabindex="-1"></a><span class="do">##extraction du SE de la pente à partir de l&#39;objet</span></span>
<span id="cb791-7"><a href="leçon-9.html#cb791-7" tabindex="-1"></a><span class="do">##summary(m.chocs)</span></span>
<span id="cb791-8"><a href="leçon-9.html#cb791-8" tabindex="-1"></a>SE.pente <span class="ot">&lt;-</span> <span class="fu">summary</span>(m.chocs)<span class="sc">$</span>coefficient[<span class="dv">2</span>,<span class="dv">2</span>]</span>
<span id="cb791-9"><a href="leçon-9.html#cb791-9" tabindex="-1"></a></span>
<span id="cb791-10"><a href="leçon-9.html#cb791-10" tabindex="-1"></a><span class="do">##Calcul de l&#39;IC de la pente à 95%</span></span>
<span id="cb791-11"><a href="leçon-9.html#cb791-11" tabindex="-1"></a>inf95 <span class="ot">&lt;-</span> pente <span class="sc">+</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> df.res) <span class="sc">*</span> SE.pente</span>
<span id="cb791-12"><a href="leçon-9.html#cb791-12" tabindex="-1"></a>sup95 <span class="ot">&lt;-</span> pente <span class="sc">-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> df.res) <span class="sc">*</span> SE.pente</span>
<span id="cb791-13"><a href="leçon-9.html#cb791-13" tabindex="-1"></a><span class="fu">c</span>(inf95, sup95)</span></code></pre></div>
<pre><code>##       Masse       Masse 
## 0.003183133 0.019348192</code></pre>
<div class="sourceCode" id="cb793"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb793-1"><a href="leçon-9.html#cb793-1" tabindex="-1"></a><span class="do">##Calcul du R carré</span></span>
<span id="cb793-2"><a href="leçon-9.html#cb793-2" tabindex="-1"></a><span class="fu">summary</span>(m.chocs)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.3896299</code></pre>
<p>Nous pouvons présenter la droite de régression avec un intervalle de confiance à 95 % (Figure <a href="leçon-9.html#fig:conclusionchocs">10.9</a>).</p>
<div class="sourceCode" id="cb795"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb795-1"><a href="leçon-9.html#cb795-1" tabindex="-1"></a><span class="do">##jeu de données à partir duquel on fait des prédictions</span></span>
<span id="cb795-2"><a href="leçon-9.html#cb795-2" tabindex="-1"></a>jeu.pred <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Masse =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(chocs<span class="sc">$</span>Masse), </span>
<span id="cb795-3"><a href="leçon-9.html#cb795-3" tabindex="-1"></a>                         <span class="at">to =</span> <span class="fu">max</span>(chocs<span class="sc">$</span>Masse),</span>
<span id="cb795-4"><a href="leçon-9.html#cb795-4" tabindex="-1"></a>                         <span class="at">by =</span> <span class="dv">1</span>))</span>
<span id="cb795-5"><a href="leçon-9.html#cb795-5" tabindex="-1"></a><span class="do">##on effectue la prédiction avec SE</span></span>
<span id="cb795-6"><a href="leçon-9.html#cb795-6" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(m.chocs, <span class="at">newdata =</span> jeu.pred, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb795-7"><a href="leçon-9.html#cb795-7" tabindex="-1"></a><span class="do">##ajout à jeu.pred</span></span>
<span id="cb795-8"><a href="leçon-9.html#cb795-8" tabindex="-1"></a>jeu.pred<span class="sc">$</span>fit <span class="ot">&lt;-</span> pred<span class="sc">$</span>fit</span>
<span id="cb795-9"><a href="leçon-9.html#cb795-9" tabindex="-1"></a>jeu.pred<span class="sc">$</span>se.fit <span class="ot">&lt;-</span> pred<span class="sc">$</span>se.fit</span>
<span id="cb795-10"><a href="leçon-9.html#cb795-10" tabindex="-1"></a><span class="do">##on calcule IC à 95 %</span></span>
<span id="cb795-11"><a href="leçon-9.html#cb795-11" tabindex="-1"></a>jeu.pred<span class="sc">$</span>inf95 <span class="ot">&lt;-</span> jeu.pred<span class="sc">$</span>fit <span class="sc">+</span> </span>
<span id="cb795-12"><a href="leçon-9.html#cb795-12" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> m.chocs<span class="sc">$</span>df.residual) <span class="sc">*</span> jeu.pred<span class="sc">$</span>se.fit</span>
<span id="cb795-13"><a href="leçon-9.html#cb795-13" tabindex="-1"></a>jeu.pred<span class="sc">$</span>sup95 <span class="ot">&lt;-</span> jeu.pred<span class="sc">$</span>fit <span class="sc">-</span> </span>
<span id="cb795-14"><a href="leçon-9.html#cb795-14" tabindex="-1"></a>  <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.025</span>, <span class="at">df =</span> m.chocs<span class="sc">$</span>df.residual) <span class="sc">*</span> jeu.pred<span class="sc">$</span>se.fit</span>
<span id="cb795-15"><a href="leçon-9.html#cb795-15" tabindex="-1"></a><span class="do">##graphique avec points originaux</span></span>
<span id="cb795-16"><a href="leçon-9.html#cb795-16" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb795-17"><a href="leçon-9.html#cb795-17" tabindex="-1"></a><span class="fu">plot</span>(chocs<span class="sc">$</span>Prix <span class="sc">~</span> chocs<span class="sc">$</span>Masse, </span>
<span id="cb795-18"><a href="leçon-9.html#cb795-18" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Prix (dollars australiens)&quot;</span>,</span>
<span id="cb795-19"><a href="leçon-9.html#cb795-19" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Masse (g)&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>,</span>
<span id="cb795-20"><a href="leçon-9.html#cb795-20" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(jeu.pred<span class="sc">$</span>inf95), <span class="fu">max</span>(jeu.pred<span class="sc">$</span>sup95)))</span>
<span id="cb795-21"><a href="leçon-9.html#cb795-21" tabindex="-1"></a><span class="do">##on ajoute la droite</span></span>
<span id="cb795-22"><a href="leçon-9.html#cb795-22" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y =</span> jeu.pred<span class="sc">$</span>fit, <span class="at">x =</span> jeu.pred<span class="sc">$</span>Masse)</span>
<span id="cb795-23"><a href="leçon-9.html#cb795-23" tabindex="-1"></a><span class="do">##on ajoute les limites de confiance</span></span>
<span id="cb795-24"><a href="leçon-9.html#cb795-24" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y =</span> jeu.pred<span class="sc">$</span>inf95, <span class="at">x =</span> jeu.pred<span class="sc">$</span>Masse, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span>
<span id="cb795-25"><a href="leçon-9.html#cb795-25" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">y =</span> jeu.pred<span class="sc">$</span>sup95, <span class="at">x =</span> jeu.pred<span class="sc">$</span>Masse, <span class="at">lty =</span> <span class="st">&quot;dotted&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:conclusionchocs"></span>
<img src="Cours_Stats_R_files/figure-html/conclusionchocs-1.png" alt="Droite de régression et limites de confiance à 95 % (pointillés) à partir de l'analyse du prix en fonction de la masse de tablettes de chocolat australiennes et valeurs observées." width="672" />
<p class="caption">
Figure 10.9: Droite de régression et limites de confiance à 95 % (pointillés) à partir de l’analyse du prix en fonction de la masse de tablettes de chocolat australiennes et valeurs observées.
</p>
</div>
</div>
</div>
</div>
<div id="corrélation" class="section level3 hasAnchor" number="10.1.2">
<h3><span class="header-section-number">10.1.2</span> Corrélation<a href="leçon-9.html#corr%C3%A9lation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La <strong>corrélation</strong> est une relation d’association entre deux variables. Contrairement à la régression, il n’y a aucune allusion à une relation de cause à effet avec la corrélation. En d’autres mots, on ne distingue pas entre variable dépendante (<span class="math inline">\(y\)</span>) et indépendante (<span class="math inline">\(x\)</span>) – les deux variables varient en même temps et une troisième variable peut potentiellement agir sur les deux. Pour distinguer entre la régression et la corrélation, considérons un exemple où on veut expliquer le nombre moyen de verres cassés par jour dans des restaurants d’une ville selon le nombre de clients. Si le nombre de clients influence le nombre de verres cassés, nous aurons un cas de régression linéaire. À l’opposé, si on mesure le nombre moyen de verres cassés par jour dans des restaurants d’une ville et la quantité de déchets dans les rues autour de ces restaurants, la relation entre les deux variables serait plutôt une corrélation, et cette corrélation pourrait être expliquée par une troisième variable qui influencent les deux premières variables, c.-à-d. la densité de population ou le nombre de clients.</p>
<div id="corrélation-de-pearson" class="section level4 hasAnchor" number="10.1.2.1">
<h4><span class="header-section-number">10.1.2.1</span> Corrélation de Pearson<a href="leçon-9.html#corr%C3%A9lation-de-pearson" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le <strong>coefficient de corrélation de Pearson</strong> (<em>Pearson’s product-moment correlation coefficient</em>) nous donne la corrélation entre deux variables<a href="#fn30" class="footnote-ref" id="fnref30"><sup>30</sup></a>:</p>
<p><span class="math display">\[r = \frac{SSXY}{\sqrt{SSX \cdot SSY}}\]</span></p>
<p>où <span class="math inline">\(SSXY\)</span>, <span class="math inline">\(SSX\)</span> et <span class="math inline">\(SSY\)</span> sont les mêmes termes que l’on calcule dans la régression. La figure <a href="leçon-9.html#fig:corr1">10.10</a> présente différents degrés de corrélation positive, alors que la figure <a href="leçon-9.html#fig:corr2">10.11</a> illustre des corrélations négatives.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:corr1"></span>
<img src="Cours_Stats_R_files/figure-html/corr1-1.png" alt="Différents degrés de corrélation positive ($r &gt; 0$) entre deux variables." width="672" />
<p class="caption">
Figure 10.10: Différents degrés de corrélation positive (<span class="math inline">\(r &gt; 0\)</span>) entre deux variables.
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:corr2"></span>
<img src="Cours_Stats_R_files/figure-html/corr2-1.png" alt="Différents degrés de corrélation négative ($r &lt; 0$) entre deux variables." width="672" />
<p class="caption">
Figure 10.11: Différents degrés de corrélation négative (<span class="math inline">\(r &lt; 0\)</span>) entre deux variables.
</p>
</div>
<p>Dans R, on peut obtenir la corrélation de Pearson entre deux variables à l’aide de la fonction <code>cor( )</code>. Nous pouvons aussi effectuer un test d’hypothèse sur le coefficient de corrélation, à savoir s’il diffère de 0 (<span class="math inline">\(H_0: \rho = 0\)</span>) avec la fonction <code>cor.test( )</code>. Néanmoins, il faut demeurer vigilant car une valeur de <span class="math inline">\(P\)</span> faible n’est pas une garantie que la corrélation est forte. Une meilleure mesure s’avère le <span class="math inline">\(r^2\)</span> (c.-à-d., le coefficient de Pearson au carré) et est en fait le coefficient de détermination. Dans le cas d’une corrélation, il indique le pourcentage de la variation d’une variable qui est associée à la deuxième variable.</p>
<div class="exemple" section="10">
<p>Dans ce petit exemple, nous montrons le coefficient de corrélation entre deux variables aléatoires ainsi que le test d’hypothèse sur ce coefficient.</p>
<div class="sourceCode" id="cb796"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb796-1"><a href="leçon-9.html#cb796-1" tabindex="-1"></a><span class="do">##on crée deux variables aléatoires</span></span>
<span id="cb796-2"><a href="leçon-9.html#cb796-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">10</span>)</span>
<span id="cb796-3"><a href="leçon-9.html#cb796-3" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>)</span>
<span id="cb796-4"><a href="leçon-9.html#cb796-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="at">seed =</span> <span class="dv">11</span>)</span>
<span id="cb796-5"><a href="leçon-9.html#cb796-5" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>)</span>
<span id="cb796-6"><a href="leçon-9.html#cb796-6" tabindex="-1"></a><span class="do">##corrélation</span></span>
<span id="cb796-7"><a href="leçon-9.html#cb796-7" tabindex="-1"></a><span class="fu">cor</span>(x1, x2)</span></code></pre></div>
<pre><code>## [1] -0.0710729</code></pre>
<div class="sourceCode" id="cb798"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb798-1"><a href="leçon-9.html#cb798-1" tabindex="-1"></a><span class="do">##test d&#39;hypothèse</span></span>
<span id="cb798-2"><a href="leçon-9.html#cb798-2" tabindex="-1"></a><span class="fu">cor.test</span>(x1, x2)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x1 and x2
## t = -2.251, df = 998, p-value = 0.0246
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.132482263 -0.009120001
## sample estimates:
##        cor 
## -0.0710729</code></pre>
<div class="sourceCode" id="cb800"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb800-1"><a href="leçon-9.html#cb800-1" tabindex="-1"></a><span class="do">##r^2</span></span>
<span id="cb800-2"><a href="leçon-9.html#cb800-2" tabindex="-1"></a><span class="fu">cor</span>(x1, x2)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.005051357</code></pre>
<p>Chaque variable comporte 1000 valeurs et la corrélation de Pearson donne -0.071. Malgré cette faible corrélation, le test d’hypothèse rejette l’hypothèse nulle principalement en raison de l’énorme taille d’échantillon. Le <span class="math inline">\(r^2\)</span> est aussi très faible (0.005), indiquant que seulement 0.5% de la variabilité de <span class="math inline">\(x1\)</span> est associée à <span class="math inline">\(x2\)</span>. Nous conclurons que la corrélation est très faible et qu’à toute fin pratique, il n’y a pas d’association entre les deux variables (pas d’effet pratique).</p>
</div>
</div>
</div>
<div id="corrélation-vs-régression" class="section level3 hasAnchor" number="10.1.3">
<h3><span class="header-section-number">10.1.3</span> Corrélation vs régression<a href="leçon-9.html#corr%C3%A9lation-vs-r%C3%A9gression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La régression est souvent utilisée pour des études d’observation. Dans de telles conditions, une relation de cause à effet peut difficilement être établie sans avoir contrôlé les autres variables ou avoir mesuré toutes les variables pertinentes. Il faut faire attention à l’interprétation et les résultats peuvent suggérer le besoin de réaliser des expériences plus formelles. Les mêmes conseils de plan d’échantillonnage de l’ANOVA s’appliquent à la régression (e.g., randomisation, sélection aléatoire des unités expérimentales, répartition spatiale). La corrélation est surtout utilisée pour déterminer l’association entre deux variables sans être une relation de cause à effet. La corrélation est utile surtout dans la phase de préanalyse pour déterminer les relations entre différentes variables explicatives.</p>
</div>
<div id="conclusion-9" class="section level3 hasAnchor" number="10.1.4">
<h3><span class="header-section-number">10.1.4</span> Conclusion<a href="leçon-9.html#conclusion-9" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cette leçon a présenté la régression linéaire simple, les suppositions et conditions nécessaires à son application, l’interprétation et la présentation des résultats. Nous avons vu les tests d’hypothèses associés aux coefficients de la régression ainsi que l’utilisation d’intervalles de confiance comme mesure de précision autour des coefficients et des valeurs prédites. Nous avons également présenté la corrélation linéaire et nous l’avons comparé à la régression linéaire simple.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="28">
<li id="fn28"><p>Rappel: la somme des carrés des erreurs s’obtient avec l’équation <span class="math inline">\(SSE = \sum_{i=1}^n (y_i - \hat{y}_i)^2\)</span>, où <span class="math inline">\(y_i\)</span> correspond aux observations de la variable réponse et <span class="math inline">\(\hat{y}_i\)</span> représente les valeurs prédites par l’équation de régression.<a href="leçon-9.html#fnref28" class="footnote-back">↩︎</a></p></li>
<li id="fn29"><p>Dans le cas de certaines relations comme une relation exponentielle, transformer la variable réponse à l’échelle log peut linéariser la relation. Si le patron est plutôt quadratique (p. ex., une courbe avec un optimum), on peut aussi considérer un terme quadratique dans l’équation, c’est-à-dire, utiliser une régression polynomiale avec variable <span class="math inline">\(x + x^2\)</span><a href="leçon-9.html#fnref29" class="footnote-back">↩︎</a></p></li>
<li id="fn30"><p>Il existe aussi des analogues non-paramétriques de la corrélation, tels que la corrélation de Spearman ou de Kendall.<a href="leçon-9.html#fnref30" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lecon10.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="autoévaluation-6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": false
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
