<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8.1 Théories | Statistiques avec R</title>
  <meta name="description" content="8.1 Théories | Statistiques avec R" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="8.1 Théories | Statistiques avec R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="8.1 Théories | Statistiques avec R" />
  <meta name="github-repo" content="sci1018/sci1018" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8.1 Théories | Statistiques avec R" />
  
  <meta name="twitter:description" content="8.1 Théories | Statistiques avec R" />
  

<meta name="author" content="" />


<meta name="date" content="2024-08-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="blocs-complets-aléatoires.html"/>
<link rel="next" href="exercices-5.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistiques avec R</a></li>

<li class="divider"></li>
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="part"><span><b>I SCI 1018</b></span></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html"><i class="fa fa-check"></i>À propos du cours</a>
<ul>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#présentation"><i class="fa fa-check"></i>Présentation</a>
<ul>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#pourquoi-suivre-ce-cours"><i class="fa fa-check"></i>Pourquoi suivre ce cours ?</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#objectifs"><i class="fa fa-check"></i>Objectifs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#feuille-de-route"><i class="fa fa-check"></i>Feuille de route</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#crédits"><i class="fa fa-check"></i>Crédits</a></li>
<li class="chapter" data-level="" data-path="à-propos-du-cours.html"><a href="à-propos-du-cours.html#contact"><i class="fa fa-check"></i>Contact</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html"><i class="fa fa-check"></i>Ressources</a>
<ul>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#travaux-notés"><i class="fa fa-check"></i>Travaux notés</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#données"><i class="fa fa-check"></i>Données</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#ressources-r"><i class="fa fa-check"></i>Ressources R</a></li>
<li class="chapter" data-level="" data-path="ressources.html"><a href="ressources.html#références"><i class="fa fa-check"></i>Références</a></li>
</ul></li>
<li class="part"><span><b>II APPRENTISSAGE</b></span></li>
<li class="chapter" data-level="1" data-path="statistiques-descriptives.html"><a href="statistiques-descriptives.html"><i class="fa fa-check"></i><b>1</b> Statistiques descriptives</a>
<ul>
<li class="chapter" data-level="1.1" data-path="théories.html"><a href="théories.html"><i class="fa fa-check"></i><b>1.1</b> Théories</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="théories.html"><a href="théories.html#paramètre-vs-statistique"><i class="fa fa-check"></i><b>1.1.1</b> Paramètre vs statistique</a></li>
<li class="chapter" data-level="1.1.2" data-path="théories.html"><a href="théories.html#mesures-de-la-tendance-centrale"><i class="fa fa-check"></i><b>1.1.2</b> Mesures de la tendance centrale</a></li>
<li class="chapter" data-level="1.1.3" data-path="théories.html"><a href="théories.html#mesures-de-dispersion"><i class="fa fa-check"></i><b>1.1.3</b> Mesures de dispersion</a>
<ul>
<li class="chapter" data-level="1.1.3.1" data-path="théories.html"><a href="théories.html#somme-des-carrés-des-erreurs"><i class="fa fa-check"></i><b>1.1.3.1</b> Somme des carrés des erreurs</a></li>
<li class="chapter" data-level="1.1.3.2" data-path="théories.html"><a href="théories.html#carré-moyen-variance"><i class="fa fa-check"></i><b>1.1.3.2</b> Carré moyen (variance)</a></li>
<li class="chapter" data-level="1.1.3.3" data-path="théories.html"><a href="théories.html#précision-vs-exactitude"><i class="fa fa-check"></i><b>1.1.3.3</b> Précision vs exactitude</a></li>
<li class="chapter" data-level="1.1.3.4" data-path="théories.html"><a href="théories.html#autres-mesures-de-dispersion"><i class="fa fa-check"></i><b>1.1.3.4</b> Autres mesures de dispersion</a></li>
</ul></li>
<li class="chapter" data-level="1.1.4" data-path="théories.html"><a href="théories.html#variables-aléatoires"><i class="fa fa-check"></i><b>1.1.4</b> Variables aléatoires</a></li>
<li class="chapter" data-level="1.1.5" data-path="théories.html"><a href="théories.html#loi-des-grands-nombres-et-théorème-de-la-limite-centrale"><i class="fa fa-check"></i><b>1.1.5</b> Loi des grands nombres et théorème de la limite centrale</a></li>
<li class="chapter" data-level="1.1.6" data-path="théories.html"><a href="théories.html#distribution-normale"><i class="fa fa-check"></i><b>1.1.6</b> Distribution normale</a>
<ul>
<li class="chapter" data-level="1.1.6.1" data-path="théories.html"><a href="théories.html#caractéristiques-de-la-distribution-normale"><i class="fa fa-check"></i><b>1.1.6.1</b> Caractéristiques de la distribution normale</a></li>
<li class="chapter" data-level="1.1.6.2" data-path="théories.html"><a href="théories.html#distribution-normale-centrée-réduite"><i class="fa fa-check"></i><b>1.1.6.2</b> Distribution normale centrée réduite</a></li>
<li class="chapter" data-level="1.1.6.3" data-path="théories.html"><a href="théories.html#probabilités-cumulatives"><i class="fa fa-check"></i><b>1.1.6.3</b> Probabilités cumulatives</a></li>
<li class="chapter" data-level="1.1.6.4" data-path="théories.html"><a href="théories.html#applications-de-la-statistique-z-à-un-échantillon"><i class="fa fa-check"></i><b>1.1.6.4</b> Applications de la statistique z à un échantillon</a></li>
</ul></li>
<li class="chapter" data-level="1.1.7" data-path="théories.html"><a href="théories.html#conclusion"><i class="fa fa-check"></i><b>1.1.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="statistiques-de-base-avec-r.html"><a href="statistiques-de-base-avec-r.html"><i class="fa fa-check"></i><b>1.2</b> Statistiques de base avec R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="statistiques-de-base-avec-r.html"><a href="statistiques-de-base-avec-r.html#fonctions-statistiques-de-base"><i class="fa fa-check"></i><b>1.2.1</b> Fonctions statistiques de base</a></li>
<li class="chapter" data-level="1.2.2" data-path="statistiques-de-base-avec-r.html"><a href="statistiques-de-base-avec-r.html#distribution-statistiques"><i class="fa fa-check"></i><b>1.2.2</b> Distribution statistiques</a>
<ul>
<li class="chapter" data-level="1.2.2.1" data-path="statistiques-de-base-avec-r.html"><a href="statistiques-de-base-avec-r.html#probabilité-cumulative"><i class="fa fa-check"></i><b>1.2.2.1</b> Probabilité cumulative</a></li>
<li class="chapter" data-level="1.2.2.2" data-path="statistiques-de-base-avec-r.html"><a href="statistiques-de-base-avec-r.html#fonction-de-quantile"><i class="fa fa-check"></i><b>1.2.2.2</b> Fonction de quantile</a></li>
<li class="chapter" data-level="1.2.2.3" data-path="statistiques-de-base-avec-r.html"><a href="statistiques-de-base-avec-r.html#nombres-aléatoires"><i class="fa fa-check"></i><b>1.2.2.3</b> Nombres aléatoires</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="exercices.html"><a href="exercices.html"><i class="fa fa-check"></i><b>1.3</b> Exercices</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="exercices.html"><a href="exercices.html#question-1"><i class="fa fa-check"></i><b>1.3.1</b> Question 1</a></li>
<li class="chapter" data-level="1.3.2" data-path="exercices.html"><a href="exercices.html#question-2"><i class="fa fa-check"></i><b>1.3.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intervalles-de-confiance-et-stratégies-déchantillonnage.html"><a href="intervalles-de-confiance-et-stratégies-déchantillonnage.html"><i class="fa fa-check"></i><b>2</b> Intervalles de confiance et stratégies d’échantillonnage</a>
<ul>
<li class="chapter" data-level="2.1" data-path="théories-1.html"><a href="théories-1.html"><i class="fa fa-check"></i><b>2.1</b> Théories</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="théories-1.html"><a href="théories-1.html#problèmes-déchantillonnage"><i class="fa fa-check"></i><b>2.1.1</b> Problèmes d’échantillonnage</a>
<ul>
<li class="chapter" data-level="2.1.1.1" data-path="théories-1.html"><a href="théories-1.html#portion-de-la-population-non-représentée"><i class="fa fa-check"></i><b>2.1.1.1</b> Portion de la population non représentée</a></li>
<li class="chapter" data-level="2.1.1.2" data-path="théories-1.html"><a href="théories-1.html#erreurs-de-mesure-ou-de-saisie-des-données"><i class="fa fa-check"></i><b>2.1.1.2</b> Erreurs de mesure ou de saisie des données</a></li>
<li class="chapter" data-level="2.1.1.3" data-path="théories-1.html"><a href="théories-1.html#erreurs-liées-à-la-probabilité-de-détection"><i class="fa fa-check"></i><b>2.1.1.3</b> Erreurs liées à la probabilité de détection</a></li>
</ul></li>
<li class="chapter" data-level="2.1.2" data-path="théories-1.html"><a href="théories-1.html#échantillonnage-complètement-aléatoire"><i class="fa fa-check"></i><b>2.1.2</b> Échantillonnage complètement aléatoire</a></li>
<li class="chapter" data-level="2.1.3" data-path="théories-1.html"><a href="théories-1.html#intervalle-de-confiance"><i class="fa fa-check"></i><b>2.1.3</b> Intervalle de confiance</a>
<ul>
<li class="chapter" data-level="2.1.3.1" data-path="théories-1.html"><a href="théories-1.html#distribution-du-t-de-student"><i class="fa fa-check"></i><b>2.1.3.1</b> Distribution du <em>t</em> de Student</a></li>
<li class="chapter" data-level="2.1.3.2" data-path="théories-1.html"><a href="théories-1.html#rééchantillonnage"><i class="fa fa-check"></i><b>2.1.3.2</b> Rééchantillonnage</a></li>
</ul></li>
<li class="chapter" data-level="2.1.4" data-path="théories-1.html"><a href="théories-1.html#autres-stratégies-déchantillonnage"><i class="fa fa-check"></i><b>2.1.4</b> Autres stratégies d’échantillonnage</a>
<ul>
<li class="chapter" data-level="2.1.4.1" data-path="théories-1.html"><a href="théories-1.html#échantillonnage-stratifié"><i class="fa fa-check"></i><b>2.1.4.1</b> Échantillonnage stratifié</a></li>
<li class="chapter" data-level="2.1.4.2" data-path="théories-1.html"><a href="théories-1.html#échantillonnage-par-grappes-et-échantillonnage-systématique"><i class="fa fa-check"></i><b>2.1.4.2</b> Échantillonnage par grappes et échantillonnage systématique</a></li>
<li class="chapter" data-level="2.1.4.3" data-path="théories-1.html"><a href="théories-1.html#échantillonnage-multistade"><i class="fa fa-check"></i><b>2.1.4.3</b> Échantillonnage multistade</a></li>
<li class="chapter" data-level="2.1.4.4" data-path="théories-1.html"><a href="théories-1.html#échantillonnage-adaptatif"><i class="fa fa-check"></i><b>2.1.4.4</b> Échantillonnage adaptatif</a></li>
<li class="chapter" data-level="2.1.4.5" data-path="théories-1.html"><a href="théories-1.html#estimation-de-la-probabilité-de-détection"><i class="fa fa-check"></i><b>2.1.4.5</b> Estimation de la probabilité de détection</a></li>
</ul></li>
<li class="chapter" data-level="2.1.5" data-path="théories-1.html"><a href="théories-1.html#conclusion-1"><i class="fa fa-check"></i><b>2.1.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html"><i class="fa fa-check"></i><b>2.2</b> Les graphiques avec R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#graphiques-de-base"><i class="fa fa-check"></i><b>2.2.1</b> Graphiques de base</a></li>
<li class="chapter" data-level="2.2.2" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#histogramme"><i class="fa fa-check"></i><b>2.2.2</b> Histogramme</a></li>
<li class="chapter" data-level="2.2.3" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#diagramme-à-bâtons"><i class="fa fa-check"></i><b>2.2.3</b> Diagramme à bâtons</a></li>
<li class="chapter" data-level="2.2.4" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#diagramme-de-boîtes-et-moustaches"><i class="fa fa-check"></i><b>2.2.4</b> Diagramme de boîtes et moustaches</a></li>
<li class="chapter" data-level="2.2.5" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#graphiques-génériques"><i class="fa fa-check"></i><b>2.2.5</b> Graphiques génériques</a></li>
<li class="chapter" data-level="2.2.6" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#sauvegarder-des-graphiques"><i class="fa fa-check"></i><b>2.2.6</b> Sauvegarder des graphiques</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="exercices-1.html"><a href="exercices-1.html"><i class="fa fa-check"></i><b>2.3</b> Exercices</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="exercices-1.html"><a href="exercices-1.html#question-1-1"><i class="fa fa-check"></i><b>2.3.1</b> Question 1</a></li>
<li class="chapter" data-level="2.3.2" data-path="exercices-1.html"><a href="exercices-1.html#question-2-1"><i class="fa fa-check"></i><b>2.3.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="tests-dhypothèse-sur-un-seul-groupe.html"><a href="tests-dhypothèse-sur-un-seul-groupe.html"><i class="fa fa-check"></i><b>3</b> Tests d’hypothèse sur un seul groupe</a>
<ul>
<li class="chapter" data-level="3.1" data-path="théories-2.html"><a href="théories-2.html"><i class="fa fa-check"></i><b>3.1</b> Théories</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="théories-2.html"><a href="théories-2.html#hypothèse"><i class="fa fa-check"></i><b>3.1.1</b> Hypothèse</a>
<ul>
<li class="chapter" data-level="3.1.1.1" data-path="théories-2.html"><a href="théories-2.html#hypothèse-scientifique"><i class="fa fa-check"></i><b>3.1.1.1</b> Hypothèse scientifique</a></li>
<li class="chapter" data-level="3.1.1.2" data-path="théories-2.html"><a href="théories-2.html#méthode-scientifique"><i class="fa fa-check"></i><b>3.1.1.2</b> Méthode scientifique</a></li>
<li class="chapter" data-level="3.1.1.3" data-path="théories-2.html"><a href="théories-2.html#inférence-bayésienne"><i class="fa fa-check"></i><b>3.1.1.3</b> Inférence bayésienne</a></li>
<li class="chapter" data-level="3.1.1.4" data-path="théories-2.html"><a href="théories-2.html#méthode-hypothético-déductive"><i class="fa fa-check"></i><b>3.1.1.4</b> Méthode hypothético-déductive</a></li>
</ul></li>
<li class="chapter" data-level="3.1.2" data-path="théories-2.html"><a href="théories-2.html#hypothèse-statistiques"><i class="fa fa-check"></i><b>3.1.2</b> Hypothèse statistiques</a></li>
<li class="chapter" data-level="3.1.3" data-path="théories-2.html"><a href="théories-2.html#erreurs-de-type-i-et-ii"><i class="fa fa-check"></i><b>3.1.3</b> Erreurs de type I et II</a>
<ul>
<li class="chapter" data-level="3.1.3.1" data-path="théories-2.html"><a href="théories-2.html#puissance"><i class="fa fa-check"></i><b>3.1.3.1</b> Puissance</a></li>
<li class="chapter" data-level="3.1.3.2" data-path="théories-2.html"><a href="théories-2.html#relation-entre-les-erreurs-de-type-i-et-ii"><i class="fa fa-check"></i><b>3.1.3.2</b> Relation entre les erreurs de type I et II</a></li>
</ul></li>
<li class="chapter" data-level="3.1.4" data-path="théories-2.html"><a href="théories-2.html#utilisation-de-tests-dhypothèse"><i class="fa fa-check"></i><b>3.1.4</b> Utilisation de tests d’hypothèse</a>
<ul>
<li class="chapter" data-level="3.1.4.1" data-path="théories-2.html"><a href="théories-2.html#conseils-sur-la-présentation-des-résultats-de-tests-dhypothèse"><i class="fa fa-check"></i><b>3.1.4.1</b> Conseils sur la présentation des résultats de tests d’hypothèse</a></li>
</ul></li>
<li class="chapter" data-level="3.1.5" data-path="théories-2.html"><a href="théories-2.html#estimation-de-paramètres"><i class="fa fa-check"></i><b>3.1.5</b> Estimation de paramètres</a></li>
<li class="chapter" data-level="3.1.6" data-path="théories-2.html"><a href="théories-2.html#tests-dhypothèse-sur-la-moyenne-dun-seul-groupe"><i class="fa fa-check"></i><b>3.1.6</b> Tests d’hypothèse sur la moyenne d’un seul groupe</a>
<ul>
<li class="chapter" data-level="3.1.6.1" data-path="théories-2.html"><a href="théories-2.html#test-bilatéral-et-test-unilatéral"><i class="fa fa-check"></i><b>3.1.6.1</b> Test bilatéral et test unilatéral</a></li>
<li class="chapter" data-level="3.1.6.2" data-path="théories-2.html"><a href="théories-2.html#suppositions"><i class="fa fa-check"></i><b>3.1.6.2</b> Suppositions</a></li>
</ul></li>
<li class="chapter" data-level="3.1.7" data-path="théories-2.html"><a href="théories-2.html#conclusion-2"><i class="fa fa-check"></i><b>3.1.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="les-packages-avec-r.html"><a href="les-packages-avec-r.html"><i class="fa fa-check"></i><b>3.2</b> Les packages avec R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="les-packages-avec-r.html"><a href="les-packages-avec-r.html#activer-un-package"><i class="fa fa-check"></i><b>3.2.1</b> Activer un package</a></li>
<li class="chapter" data-level="3.2.2" data-path="les-packages-avec-r.html"><a href="les-packages-avec-r.html#installer-un-package"><i class="fa fa-check"></i><b>3.2.2</b> Installer un package</a></li>
<li class="chapter" data-level="3.2.3" data-path="les-packages-avec-r.html"><a href="les-packages-avec-r.html#mettre-à-jour-un-package"><i class="fa fa-check"></i><b>3.2.3</b> Mettre à jour un package</a></li>
<li class="chapter" data-level="3.2.4" data-path="les-packages-avec-r.html"><a href="les-packages-avec-r.html#désactiver-un-package"><i class="fa fa-check"></i><b>3.2.4</b> Désactiver un package</a></li>
<li class="chapter" data-level="3.2.5" data-path="les-packages-avec-r.html"><a href="les-packages-avec-r.html#désinstaller-un-package"><i class="fa fa-check"></i><b>3.2.5</b> Désinstaller un package</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="exercices-2.html"><a href="exercices-2.html"><i class="fa fa-check"></i><b>3.3</b> Exercices</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="exercices-2.html"><a href="exercices-2.html#question-1-2"><i class="fa fa-check"></i><b>3.3.1</b> Question 1</a></li>
<li class="chapter" data-level="3.3.2" data-path="exercices-2.html"><a href="exercices-2.html#question-2-2"><i class="fa fa-check"></i><b>3.3.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tests-dhypothèse-sur-deux-groupes.html"><a href="tests-dhypothèse-sur-deux-groupes.html"><i class="fa fa-check"></i><b>4</b> Tests d’hypothèse sur deux groupes</a>
<ul>
<li class="chapter" data-level="4.1" data-path="théories-3.html"><a href="théories-3.html"><i class="fa fa-check"></i><b>4.1</b> Théories</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="théories-3.html"><a href="théories-3.html#tests-dhypothèses-sur-la-moyenne-de-deux-groupes-indépendants"><i class="fa fa-check"></i><b>4.1.1</b> Tests d’hypothèses sur la moyenne de deux groupes indépendants</a>
<ul>
<li class="chapter" data-level="4.1.1.1" data-path="théories-3.html"><a href="théories-3.html#suppositions-1"><i class="fa fa-check"></i><b>4.1.1.1</b> Suppositions</a></li>
</ul></li>
<li class="chapter" data-level="4.1.2" data-path="théories-3.html"><a href="théories-3.html#tests-dhypothèse-pour-deux-groupes-appariés"><i class="fa fa-check"></i><b>4.1.2</b> Tests d’hypothèse pour deux groupes appariés</a></li>
<li class="chapter" data-level="4.1.3" data-path="théories-3.html"><a href="théories-3.html#transformations"><i class="fa fa-check"></i><b>4.1.3</b> Transformations</a>
<ul>
<li class="chapter" data-level="4.1.3.1" data-path="théories-3.html"><a href="théories-3.html#transformation-logarithmique"><i class="fa fa-check"></i><b>4.1.3.1</b> Transformation logarithmique</a></li>
<li class="chapter" data-level="4.1.3.2" data-path="théories-3.html"><a href="théories-3.html#transformation-racine-carrée"><i class="fa fa-check"></i><b>4.1.3.2</b> Transformation racine carrée</a></li>
<li class="chapter" data-level="4.1.3.3" data-path="théories-3.html"><a href="théories-3.html#transformation-arcsinus"><i class="fa fa-check"></i><b>4.1.3.3</b> Transformation arcsinus</a></li>
<li class="chapter" data-level="4.1.3.4" data-path="théories-3.html"><a href="théories-3.html#autres-transformations"><i class="fa fa-check"></i><b>4.1.3.4</b> Autres transformations</a></li>
</ul></li>
<li class="chapter" data-level="4.1.4" data-path="théories-3.html"><a href="théories-3.html#conclusion-3"><i class="fa fa-check"></i><b>4.1.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="laboratoire.html"><a href="laboratoire.html"><i class="fa fa-check"></i><b>4.2</b> Laboratoire</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="laboratoire.html"><a href="laboratoire.html#question-1-3"><i class="fa fa-check"></i><b>4.2.1</b> Question 1</a></li>
<li class="chapter" data-level="4.2.2" data-path="laboratoire.html"><a href="laboratoire.html#question-2-3"><i class="fa fa-check"></i><b>4.2.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyse-de-fréquences-et-test-du-khi-carré-chi2.html"><a href="analyse-de-fréquences-et-test-du-khi-carré-chi2.html"><i class="fa fa-check"></i><b>5</b> Analyse de fréquences et test du khi carré (<span class="math inline">\(\chi^2\)</span>)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="théories-4.html"><a href="théories-4.html"><i class="fa fa-check"></i><b>5.1</b> Théories</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="théories-4.html"><a href="théories-4.html#analyse-de-fréquences-le-test-du-khi-carré-chi2"><i class="fa fa-check"></i><b>5.1.1</b> Analyse de fréquences : le test du khi carré (<span class="math inline">\(\chi^2\)</span>)</a>
<ul>
<li class="chapter" data-level="5.1.1.1" data-path="théories-4.html"><a href="théories-4.html#la-distribution-du-khi-carré-chi2"><i class="fa fa-check"></i><b>5.1.1.1</b> La distribution du khi carré (<span class="math inline">\(\chi^2\)</span>)</a></li>
<li class="chapter" data-level="5.1.1.2" data-path="théories-4.html"><a href="théories-4.html#le-test-du-khi-carré-chi2"><i class="fa fa-check"></i><b>5.1.1.2</b> Le test du khi carré (<span class="math inline">\(\chi^2\)</span>)</a></li>
<li class="chapter" data-level="5.1.1.3" data-path="théories-4.html"><a href="théories-4.html#conditions-dutilisation"><i class="fa fa-check"></i><b>5.1.1.3</b> Conditions d’utilisation</a></li>
</ul></li>
<li class="chapter" data-level="5.1.2" data-path="théories-4.html"><a href="théories-4.html#tableau-de-contingence"><i class="fa fa-check"></i><b>5.1.2</b> Tableau de contingence</a>
<ul>
<li class="chapter" data-level="5.1.2.1" data-path="théories-4.html"><a href="théories-4.html#formulation-des-hypothèse-nulles"><i class="fa fa-check"></i><b>5.1.2.1</b> Formulation des hypothèse nulles</a></li>
<li class="chapter" data-level="5.1.2.2" data-path="théories-4.html"><a href="théories-4.html#fréquences-théoriques"><i class="fa fa-check"></i><b>5.1.2.2</b> Fréquences théoriques</a></li>
<li class="chapter" data-level="5.1.2.3" data-path="théories-4.html"><a href="théories-4.html#calcul-du-chi2-dindépendance"><i class="fa fa-check"></i><b>5.1.2.3</b> Calcul du <span class="math inline">\(\chi^2\)</span> d’indépendance</a></li>
</ul></li>
<li class="chapter" data-level="5.1.3" data-path="théories-4.html"><a href="théories-4.html#alternative-au-test-du-chi2"><i class="fa fa-check"></i><b>5.1.3</b> Alternative au test du <span class="math inline">\(\chi^2\)</span></a></li>
<li class="chapter" data-level="5.1.4" data-path="théories-4.html"><a href="théories-4.html#le-paradoxe-de-simpson"><i class="fa fa-check"></i><b>5.1.4</b> Le paradoxe de Simpson</a></li>
<li class="chapter" data-level="5.1.5" data-path="théories-4.html"><a href="théories-4.html#conclusion-4"><i class="fa fa-check"></i><b>5.1.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="exercices-3.html"><a href="exercices-3.html"><i class="fa fa-check"></i><b>5.2</b> Exercices</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="exercices-3.html"><a href="exercices-3.html#question-1-4"><i class="fa fa-check"></i><b>5.2.1</b> Question 1</a></li>
<li class="chapter" data-level="5.2.2" data-path="exercices-3.html"><a href="exercices-3.html#question-2-4"><i class="fa fa-check"></i><b>5.2.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analyse-de-variance-à-un-critère.html"><a href="analyse-de-variance-à-un-critère.html"><i class="fa fa-check"></i><b>6</b> Analyse de variance à un critère</a>
<ul>
<li class="chapter" data-level="6.1" data-path="théories-5.html"><a href="théories-5.html"><i class="fa fa-check"></i><b>6.1</b> Théories</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="théories-5.html"><a href="théories-5.html#comparaison-de-plusieurs-groupes"><i class="fa fa-check"></i><b>6.1.1</b> Comparaison de plusieurs groupes</a></li>
<li class="chapter" data-level="6.1.2" data-path="théories-5.html"><a href="théories-5.html#analyse-de-variance-anova"><i class="fa fa-check"></i><b>6.1.2</b> Analyse de variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.1.2.1" data-path="théories-5.html"><a href="théories-5.html#décomposition-de-la-variance"><i class="fa fa-check"></i><b>6.1.2.1</b> Décomposition de la variance</a></li>
<li class="chapter" data-level="6.1.2.2" data-path="théories-5.html"><a href="théories-5.html#la-distribution-du-f"><i class="fa fa-check"></i><b>6.1.2.2</b> La distribution du <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="6.1.2.3" data-path="théories-5.html"><a href="théories-5.html#hypothèses-statistiques"><i class="fa fa-check"></i><b>6.1.2.3</b> Hypothèses statistiques</a></li>
<li class="chapter" data-level="6.1.2.4" data-path="théories-5.html"><a href="théories-5.html#suppositions-2"><i class="fa fa-check"></i><b>6.1.2.4</b> Suppositions</a></li>
</ul></li>
<li class="chapter" data-level="6.1.3" data-path="théories-5.html"><a href="théories-5.html#comparaison-multiples"><i class="fa fa-check"></i><b>6.1.3</b> Comparaison multiples</a>
<ul>
<li class="chapter" data-level="6.1.3.1" data-path="théories-5.html"><a href="théories-5.html#erreurs-associées-aux-comparaisons-multiples"><i class="fa fa-check"></i><b>6.1.3.1</b> Erreurs associées aux comparaisons multiples</a></li>
<li class="chapter" data-level="6.1.3.2" data-path="théories-5.html"><a href="théories-5.html#suppositions-3"><i class="fa fa-check"></i><b>6.1.3.2</b> Suppositions</a></li>
<li class="chapter" data-level="6.1.3.3" data-path="théories-5.html"><a href="théories-5.html#structure-générale"><i class="fa fa-check"></i><b>6.1.3.3</b> Structure générale</a></li>
<li class="chapter" data-level="6.1.3.4" data-path="théories-5.html"><a href="théories-5.html#test-de-tukey"><i class="fa fa-check"></i><b>6.1.3.4</b> Test de Tukey</a></li>
<li class="chapter" data-level="6.1.3.5" data-path="théories-5.html"><a href="théories-5.html#présentation-des-résultats"><i class="fa fa-check"></i><b>6.1.3.5</b> Présentation des résultats</a></li>
</ul></li>
<li class="chapter" data-level="6.1.4" data-path="théories-5.html"><a href="théories-5.html#conclusion-5"><i class="fa fa-check"></i><b>6.1.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="les-boucles-avec-r.html"><a href="les-boucles-avec-r.html"><i class="fa fa-check"></i><b>6.2</b> Les boucles avec R</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="les-boucles-avec-r.html"><a href="les-boucles-avec-r.html#les-boucles"><i class="fa fa-check"></i><b>6.2.1</b> Les boucles</a>
<ul>
<li class="chapter" data-level="6.2.1.1" data-path="les-boucles-avec-r.html"><a href="les-boucles-avec-r.html#structure"><i class="fa fa-check"></i><b>6.2.1.1</b> Structure</a></li>
</ul></li>
<li class="chapter" data-level="6.2.2" data-path="les-boucles-avec-r.html"><a href="les-boucles-avec-r.html#alternatives-aux-boucles"><i class="fa fa-check"></i><b>6.2.2</b> Alternatives aux boucles</a>
<ul>
<li class="chapter" data-level="6.2.2.1" data-path="les-boucles-avec-r.html"><a href="les-boucles-avec-r.html#apply-et-fonctions-apparentées"><i class="fa fa-check"></i><b>6.2.2.1</b> <code>apply( )</code> et fonctions apparentées</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="exercices-4.html"><a href="exercices-4.html"><i class="fa fa-check"></i><b>6.3</b> Exercices</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="exercices-4.html"><a href="exercices-4.html#question-1-5"><i class="fa fa-check"></i><b>6.3.1</b> Question 1</a></li>
<li class="chapter" data-level="6.3.2" data-path="exercices-4.html"><a href="exercices-4.html#question-2-5"><i class="fa fa-check"></i><b>6.3.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="analyse-de-variance-à-deux-critères.html"><a href="analyse-de-variance-à-deux-critères.html"><i class="fa fa-check"></i><b>7</b> Analyse de variance à deux critères</a>
<ul>
<li class="chapter" data-level="7.1" data-path="théories-6.html"><a href="théories-6.html"><i class="fa fa-check"></i><b>7.1</b> Théories</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="théories-6.html"><a href="théories-6.html#anova-à-deux-critères"><i class="fa fa-check"></i><b>7.1.1</b> ANOVA à deux critères</a></li>
<li class="chapter" data-level="7.1.2" data-path="théories-6.html"><a href="théories-6.html#suppositions-et-dispositif-expérimental"><i class="fa fa-check"></i><b>7.1.2</b> Suppositions et dispositif expérimental</a></li>
<li class="chapter" data-level="7.1.3" data-path="théories-6.html"><a href="théories-6.html#hypothèses-statistiques-1"><i class="fa fa-check"></i><b>7.1.3</b> Hypothèses statistiques</a></li>
<li class="chapter" data-level="7.1.4" data-path="théories-6.html"><a href="théories-6.html#sommes-des-carrés-1"><i class="fa fa-check"></i><b>7.1.4</b> Sommes des carrés</a></li>
<li class="chapter" data-level="7.1.5" data-path="théories-6.html"><a href="théories-6.html#effets-additifs"><i class="fa fa-check"></i><b>7.1.5</b> Effets additifs</a></li>
<li class="chapter" data-level="7.1.6" data-path="théories-6.html"><a href="théories-6.html#conclusion-6"><i class="fa fa-check"></i><b>7.1.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="laboratoire-1.html"><a href="laboratoire-1.html"><i class="fa fa-check"></i><b>7.2</b> Laboratoire</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="laboratoire-1.html"><a href="laboratoire-1.html#question-1-6"><i class="fa fa-check"></i><b>7.2.1</b> Question 1</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="blocs-complets-aléatoires.html"><a href="blocs-complets-aléatoires.html"><i class="fa fa-check"></i><b>8</b> Blocs complets aléatoires</a>
<ul>
<li class="chapter" data-level="8.1" data-path="théories-7.html"><a href="théories-7.html"><i class="fa fa-check"></i><b>8.1</b> Théories</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="théories-7.html"><a href="théories-7.html#effets-fixes-et-effets-aléatoires"><i class="fa fa-check"></i><b>8.1.1</b> Effets fixes et effets aléatoires</a>
<ul>
<li class="chapter" data-level="8.1.1.1" data-path="théories-7.html"><a href="théories-7.html#anova-à-un-critère"><i class="fa fa-check"></i><b>8.1.1.1</b> ANOVA à un critère</a></li>
<li class="chapter" data-level="8.1.1.2" data-path="théories-7.html"><a href="théories-7.html#anova-à-deux-critères-1"><i class="fa fa-check"></i><b>8.1.1.2</b> ANOVA à deux critères</a></li>
</ul></li>
<li class="chapter" data-level="8.1.2" data-path="théories-7.html"><a href="théories-7.html#blocs-complets-aléatoires-1"><i class="fa fa-check"></i><b>8.1.2</b> Blocs complets aléatoires</a>
<ul>
<li class="chapter" data-level="8.1.2.1" data-path="théories-7.html"><a href="théories-7.html#révision-de-léchantillonnage"><i class="fa fa-check"></i><b>8.1.2.1</b> Révision de l’échantillonnage</a></li>
<li class="chapter" data-level="8.1.2.2" data-path="théories-7.html"><a href="théories-7.html#origine-du-dispositif-en-blocs-complets-aléatoires"><i class="fa fa-check"></i><b>8.1.2.2</b> Origine du dispositif en blocs complets aléatoires</a></li>
<li class="chapter" data-level="8.1.2.3" data-path="théories-7.html"><a href="théories-7.html#particularité-du-dispositif-en-blocs-complets-aléatoires"><i class="fa fa-check"></i><b>8.1.2.3</b> Particularité du dispositif en blocs complets aléatoires</a></li>
<li class="chapter" data-level="8.1.2.4" data-path="théories-7.html"><a href="théories-7.html#applications-moins-conventionnelles"><i class="fa fa-check"></i><b>8.1.2.4</b> Applications moins conventionnelles</a></li>
<li class="chapter" data-level="8.1.2.5" data-path="théories-7.html"><a href="théories-7.html#conditions-dapplication"><i class="fa fa-check"></i><b>8.1.2.5</b> Conditions d’application</a></li>
<li class="chapter" data-level="8.1.2.6" data-path="théories-7.html"><a href="théories-7.html#avantages-du-dispositif-en-blocs-complets-aléatoires"><i class="fa fa-check"></i><b>8.1.2.6</b> Avantages du dispositif en blocs complets aléatoires</a></li>
<li class="chapter" data-level="8.1.2.7" data-path="théories-7.html"><a href="théories-7.html#désavantages-du-dispositif-en-blocs-complets-aléatoires"><i class="fa fa-check"></i><b>8.1.2.7</b> Désavantages du dispositif en blocs complets aléatoires</a></li>
</ul></li>
<li class="chapter" data-level="8.1.3" data-path="théories-7.html"><a href="théories-7.html#conclusion-7"><i class="fa fa-check"></i><b>8.1.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="exercices-5.html"><a href="exercices-5.html"><i class="fa fa-check"></i><b>8.2</b> Exercices</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="exercices-5.html"><a href="exercices-5.html#question-1-7"><i class="fa fa-check"></i><b>8.2.1</b> Question 1</a></li>
<li class="chapter" data-level="8.2.2" data-path="exercices-5.html"><a href="exercices-5.html#question-2-6"><i class="fa fa-check"></i><b>8.2.2</b> Question 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="élaboration-et-optimisation-de-plans-déchantillonnage.html"><a href="élaboration-et-optimisation-de-plans-déchantillonnage.html"><i class="fa fa-check"></i><b>9</b> Élaboration et optimisation de plans d’échantillonnage</a>
<ul>
<li class="chapter" data-level="9.1" data-path="théories-8.html"><a href="théories-8.html"><i class="fa fa-check"></i><b>9.1</b> Théories</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="théories-8.html"><a href="théories-8.html#plans-déchantillonnage"><i class="fa fa-check"></i><b>9.1.1</b> Plans d’échantillonnage</a>
<ul>
<li class="chapter" data-level="9.1.1.1" data-path="théories-8.html"><a href="théories-8.html#expérience-vs-étude-dobservation"><i class="fa fa-check"></i><b>9.1.1.1</b> Expérience vs étude d’observation</a></li>
<li class="chapter" data-level="9.1.1.2" data-path="théories-8.html"><a href="théories-8.html#témoin"><i class="fa fa-check"></i><b>9.1.1.2</b> Témoin</a></li>
<li class="chapter" data-level="9.1.1.3" data-path="théories-8.html"><a href="théories-8.html#placébo"><i class="fa fa-check"></i><b>9.1.1.3</b> Placébo</a></li>
<li class="chapter" data-level="9.1.1.4" data-path="théories-8.html"><a href="théories-8.html#prise-de-données-en-aveugle"><i class="fa fa-check"></i><b>9.1.1.4</b> Prise de données en aveugle</a></li>
<li class="chapter" data-level="9.1.1.5" data-path="théories-8.html"><a href="théories-8.html#répétition-randomisation-et-répartition-spatiale"><i class="fa fa-check"></i><b>9.1.1.5</b> Répétition, randomisation et répartition spatiale</a></li>
</ul></li>
<li class="chapter" data-level="9.1.2" data-path="théories-8.html"><a href="théories-8.html#nos-meilleurs-alliés-dans-lélaboration-dun-plan-déchantillonnage"><i class="fa fa-check"></i><b>9.1.2</b> Nos meilleurs alliés dans l’élaboration d’un plan d’échantillonnage</a></li>
<li class="chapter" data-level="9.1.3" data-path="théories-8.html"><a href="théories-8.html#problèmes-associés-à-certains-plan-déchantillonnage"><i class="fa fa-check"></i><b>9.1.3</b> Problèmes associés à certains plan d’échantillonnage</a>
<ul>
<li class="chapter" data-level="9.1.3.1" data-path="théories-8.html"><a href="théories-8.html#labsence-de-réelles-répétitions-la-pseudoréplication"><i class="fa fa-check"></i><b>9.1.3.1</b> L’absence de réelles répétitions : la pseudoréplication</a></li>
<li class="chapter" data-level="9.1.3.2" data-path="théories-8.html"><a href="théories-8.html#contrôler-la-variabilité-temporelle"><i class="fa fa-check"></i><b>9.1.3.2</b> Contrôler la variabilité temporelle</a></li>
<li class="chapter" data-level="9.1.3.3" data-path="théories-8.html"><a href="théories-8.html#sources-de-confusion"><i class="fa fa-check"></i><b>9.1.3.3</b> Sources de confusion</a></li>
</ul></li>
<li class="chapter" data-level="9.1.4" data-path="théories-8.html"><a href="théories-8.html#conclusion-8"><i class="fa fa-check"></i><b>9.1.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="laboratoire-2.html"><a href="laboratoire-2.html"><i class="fa fa-check"></i><b>9.2</b> Laboratoire</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="laboratoire-2.html"><a href="laboratoire-2.html#instructions"><i class="fa fa-check"></i><b>9.2.1</b> Instructions</a></li>
<li class="chapter" data-level="9.2.2" data-path="laboratoire-2.html"><a href="laboratoire-2.html#suggestions-de-thèmes-à-étudier"><i class="fa fa-check"></i><b>9.2.2</b> Suggestions de thèmes à étudier</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistiques avec R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="théories-7" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Théories<a href="théories-7.html#théories-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="effets-fixes-et-effets-aléatoires" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Effets fixes et effets aléatoires<a href="théories-7.html#effets-fixes-et-effets-aléatoires" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dans les leçons précédentes, nous avons vu l’ANOVA à un critère et l’ANOVA à deux critères. Dans tous les exemples que nous avons présentés, les effets étudiés étaient fixés par l’expérimentateur. Par exemple, on s’intéressait à l’effet du sexe ou d’un traitement hormonal sur la concentration en calcium dans le plasma sanguin . Lorsque les niveaux du facteur sont spécifiquement choisis par l’expérimentateur, nous dirons que c’est un <strong>effet fixe</strong>. Ce genre d’effet est le plus commun.</p>
<hr />
<div class="exemple" section="8">
<p>Dans une expérience sur l’effet de la zoothérapie sur des personnes atteintes d’un stress chronique, on sélectionne aléatoirement 30 personnes atteintes. L’expérimentateur s’intéresse à la différence entre les traitements suivants : thérapie accompagnée d’un chat, thérapie accompagnée d’un chien et thérapie conventionnelle. On attribue aléatoirement l’un des traitements à chaque personne atteinte, de façon à avoir 10 répétitions pour chaque traitement. Puisque l’expérimentateur s’intéresse spécifiquement à ces trois traitements, l’effet de la zoothérapie est un effet fixe.</p>
</div>
<hr />
<p>En contrepartie, lorsque les niveaux d’un facteur sont déterminés aléatoirement, nous dirons que c’est un <strong>effet aléatoire</strong>. Autrement dit, l’expérimentateur choisit aléatoirement les niveaux qui seront inclus dans l’expérience parmi tous les niveaux disponibles. L’effet aléatoire permet d’étudier l’effet global d’un facteur sur la variable réponse en considérant tous les traitements possibles plutôt que les différences entre des traitements spécifiques.</p>
<hr />
<div class="exemple" section="8">
<p>On veut connaître s’il y a un effet du fournisseur de batteries de téléphone portable sur leur durée de vie. Dans un catalogue de fournisseurs de batteries, on sélectionne aléatoirement 3 fournisseurs de batteries. On commande 10 batteries de chacun des 3 fournisseurs. Puisque les trois niveaux du facteur <code>fournisseur de batteries</code> ont été sélectionnés aléatoirement, nous dirons que c’est un effet aléatoire.</p>
</div>
<hr />
<p>La différence entre l’effet fixe et l’effet aléatoire est au niveau de l’interprétation des résultats. Avec un effet fixe, on s’intéresse à la différence entre les niveaux spécifiques du facteur et notre conclusion se rapporte directement à ces niveaux. Pour l’effet aléatoire, la conclusion est pertinente à l’effet global du facteur et à tous les niveaux possibles du facteur. Dans le dernier cas, il peut exister une multitude de niveaux qui n’ont pas nécessairement été inclus dans l’analyse. L’exemple suivant distingue les deux types d’effets.</p>
<hr />
<div class="exemple" section="8">
<p>On veut déterminer la variabilité géographique de la concentration en cadmium dans le sol au Québec. Si l’expérimentateur identifie différentes régions du Québec et qu’il sélectionne aléatoirement trois régions, on considérera l’effet comme aléatoire. À l’opposé, si l’expérimentateur s’intéresse spécifiquement aux régions de l’Abitibi, du Lac St-Jean et de la Côte-Nord, on considérera l’effet comme fixe.</p>
</div>
<hr />
<div id="anova-à-un-critère" class="section level4 hasAnchor" number="8.1.1.1">
<h4><span class="header-section-number">8.1.1.1</span> ANOVA à un critère<a href="théories-7.html#anova-à-un-critère" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Lorsqu’on effectue une ANOVA à un critère, le calcul de la somme des carrés, des carrés moyens et du <span class="math inline">\(F\)</span> demeure le même, peu importe que l’effet soit fixe ou aléatoire. Seule l’interprétation va changer.</p>
</div>
<div id="anova-à-deux-critères-1" class="section level4 hasAnchor" number="8.1.1.2">
<h4><span class="header-section-number">8.1.1.2</span> ANOVA à deux critères<a href="théories-7.html#anova-à-deux-critères-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>En ce qui concerne l’ANOVA à deux critères (A et B) avec répétition, c’est-à-dire avec plus d’une observation, on distingue trois scénarios d’effets fixes et aléatoires possibles :</p>
<ul>
<li>Modèle I: A fixe et B fixe</li>
<li>Modèle II: A aléatoire et B aléatoire</li>
<li>Modèle III: A aléatoire et B fixe<a href="#fn23" class="footnote-ref" id="fnref23"><sup>23</sup></a></li>
</ul>
<p>Le type d’effet (fixe <em>vs</em> aléatoire) détermine le terme d’erreur à utiliser dans le tableau d’ANOVA. Le tableau <a href="théories-7.html#tab:SS">8.1</a> présente la formulation des différents ratios des carrés moyens pour tester les effets de A, de B et de leur interaction selon la nature de ces effets.</p>
<table class="table" style="color: black; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:SS">Table 8.1: </span>Termes d’erreurs utilisés pour tester les effets de A, de B et de leur interaction selon la nature des effets (fixes ou aléatoires) en présence de répétitions.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Facteur
</th>
<th style="text-align:left;">
Modèle I <br> (A fixe, B fixe)
</th>
<th style="text-align:left;">
Modèle II <br> (A aléatoire, B aléatoire)
</th>
<th style="text-align:left;">
Modèle III <br> (A aléatoire, B fixe)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{A}}{MS \: \mathrm{erreur}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{A}}{MS \: \mathrm{A \: \times \: B}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{A}}{MS \: \mathrm{erreur}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{B}}{MS \: \mathrm{erreur}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{B}}{MS \: \mathrm{A \: \times \: B}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{B}}{MS \: \mathrm{A \: \times \: B}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
A x B
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{A \: \times \: B}}{MS \: \mathrm{erreur}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{A \: \times \: B}}{MS \: \mathrm{erreur}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\frac{MS \: \mathrm{A \: \times \: B}}{MS \: \mathrm{erreur}}\)</span>
</td>
</tr>
</tbody>
</table>
<p>Le modèle III est aussi appelé <strong>modèle mixte</strong> puisqu’il contient des effets fixes et des effets aléatoires. Les modèles mixtes englobent une variété d’approches qui tiennent compte de la structure de données complexes, telles que celles provenant d’un dispositif dit niché ou emboité (p.ex., sondages auprès d’individus emboîtés dans des quartiers, ces derniers emboîtés eux-mêmes dans différentes villes) ou encore avec des mesures répétées dans le temps. Le dispositif expérimental le plus simple du modèle III est le dispositif en <strong>blocs complets aléatoires</strong> et c’est celui que nous verrons en détail dans la prochaine section.</p>
</div>
</div>
<div id="blocs-complets-aléatoires-1" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Blocs complets aléatoires<a href="théories-7.html#blocs-complets-aléatoires-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Le dispositif en <strong>blocs complets aléatoires</strong> consiste en deux facteurs, l’un fixe, l’autre aléatoire, mais sans répétition. Avant d’aller plus loin, revisitons les dispositifs expérimentaux menant à certaines des analyses que nous avons vues dans les leçons précédentes.</p>
<div id="révision-de-léchantillonnage" class="section level4 hasAnchor" number="8.1.2.1">
<h4><span class="header-section-number">8.1.2.1</span> Révision de l’échantillonnage<a href="théories-7.html#révision-de-léchantillonnage" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Certains dispositifs expérimentaux permettent d’échantillonner les données de façon complètement aléatoire. Par exemple, lorsqu’on applique le test <span class="math inline">\(t\)</span> à un échantillon, on sélectionne les unités expérimentales aléatoirement parmi la population et on compare la moyenne à celle de l’hypothèse nulle (Figure <a href="théories-7.html#fig:randomunits">8.1</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:randomunits"></span>
<a href="images/Random_units.png" target="_blank"><img src="Module_8/images/Random_units.png" alt="Sélection aléatoire des unités expérimentales parmi la population pour le test $t$ à un échantillon ($n = 12$)." width="342" /></a>
<p class="caption">
Figure 8.1: Sélection aléatoire des unités expérimentales parmi la population pour le test <span class="math inline">\(t\)</span> à un échantillon (<span class="math inline">\(n = 12\)</span>).
</p>
</div>
<p>Pour ce qui est du test <span class="math inline">\(t\)</span> sur deux échantillons indépendants, on sélectionne les unités expérimentales et on attribue aléatoirement l’un des deux traitements aux unités (Figure <a href="théories-7.html#fig:completelyrandom">8.2</a>). Dans l’ANOVA à un critère, les unités expérimentales sont sélectionnées aléatoirement et on attribue les traitements de façon complètement aléatoire (Figure <a href="théories-7.html#fig:completelyrandomaov">8.3</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:completelyrandom"></span>
<a href="images/Completely_random_t.png" target="_blank"><img src="Module_8/images/Completely_random_t.png" alt="Sélection aléatoire des unités expérimentales et attribution aléatoire des unités parmi la population pour le test $t$ à deux groupes. À noter que les deux couleurs distinguent les deux traitements appliqués aux unités expérimentales ($n = 8$ répétitions par traitement).}" width="347" /></a>
<p class="caption">
Figure 8.2: Sélection aléatoire des unités expérimentales et attribution aléatoire des unités parmi la population pour le test <span class="math inline">\(t\)</span> à deux groupes. À noter que les deux couleurs distinguent les deux traitements appliqués aux unités expérimentales (<span class="math inline">\(n = 8\)</span> répétitions par traitement).}
</p>
</div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:completelyrandomaov"></span>
<a href="images/Completely_random_aov.png" target="_blank"><img src="Module_8/images/Completely_random_aov.png" alt="Sélection aléatoire des unités expérimentales et assignation aléatoire de trois traitements dans un dispositif complètement aléatoire. À noter que chaque couleur correspond à un traitement appliqué à l'unité expérimentale ($n = 8$ répétitions par traitement)." width="343" /></a>
<p class="caption">
Figure 8.3: Sélection aléatoire des unités expérimentales et assignation aléatoire de trois traitements dans un dispositif complètement aléatoire. À noter que chaque couleur correspond à un traitement appliqué à l’unité expérimentale (<span class="math inline">\(n = 8\)</span> répétitions par traitement).
</p>
</div>
<p>D’autres dispositifs expérimentaux imposent une structure aux données: certaines unités expérimentales ne sont pas indépendantes. Par exemple, le test <span class="math inline">\(t\)</span> pour données appariées traite les données par paire. On sélectionne aléatoirement les paires et on attribue aléatoirement l’un des traitements à chaque élément de la paire (Figure <a href="théories-7.html#fig:pairedt">8.4</a>). Ce dispositif minimise la variabilité intrapaire, mais permet une grande variabilité entre paires. Cette stratégie d’échantillonnage est avantageuse puisque, dans certains cas, il est logistiquement plus simple d’échantillonner des paires d’unités expérimentales que des unités expérimentales indépendantes. Par exemple, le dispositif apparié présenté à la figure (<a href="théories-7.html#fig:pairedt">8.4</a>) nécessite huit paires d’unités expérimentales. En contrepartie, si on utilise un dispositif complètement aléatoire avec deux groupes comme pour le test <span class="math inline">\(t\)</span> à deux groupes indépendants, on aura recours à 16 unités expérimentales indépendantes (Figure <a href="théories-7.html#fig:completelyrandom">8.2</a>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:pairedt"></span>
<a href="images/Paired_t.png" target="_blank"><img src="Module_8/images/Paired_t.png" alt="Sélection aléatoire des paires d'unités expérimentales et assignation aléatoire de l'un des deux traitements. À noter que chaque couleur correspond à un des deux traitements appliqués à chaque unité expérimentale d'une paire ($n = 8$ paires)." width="348" /></a>
<p class="caption">
Figure 8.4: Sélection aléatoire des paires d’unités expérimentales et assignation aléatoire de l’un des deux traitements. À noter que chaque couleur correspond à un des deux traitements appliqués à chaque unité expérimentale d’une paire (<span class="math inline">\(n = 8\)</span> paires).
</p>
</div>
<p>L’<strong>ANOVA en blocs complets aléatoires</strong> est l’extension du test <span class="math inline">\(t\)</span> pour données appariées lorsqu’on a plus de deux traitements. Le <strong>bloc</strong> est l’analogue à la paire dans le test <span class="math inline">\(t\)</span>: alors que la paire était constituée de deux observations liées entre elles, le bloc est constitué de plus de deux observations reliées entre elles (Figure <a href="théories-7.html#fig:bloc">8.5</a>). Tout comme le test <span class="math inline">\(t\)</span> pour données appariées, le bloc minimise la variabilité à l’intérieur d’un bloc, mais la variabilité entre blocs est grande. En fait, l’ANOVA en blocs complets aléatoires effectuée sur des paires est identique au test <span class="math inline">\(t\)</span> pour données appariées.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:bloc"></span>
<a href="images/Bloc.png" target="_blank"><img src="Module_8/images/Bloc.png" alt="Sélection aléatoire des blocs et assignation aléatoire de l'un des trois traitements aux unités expérimentales. À noter que chaque couleur correspond à l'un des trois traitements appliqués à chaque unité expérimentale d'un bloc ($n = 8$ blocs)." width="354" /></a>
<p class="caption">
Figure 8.5: Sélection aléatoire des blocs et assignation aléatoire de l’un des trois traitements aux unités expérimentales. À noter que chaque couleur correspond à l’un des trois traitements appliqués à chaque unité expérimentale d’un bloc (<span class="math inline">\(n = 8\)</span> blocs).
</p>
</div>
<p>Dans la figure <a href="théories-7.html#fig:bloc">8.5</a>, l’ANOVA en blocs complets aléatoires utilise huit blocs pour tester l’effet de trois traitements, alors que l’ANOVA à un critère classique aurait nécessité 24 unités expérimentales pour tester ces mêmes effets (Figure <a href="théories-7.html#fig:completelyrandomaov">8.3</a>). Étant donné ses avantages logistiques (p.ex., coût en temps et en argent), le dispositif en blocs complets aléatoires est beaucoup utilisé en sciences.</p>
</div>
<div id="origine-du-dispositif-en-blocs-complets-aléatoires" class="section level4 hasAnchor" number="8.1.2.2">
<h4><span class="header-section-number">8.1.2.2</span> Origine du dispositif en blocs complets aléatoires<a href="théories-7.html#origine-du-dispositif-en-blocs-complets-aléatoires" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le dispositif en blocs complets aléatoires a été développé en agronomie pour les cas où un <strong>gradient</strong> est présent sur les parcelles étudiées. On entend par gradient, un ensemble de conditions telles que l’humidité, la température, le pH ou l’exposition au soleil, qui varient sur un site d’étude ou dans un laboratoire. Les blocs sont disposés perpendiculairement au gradient (Figure <a href="théories-7.html#fig:blocgrad">8.6</a>), de façon à ce que les conditions à l’intérieur d’un bloc soient homogènes.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:blocgrad"></span>
<a href="images/Random_complete_blocks.png" target="_blank"><img src="Module_8/images/Random_complete_blocks.png" alt="Les blocs sont perpendiculaires au gradient (ici, le gradient va de gauche à droite). Cinq blocs ont été utilisés pour comparer trois traitements." width="345" /></a>
<p class="caption">
Figure 8.6: Les blocs sont perpendiculaires au gradient (ici, le gradient va de gauche à droite). Cinq blocs ont été utilisés pour comparer trois traitements.
</p>
</div>
</div>
<div id="particularité-du-dispositif-en-blocs-complets-aléatoires" class="section level4 hasAnchor" number="8.1.2.3">
<h4><span class="header-section-number">8.1.2.3</span> Particularité du dispositif en blocs complets aléatoires<a href="théories-7.html#particularité-du-dispositif-en-blocs-complets-aléatoires" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Comme il est illustré aux figures <a href="théories-7.html#fig:bloc">8.5</a> et <a href="théories-7.html#fig:blocgrad">8.6</a>, chaque bloc reçoit une seule répétition de chaque traitement, ce qui explique le terme “bloc complet” (chaque bloc reçoit tous les traitements). Les traitements sont assignés aléatoirement à chaque unité dans le bloc. Cette approche s’applique également en laboratoire lorsque l’espace est limité. Par exemple, on pourrait considérer des essais dans une chambre de croissance<a href="#fn24" class="footnote-ref" id="fnref24"><sup>24</sup></a> comme des blocs, où chaque essai consisterait à placer un plat de Petri pour chacun des traitements d’intérêt dans la chambre de croissance pendant une période donnée. Nous pourrions répéter la procédure plusieurs fois pour obtenir plusieurs essais. Comme autre exemple, on pourrait penser à des aquariums divisés en trois sections avec les mêmes densités de têtards de grenouilles, mais où chaque section recevrait différents prédateurs, afin d’estimer la survie des têtards. Ici, les aquariums représenteraient les blocs, puisque chaque aquarium donnerait trois observations (le nombre de survivants), soit une observation dans chaque section. Un dernier exemple serait une compagnie de raffinerie de pétrole qui s’intéresse à la performance en termes d’économie d’essence de 4 types d’essence qu’ils ont développés. Elle pourrait tester les 4 types d’essence sur 8 modèles de voitures sélectionnées aléatoirement.</p>
<p>Dans tous ces exemples, il y donc toujours un facteur dont l’effet nous intéresse (effet des prédateurs sur les têtards, effet des types d’essence sur l’économie) et un facteur qui ne nous intéresse pas ou peu (effet des différents aquariums, effet des différents modèles de voitures). Le premier facteur représente l’effet fixe et le second représente l’effet aléatoire.</p>
<p>L’ANOVA en blocs complets aléatoires est en fait une ANOVA à deux critères sans répétitions: il n’y a qu’une observation pour chaque combinaison de traitement et de bloc. Le facteur d’intérêt est un facteur fixe, alors que le bloc peut être considéré comme un facteur aléatoire. On suppose que les blocs sont différents entre eux. Afin d’optimiser ce dispositif, il faut s’assurer que les conditions soient homogènes à l’intérieur d’un bloc donné, et que les blocs diffèrent entre eux. Ceci a pour effet de minimiser la variabilité à l’intérieur d’un bloc et de maximiser la variabilité entre les blocs (<span class="math inline">\(\sigma^2_{\mathrm{intra-bloc}} &lt; \sigma^2_{\mathrm{inter-bloc}}\)</span>). Puiqu’il n’y aucune répétition à l’intérieur d’un même bloc (p.ex., une observation par traitement), il est impossible de tester le terme d’interaction bloc <span class="math inline">\(\times\)</span> traitement.</p>
<p>À l’instar de l’ANOVA à deux critères, le rejet de l’hypothèse nulle pour le facteur d’intérêt peut être suivi de comparaisons multiples pour déterminer où se trouvent les différences. Toutefois, si le facteur bloc explique une bonne partie de la variance et l’hypothèse nulle est rejetée pour le bloc (c.-à-d., <span class="math inline">\(P &lt; \alpha\)</span>), nous ne testons pas les différences entre blocs. Le facteur bloc n’est pas directement d’intérêt et il reflète simplement le dispositif qui a été utilisé. Le prochain exemple illustre l’application de l’ANOVA à ce dispositif expérimental.</p>
<hr />
<div class="exemple" section="8">
<p>On veut déterminer l’effet de quatre diètes différentes sur le gain de masse en grammes de cochons d’Inde. Chaque individu est placé dans une cage individuelle située dans un grand entrepôt. Étant donné qu’il n’y a qu’une source de chaleur à une extrémité de l’entrepôt, on pourrait s’attendre à avoir un gradient de température. On dispose les cages en blocs complets aléatoires de façon à avoir des groupes de quatre cages à différentes distances de la source de chaleur. On trouve ces données dans le fichier <code>cochons.txt</code>.</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="théories-7.html#cb427-1" tabindex="-1"></a><span class="do">##importation</span></span>
<span id="cb427-2"><a href="théories-7.html#cb427-2" tabindex="-1"></a>cochons <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;Module_8/data/cochons.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb427-3"><a href="théories-7.html#cb427-3" tabindex="-1"></a><span class="do">##premières observations</span></span>
<span id="cb427-4"><a href="théories-7.html#cb427-4" tabindex="-1"></a><span class="fu">head</span>(cochons)</span></code></pre></div>
<pre><code>##   Bloc Diete Masse
## 1    1     1   1.5
## 2    1     2   2.7
## 3    1     3   2.1
## 4    1     4   1.3
## 5    2     1   1.4
## 6    2     2   2.9</code></pre>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="théories-7.html#cb429-1" tabindex="-1"></a><span class="do">##structure du jeu de données</span></span>
<span id="cb429-2"><a href="théories-7.html#cb429-2" tabindex="-1"></a><span class="fu">str</span>(cochons)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  3 variables:
##  $ Bloc : int  1 1 1 1 2 2 2 2 3 3 ...
##  $ Diete: int  1 2 3 4 1 2 3 4 1 2 ...
##  $ Masse: num  1.5 2.7 2.1 1.3 1.4 2.9 2.2 1 1.4 2.1 ...</code></pre>
<p>Dans notre expérience, les deux facteurs sont <code>Bloc</code> et <code>Diete</code>. Toutefois, R considère ces deux variables comme numérique (des entiers). À chaque fois qu’un facteur est codé avec des valeurs numériques, comme ici 1, 2, 3, 4, il faut recoder soi-même la variable en facteur.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="théories-7.html#cb431-1" tabindex="-1"></a><span class="do">##convertir en facteur</span></span>
<span id="cb431-2"><a href="théories-7.html#cb431-2" tabindex="-1"></a>cochons<span class="sc">$</span>Bloc <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(cochons<span class="sc">$</span>Bloc)</span>
<span id="cb431-3"><a href="théories-7.html#cb431-3" tabindex="-1"></a>cochons<span class="sc">$</span>Diete <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(cochons<span class="sc">$</span>Diete)</span>
<span id="cb431-4"><a href="théories-7.html#cb431-4" tabindex="-1"></a><span class="do">##reconnus maintenant comme facteurs</span></span>
<span id="cb431-5"><a href="théories-7.html#cb431-5" tabindex="-1"></a><span class="fu">str</span>(cochons)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  3 variables:
##  $ Bloc : Factor w/ 5 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 1 2 2 2 2 3 3 ...
##  $ Diete: Factor w/ 4 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;: 1 2 3 4 1 2 3 4 1 2 ...
##  $ Masse: num  1.5 2.7 2.1 1.3 1.4 2.9 2.2 1 1.4 2.1 ...</code></pre>
<p>On peut visualiser les données à l’aide d’un diagramme de boîtes et moustaches (Figure <a href="théories-7.html#fig:boxplotcochon">8.7</a>).</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="théories-7.html#cb433-1" tabindex="-1"></a><span class="fu">boxplot</span>(Masse <span class="sc">~</span> Diete, <span class="at">data =</span> cochons, <span class="at">xlab =</span> <span class="st">&quot;Diète&quot;</span>, </span>
<span id="cb433-2"><a href="théories-7.html#cb433-2" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Gain de massse (g)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:boxplotcochon"></span>
<img src="Cours_Stats_R_files/figure-html/boxplotcochon-1.png" alt="Diagramme de boîtes et moustaches à partir des données de gain de masse de cochons d'Inde." width="672" />
<p class="caption">
Figure 8.7: Diagramme de boîtes et moustaches à partir des données de gain de masse de cochons d’Inde.
</p>
</div>
<p>Pour réaliser l’ANOVA à deux critères sans répétition, on utilise encore une fois <code>aov( )</code> :</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="théories-7.html#cb434-1" tabindex="-1"></a><span class="do">##ANOVA à deux critères sans répétition</span></span>
<span id="cb434-2"><a href="théories-7.html#cb434-2" tabindex="-1"></a>bloc.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Masse <span class="sc">~</span> Diete <span class="sc">+</span> Bloc, <span class="at">data =</span> cochons)</span></code></pre></div>
<p>Avant d’interpréter les résultats de l’ANOVA, nous devons vérifier les suppositions habituelles.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="théories-7.html#cb435-1" tabindex="-1"></a><span class="do">##vérification des suppositions</span></span>
<span id="cb435-2"><a href="théories-7.html#cb435-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb435-3"><a href="théories-7.html#cb435-3" tabindex="-1"></a><span class="fu">plot</span>(bloc.aov)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:aovblockfig"></span>
<img src="Cours_Stats_R_files/figure-html/aovblockfig-1.png" alt="Vérifications des suppositions d'homogénéité des variances et de la normalité des résidus." width="672" />
<p class="caption">
Figure 8.8: Vérifications des suppositions d’homogénéité des variances et de la normalité des résidus.
</p>
</div>
<p>On remarque que les variances sont légèrement hétérogènes (Figure <a href="théories-7.html#fig:aovblockfig">8.8</a>). Essayons une transformation logarithmique afin d’homogénéiser les variances :</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="théories-7.html#cb436-1" tabindex="-1"></a><span class="do">##ANOVA à deux critères sans répétition</span></span>
<span id="cb436-2"><a href="théories-7.html#cb436-2" tabindex="-1"></a><span class="do">##en utilisant le logarithme de la Masse</span></span>
<span id="cb436-3"><a href="théories-7.html#cb436-3" tabindex="-1"></a>bloc.aov.log <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log</span>(Masse) <span class="sc">~</span> Diete <span class="sc">+</span> Bloc, <span class="at">data =</span> cochons)</span></code></pre></div>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="théories-7.html#cb437-1" tabindex="-1"></a><span class="do">##vérification des suppositions</span></span>
<span id="cb437-2"><a href="théories-7.html#cb437-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb437-3"><a href="théories-7.html#cb437-3" tabindex="-1"></a><span class="fu">plot</span>(bloc.aov.log)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:blockdiaglog"></span>
<img src="Cours_Stats_R_files/figure-html/blockdiaglog-1.png" alt="Vérifications des suppositions d'homogénéité des variances et de la normalité des résidus avec les données log-transformées." width="672" />
<p class="caption">
Figure 8.9: Vérifications des suppositions d’homogénéité des variances et de la normalité des résidus avec les données log-transformées.
</p>
</div>
<p>On observe que la transformation logarithmique a permis de mieux respecter les suppositions (Figure <a href="théories-7.html#fig:blockdiaglog">8.9</a>).</p>
<p>Comparons maintenant l’ANOVA en blocs complets aléatoires et l’ANOVA à un critère avec ces mêmes données.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="théories-7.html#cb438-1" tabindex="-1"></a><span class="do">##ANOVA à 1 critère</span></span>
<span id="cb438-2"><a href="théories-7.html#cb438-2" tabindex="-1"></a>aov1.log <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log</span>(Masse) <span class="sc">~</span> Diete, <span class="at">data =</span> cochons)</span>
<span id="cb438-3"><a href="théories-7.html#cb438-3" tabindex="-1"></a><span class="do">##comparaisons ANOVA à 1 critère vs blocs</span></span>
<span id="cb438-4"><a href="théories-7.html#cb438-4" tabindex="-1"></a><span class="fu">summary</span>(aov1.log)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Diete        3 2.2515  0.7505   43.12 6.83e-08 ***
## Residuals   16 0.2784  0.0174                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="théories-7.html#cb440-1" tabindex="-1"></a><span class="fu">summary</span>(bloc.aov.log)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Diete        3 2.2515  0.7505  49.363 5.03e-07 ***
## Bloc         4 0.0960  0.0240   1.579    0.243    
## Residuals   12 0.1824  0.0152                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>On remarque que la somme des carrés du facteur <code>Diete</code> est le même pour les deux analyses (2.251). La différence entre l’ANOVA à un critère et l’ANOVA en blocs complets aléatoires est au niveau du terme d’erreur. Dans l’ANOVA en blocs complets aléatoires, la somme des carrés des erreurs (<span class="math inline">\(SSE\)</span>) est de 0.182, alors que celle de l’ANOVA à un critère est de 0.278. On constate que la somme des carrés du terme <code>Bloc</code> est de 0.096 et que cette valeur ajoutée à la somme de carrés des erreurs de l’ANOVA en blocs complets aléatoires donne un total de 0.278 (<span class="math inline">\(0.096 + 0.182 = 0.278\)</span>).</p>
<p>Le terme <code>Bloc</code> explique une partie de la variabilité de la variable réponse (<code>Masse</code>) et réduit le terme d’erreur. Ceci a pour conséquence de réduire le carré moyen de l’erreur (<span class="math inline">\(MSE\)</span>). Puisque le <span class="math inline">\(F\)</span> est le ratio entre le carré moyen de <code>Diete</code> et le carré moyen de l’erreur, la valeur du <span class="math inline">\(F\)</span> est plus grande en présence du bloc.</p>
<p>On constate que la diète influence fortement le gain de masse (<span class="math inline">\(F_{3, 12} = 49.36\)</span>, ) et que les blocs ne diffèrent pas entre eux (<span class="math inline">\(F_{4, 12} = 1.58, P = 0.24\)</span>). On peut procéder à des comparaisons multiples afin d’identifier les groupes définis par la diète.</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="théories-7.html#cb442-1" tabindex="-1"></a><span class="do">##moyennes des groupes</span></span>
<span id="cb442-2"><a href="théories-7.html#cb442-2" tabindex="-1"></a><span class="fu">tapply</span>(<span class="at">X =</span> cochons<span class="sc">$</span>Masse, <span class="at">INDEX =</span> cochons<span class="sc">$</span>Diete, <span class="at">FUN =</span> mean)</span></code></pre></div>
<pre><code>##    1    2    3    4 
## 1.38 2.80 2.24 1.24</code></pre>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="théories-7.html#cb444-1" tabindex="-1"></a><span class="do">##comparaisons multiples</span></span>
<span id="cb444-2"><a href="théories-7.html#cb444-2" tabindex="-1"></a><span class="fu">TukeyHSD</span>(<span class="at">x =</span> bloc.aov.log, <span class="at">which =</span> <span class="st">&quot;Diete&quot;</span>)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = log(Masse) ~ Diete + Bloc, data = cochons)
## 
## $Diete
##           diff        lwr         upr     p adj
## 2-1  0.6990462  0.4675197  0.93057281 0.0000060
## 3-1  0.4836196  0.2520930  0.71514616 0.0002317
## 4-1 -0.1143399 -0.3458665  0.11718666 0.4856391
## 3-2 -0.2154267 -0.4469532  0.01609992 0.0712144
## 4-2 -0.8133862 -1.0449127 -0.58185959 0.0000012
## 4-3 -0.5979595 -0.8294861 -0.36643294 0.0000299</code></pre>
<p>Les comparaisons multiples identifient deux groupes, le premier est constitué des diètes 4 et 1, et le deuxième est composé des diètes 2 et 3 :</p>
<table>
<tr>
<th style="border: 0px solid black; padding: 3px;">
4
</th>
<th style="border: 0px solid black; padding: 3px;">
1
</th>
<th style="border: 0px solid black; padding: 3px;">
2
</th>
<th style="border: 0px solid black; padding: 3px;">
3
</th>
</tr>
<tr>
<td>
1.24<sup>2</sup>
</td>
<td>
1.38<sup>2</sup>
</td>
<td>
2.24<sup>2</sup>
</td>
<td>
2.80<sup>2</sup>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 2px solid;">
 
</td>
<td>
 
</td>
<td>
 
</td>
</tr>
<tr>
<td>
 
</td>
<td>
 
</td>
<td colspan="2" style="border-bottom: 2px solid;">
 
</td>
</tr>
</table>
<p>On peut présenter les résultats graphiquement.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="théories-7.html#cb446-1" tabindex="-1"></a><span class="do">##Définissons l&#39;axe des x de la figure, c&#39;est à dire les diètes</span></span>
<span id="cb446-2"><a href="théories-7.html#cb446-2" tabindex="-1"></a>diete <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span></span>
<span id="cb446-3"><a href="théories-7.html#cb446-3" tabindex="-1"></a></span>
<span id="cb446-4"><a href="théories-7.html#cb446-4" tabindex="-1"></a><span class="do">##Puis, calculons les moyennes sur les donnees transformees</span></span>
<span id="cb446-5"><a href="théories-7.html#cb446-5" tabindex="-1"></a>means.log <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> <span class="fu">log</span>(cochons<span class="sc">$</span>Masse), <span class="at">INDEX =</span> cochons<span class="sc">$</span>Diete, <span class="at">FUN =</span> mean)</span>
<span id="cb446-6"><a href="théories-7.html#cb446-6" tabindex="-1"></a></span>
<span id="cb446-7"><a href="théories-7.html#cb446-7" tabindex="-1"></a><span class="do">##Il nous faut maintenant trouver le MSE. </span></span>
<span id="cb446-8"><a href="théories-7.html#cb446-8" tabindex="-1"></a><span class="do">##Pour se faire, nous devons nous référer au résumé de l&#39;ANOVA</span></span>
<span id="cb446-9"><a href="théories-7.html#cb446-9" tabindex="-1"></a><span class="fu">summary</span>(bloc.aov.log)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Diete        3 2.2515  0.7505  49.363 5.03e-07 ***
## Bloc         4 0.0960  0.0240   1.579    0.243    
## Residuals   12 0.1824  0.0152                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="théories-7.html#cb448-1" tabindex="-1"></a><span class="do">##Le MSE est la valeur données à la ligne Residuals de la colonne Mean Sq</span></span>
<span id="cb448-2"><a href="théories-7.html#cb448-2" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> <span class="fl">0.0152</span></span>
<span id="cb448-3"><a href="théories-7.html#cb448-3" tabindex="-1"></a><span class="do">##On peut aussi le trouver de cette façon:</span></span>
<span id="cb448-4"><a href="théories-7.html#cb448-4" tabindex="-1"></a>S<span class="ot">&lt;-</span><span class="fu">summary</span>(bloc.aov.log)</span>
<span id="cb448-5"><a href="théories-7.html#cb448-5" tabindex="-1"></a>MSE<span class="ot">&lt;-</span>S[[<span class="dv">1</span>]][[<span class="dv">3</span>]][[<span class="dv">3</span>]]</span>
<span id="cb448-6"><a href="théories-7.html#cb448-6" tabindex="-1"></a></span>
<span id="cb448-7"><a href="théories-7.html#cb448-7" tabindex="-1"></a><span class="do">##Calculons maintenant les barres d&#39;erreur</span></span>
<span id="cb448-8"><a href="théories-7.html#cb448-8" tabindex="-1"></a>low.log <span class="ot">&lt;-</span> means.log <span class="sc">-</span> <span class="fu">sqrt</span>(MSE)</span>
<span id="cb448-9"><a href="théories-7.html#cb448-9" tabindex="-1"></a>upp.log <span class="ot">&lt;-</span> means.log <span class="sc">+</span> <span class="fu">sqrt</span>(MSE)</span>
<span id="cb448-10"><a href="théories-7.html#cb448-10" tabindex="-1"></a></span>
<span id="cb448-11"><a href="théories-7.html#cb448-11" tabindex="-1"></a><span class="do">##On affiche les moyennes</span></span>
<span id="cb448-12"><a href="théories-7.html#cb448-12" tabindex="-1"></a><span class="fu">plot</span>(means.log <span class="sc">~</span> diete, <span class="at">ylab =</span> <span class="st">&quot;Log du gain de masse (g)&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Diète&quot;</span>,</span>
<span id="cb448-13"><a href="théories-7.html#cb448-13" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;p&quot;</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fu">min</span>(low.log), <span class="fu">max</span>(upp.log)), </span>
<span id="cb448-14"><a href="théories-7.html#cb448-14" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">cex.lab =</span> <span class="fl">1.2</span>, <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb448-15"><a href="théories-7.html#cb448-15" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Log des Moyennes ± racine carrée de MSE&quot;</span>)</span>
<span id="cb448-16"><a href="théories-7.html#cb448-16" tabindex="-1"></a></span>
<span id="cb448-17"><a href="théories-7.html#cb448-17" tabindex="-1"></a><span class="do">##Ajoutons l&#39;axe des x</span></span>
<span id="cb448-18"><a href="théories-7.html#cb448-18" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>))</span>
<span id="cb448-19"><a href="théories-7.html#cb448-19" tabindex="-1"></a></span>
<span id="cb448-20"><a href="théories-7.html#cb448-20" tabindex="-1"></a><span class="do">##Ajoutons les barres d&#39;erreur</span></span>
<span id="cb448-21"><a href="théories-7.html#cb448-21" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> diete, <span class="at">x1 =</span> diete, <span class="at">y0 =</span> low.log, <span class="at">y1 =</span> upp.log,</span>
<span id="cb448-22"><a href="théories-7.html#cb448-22" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">code =</span> <span class="dv">3</span>, <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb448-23"><a href="théories-7.html#cb448-23" tabindex="-1"></a></span>
<span id="cb448-24"><a href="théories-7.html#cb448-24" tabindex="-1"></a><span class="do">##Ajoutons les lettres qui designent les groupes</span></span>
<span id="cb448-25"><a href="théories-7.html#cb448-25" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">0.18</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb448-26"><a href="théories-7.html#cb448-26" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="fl">0.07</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb448-27"><a href="théories-7.html#cb448-27" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">0.88</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb448-28"><a href="théories-7.html#cb448-28" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">0.66</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotres"></span>
<img src="Cours_Stats_R_files/figure-html/plotres-1.png" alt="Effet de la diète sur le logarithme du gain de masse. Les lettres différentes indiquent les groupes." width="672" />
<p class="caption">
Figure 8.10: Effet de la diète sur le logarithme du gain de masse. Les lettres différentes indiquent les groupes.
</p>
</div>
<p>Pour faciliter l’interprétation de notre analyse représentons les données originales plutôt que les données transformées.</p>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="théories-7.html#cb449-1" tabindex="-1"></a><span class="do">##Calculons les moyennes sur les donnees originales</span></span>
<span id="cb449-2"><a href="théories-7.html#cb449-2" tabindex="-1"></a>means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(<span class="at">X =</span> cochons<span class="sc">$</span>Masse, <span class="at">INDEX =</span> cochons<span class="sc">$</span>Diete, <span class="at">FUN =</span> mean)</span>
<span id="cb449-3"><a href="théories-7.html#cb449-3" tabindex="-1"></a></span>
<span id="cb449-4"><a href="théories-7.html#cb449-4" tabindex="-1"></a><span class="do">##Les barres d&#39;erreurs sur les donnees originales se determinent en prenant la fonction exp() </span></span>
<span id="cb449-5"><a href="théories-7.html#cb449-5" tabindex="-1"></a><span class="do">## sur les barres d&#39;erreurs des donnees transformees</span></span>
<span id="cb449-6"><a href="théories-7.html#cb449-6" tabindex="-1"></a>low <span class="ot">&lt;-</span> <span class="fu">exp</span>(low.log) </span>
<span id="cb449-7"><a href="théories-7.html#cb449-7" tabindex="-1"></a>upp <span class="ot">&lt;-</span> <span class="fu">exp</span>(upp.log) </span>
<span id="cb449-8"><a href="théories-7.html#cb449-8" tabindex="-1"></a></span>
<span id="cb449-9"><a href="théories-7.html#cb449-9" tabindex="-1"></a></span>
<span id="cb449-10"><a href="théories-7.html#cb449-10" tabindex="-1"></a><span class="do">##On cree la figure</span></span>
<span id="cb449-11"><a href="théories-7.html#cb449-11" tabindex="-1"></a><span class="fu">plot</span>(means <span class="sc">~</span> diete, <span class="at">ylab =</span> <span class="st">&quot;Gain de masse (g)&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Diète&quot;</span>,</span>
<span id="cb449-12"><a href="théories-7.html#cb449-12" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;p&quot;</span>, <span class="at">ylim =</span> <span class="fu">c</span>((<span class="fu">min</span>(low)<span class="sc">-</span><span class="fl">0.2</span>), <span class="fu">max</span>(upp)), </span>
<span id="cb449-13"><a href="théories-7.html#cb449-13" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>), <span class="at">cex.lab =</span> <span class="fl">1.2</span>, <span class="at">xaxt =</span> <span class="st">&quot;n&quot;</span>, </span>
<span id="cb449-14"><a href="théories-7.html#cb449-14" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Moyennes ± racine carrée de MSE&quot;</span>)</span>
<span id="cb449-15"><a href="théories-7.html#cb449-15" tabindex="-1"></a></span>
<span id="cb449-16"><a href="théories-7.html#cb449-16" tabindex="-1"></a><span class="do">##Ajoutons l&#39;axe des x</span></span>
<span id="cb449-17"><a href="théories-7.html#cb449-17" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>))</span>
<span id="cb449-18"><a href="théories-7.html#cb449-18" tabindex="-1"></a></span>
<span id="cb449-19"><a href="théories-7.html#cb449-19" tabindex="-1"></a><span class="do">##Ajoutons les barres d&#39;erreur</span></span>
<span id="cb449-20"><a href="théories-7.html#cb449-20" tabindex="-1"></a><span class="fu">arrows</span>(<span class="at">x0 =</span> diete, <span class="at">x1 =</span> diete, <span class="at">y0 =</span> low, <span class="at">y1 =</span> upp,</span>
<span id="cb449-21"><a href="théories-7.html#cb449-21" tabindex="-1"></a>       <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">code =</span> <span class="dv">3</span>, <span class="at">length =</span> <span class="fl">0.05</span>)</span>
<span id="cb449-22"><a href="théories-7.html#cb449-22" tabindex="-1"></a></span>
<span id="cb449-23"><a href="théories-7.html#cb449-23" tabindex="-1"></a><span class="do">##Ajoutons les lettres qui designent les groupes</span></span>
<span id="cb449-24"><a href="théories-7.html#cb449-24" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fl">1.19</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb449-25"><a href="théories-7.html#cb449-25" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">4</span>, <span class="at">y =</span> <span class="fl">1.0</span>, <span class="at">labels =</span> <span class="st">&quot;a&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb449-26"><a href="théories-7.html#cb449-26" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="fl">2.4</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span>
<span id="cb449-27"><a href="théories-7.html#cb449-27" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="fl">1.9</span>, <span class="at">labels =</span> <span class="st">&quot;b&quot;</span>, <span class="at">cex =</span> <span class="fl">1.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:plotresorig"></span>
<img src="Cours_Stats_R_files/figure-html/plotresorig-1.png" alt="Effet de la diète sur le gain de masse. Les lettres différentes indiquent les groupes.}" width="672" />
<p class="caption">
Figure 8.11: Effet de la diète sur le gain de masse. Les lettres différentes indiquent les groupes.}
</p>
</div>
<p>Sur la figure <a href="théories-7.html#fig:plotresorig">8.11</a>, on constate la présence de deux groupes de diètes. Le premier groupe est composé des diètes 4 et 1, et le deuxième est constitué des groupes 3 et 2. De plus, on peut conclure que les diètes 4 et 1 augmentent moins le gain de masse que les diètes 3 et 2.</p>
</div>
<hr />
</div>
<div id="applications-moins-conventionnelles" class="section level4 hasAnchor" number="8.1.2.4">
<h4><span class="header-section-number">8.1.2.4</span> Applications moins conventionnelles<a href="théories-7.html#applications-moins-conventionnelles" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Typiquement en agronomie ou en écologie forestière, les blocs sont disposés dans l’espace et perpendiculaires à un gradient. Toutefois, on peut aussi disposer les blocs dans le temps. Par exemple, considérons une expérience de germination de graines en serre (croissance en une semaine), où l’on ne peut pas répéter tous les traitements d’intérêt dû à un manque d’espace. Pour pallier le problème, on peut créer des blocs temporels de façon à avoir une répétition de chaque traitement et à effectuer un bloc par semaine.</p>
<p>Dans d’autres cas, on peut avoir plusieurs mesures sur un même individu. L’individu constituera le bloc. Pour illustrer ce concept, imaginons une expérience sur la production de lait par des vaches avec différents types de fourrage (p.ex., luzerne, trèfle, blé, maïs). Si on soupçonne que la production de lait varie beaucoup entre les vaches, on pourrait traiter chaque vache comme un bloc. Chaque vache recevrait chacun des traitements, dans une séquence aléatoire et avec suffisamment de temps entre les traitements pour éviter de contaminer les réponses des vaches par l’effet du fourrage précédent. De cette façon, on peut mieux contrôler les différences individuelles en comparant la réponse d’un même individu à différents traitements.</p>
<p>Un autre exemple serait de suivre les résultats d’élèves à différentes périodes lors desquelles ils auraient utilisé différentes méthodes d’apprentissage. Chaque élève représenterait un bloc complet et utiliserait toutes les méthodes à travers le temps dans un ordre aléatoire. De cette façon, on peut contrôler pour la grande variabilité inter-élève et se concentrer sur l’effet des méthodes d’apprentissage.</p>
</div>
<div id="conditions-dapplication" class="section level4 hasAnchor" number="8.1.2.5">
<h4><span class="header-section-number">8.1.2.5</span> Conditions d’application<a href="théories-7.html#conditions-dapplication" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>En plus des conditions nécessaires à l’ANOVA classique (homogénéité des variances, normalité des résidus), il faut respecter les conditions suivantes :</p>
<ul>
<li>chaque bloc doit être suffisamment petit pour assurer des conditions homogènes à l’intérieur du bloc;</li>
<li>chaque bloc doit être suffisamment grand pour accommoder une répétition de chaque traitement: il doit y avoir assez de place pour que les répétitions de chaque traitement soient espacées afin d’être indépendantes. En d’autres mots, l’observation provenant d’un traitement dans un bloc ne doit pas être influencée par un traitement adjacent du même bloc (p.ex., l’application de différentes concentrations d’engrais à des parcelles d’un bloc et le ruissellement contaminant le traitement d’une parcelle adjacent du même bloc);</li>
<li>les blocs doivent être suffisamment espacés afin d’être indépendants les uns des autres;</li>
<li>il ne doit y avoir aucune interaction entre les blocs et les traitements (effets additifs seulement): l’effet d’un traitement doit être constant pour tous les blocs.</li>
</ul>
</div>
<div id="avantages-du-dispositif-en-blocs-complets-aléatoires" class="section level4 hasAnchor" number="8.1.2.6">
<h4><span class="header-section-number">8.1.2.6</span> Avantages du dispositif en blocs complets aléatoires<a href="théories-7.html#avantages-du-dispositif-en-blocs-complets-aléatoires" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le dispositif en blocs complets aléatoires comporte plusieurs avantages, notamment :</p>
<ul>
<li>il contrôle l’hétérogénéité environnementale (tient compte des gradients) qui autrement ferait augmenter le carré moyen des erreurs (<span class="math inline">\(MSE\)</span>) et rendrait plus difficile de rejeter l’hypothèse nulle concernant le facteur d’intérêt;</li>
<li>en présence de gradients, l’ANOVA en blocs complets aléatoires est plus puissante que l’ANOVA complètement aléatoire;</li>
<li>il est logistiquement intéressant lorsque la répétition est contrainte dans l’espace ou le temps;</li>
<li>il peut être utilisé avec un design apparié (p.ex., &gt; 2 observations par bloc) pour tenir compte de facteurs additionnels tels que la variabilité entre les individus d’une même famille.</li>
</ul>
</div>
<div id="désavantages-du-dispositif-en-blocs-complets-aléatoires" class="section level4 hasAnchor" number="8.1.2.7">
<h4><span class="header-section-number">8.1.2.7</span> Désavantages du dispositif en blocs complets aléatoires<a href="théories-7.html#désavantages-du-dispositif-en-blocs-complets-aléatoires" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Le dispositif en blocs complets aléatoires comporte certains désavantages, notamment :</p>
<ul>
<li>il y a un coût statistique à utiliser les blocs. Si l’effectif (<span class="math inline">\(n\)</span>) est petit et si l’effet du bloc est faible, l’ANOVA à un critère est plus puissante dans ce cas.</li>
<li>avec des blocs trop petits, on risque d’introduire une dépendance des observations soumis aux différents traitements d’un même bloc, si les traitements sont physiquement près les uns des autres;</li>
<li>il faut un dispositif complètement balancé: si on a au moins une donnée manquante dans un bloc, on doit se débarrasser du bloc ou estimer les valeurs des données manquantes;</li>
<li>s’il y a une interaction entre les blocs et les traitements (effets non-additifs), on a un problème puisqu’on ne peut tester l’interaction en l’absence de répétitions. Si on soupçonne un potentiel effet interactif, il faut prévoir récolter plus d’une observation d’un même traitement dans chaque bloc pour le tester formellement. Le cas échéant, on utilisera une analyse plus complexe, telle que l’ANOVA en tiroirs (<em>split-plot</em>)<a href="#fn25" class="footnote-ref" id="fnref25"><sup>25</sup></a>. Une autre option est de mesurer directement la variable qui est responsable du gradient (p.ex., humidité, ensoleillement, position dans la pente).</li>
</ul>
</div>
</div>
<div id="conclusion-7" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Conclusion<a href="théories-7.html#conclusion-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dans cette leçon, nous avons revisité différents types de dispositifs associés aux analyses vues jusqu’à présent dans le cours. Nous avons présenté les concepts d’effets fixes et d’effets aléatoires ainsi que de modèle mixte. Nous avons présenté l’ANOVA en blocs complets aléatoires comme étant le cas le plus simple de modèle mixte et comme l’extension du test <span class="math inline">\(t\)</span> pour les données appariées. Le dispositif en blocs complets aléatoires se caractérise par la disposition de blocs perpendiculaires à un gradient. Ce gradient n’est pas mesuré directement, mais les blocs sont une mesure indirecte de la variabilité associée à ce gradient. Ce dispositif comporte des avantages importants, notamment sur le plan logistique comparé aux dispositifs complètement aléatoires (p.ex., ANOVA à un critère avec répétitions, ANOVA à deux critères avec répétitions). Bien qu’à l’origine le dispositif en blocs complets aléatoires ait été développé en agronomie, il est maintenant utilisé dans des disciplines variées incluant les sciences environnementales, la médecine, la chimie et le marketing. La prochaine leçon traitera de façon plus générale de l’élaboration de dispositifs expérimentaux et de recommandations afin d’arriver à des conclusions solides.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="23">
<li id="fn23"><p>Le cas opposé, avec A fixe et B aléatoire, est bien sûr équivalent.<a href="théories-7.html#fnref23" class="footnote-back">↩︎</a></p></li>
<li id="fn24"><p>Une chambre de croissance est un contenant isotherme dans lequel les conditions sont contrôlées afin d’optimiser la croissance de plantes ou de cultures.<a href="théories-7.html#fnref24" class="footnote-back">↩︎</a></p></li>
<li id="fn25"><p>Ce dispositif plus complexe ne sera pas vu dans le cours.<a href="théories-7.html#fnref25" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="blocs-complets-aléatoires.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exercices-5.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/Module_8/Module_8.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Cours_Stats_R.pdf", "Cours_Stats_R.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
